/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/integration_test_build_payload.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@fcher@fbf.nim.c.o /home/becker/projects/libnet/nimcache/tests/integration_test_build_payload.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@fcher@fbf.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <unistd.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__rz9by4t7i52ayGwIPpdG9akQ tySequence__rz9by4t7i52ayGwIPpdG9akQ;
typedef struct tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content;
typedef struct tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__rz9by4t7i52ayGwIPpdG9akQ {
  NI len; tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__rz9by4t7i52ayGwIPpdG9akQ trace;
	Exception* up;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content { NI cap; tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getApplAux__cherZbf_u182)(NimStringV2 procPath_p0);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___flfgrz_u2696)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getApplHeuristic__cherZbf_u186)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, paramStr__fgqZpzqyvar_u55)(NI i_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__fgqZraiinef_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__flfgrz_u8960)(NimStringV2 s_p0, NI first_p1, NI last_p2);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___flfgrz_u2687)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, eqdestroy___flfgrz_u281)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___fgqZglcrqguernqf_u223)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShellPosix)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, allCharsInSet__cherZfgehgvyf_u1568)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw theSet_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___flfgrz_u2690)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__flfgrz_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuReplaceStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NimStringV2 by_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_3 = { 14 | NIM_STRLIT_FLAG, "/proc/self/exe" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_4 = {14, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_3};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_5 = { 4 | NIM_STRLIT_FLAG, "PATH" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_6 = {4, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_5};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_7 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_8 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_7};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_13 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_7};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_14 = { 2 | NIM_STRLIT_FLAG, "\'\'" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_15 = {2, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_14};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__yu6cxgKBBXbNsTkT9cyMd4g_16 = {
0x00, 0x00, 0x00, 0x00, 0x20, 0xe8, 0xff, 0x27,
0xff, 0xff, 0xff, 0x87, 0xfe, 0xff, 0xff, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_17 = { 1 | NIM_STRLIT_FLAG, "\'" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_18 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_17};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_20 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_17};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_21 = { 5 | NIM_STRLIT_FLAG, "\'\"\'\"\'" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_22 = {5, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_21};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_23 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_17};
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4491;
extern NIM_THREADVAR Exception* currException__flfgrz_u4136;
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2723;
	framePtr__flfgrz_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2723 = (*framePtr__flfgrz_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getApplAux__cherZbf_u182)(NimStringV2 procPath_p0) {
	NimStringV2 result;
	NI len_1;
	nimfr_("getApplAux", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");
{	nimlf_(563, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");	result = mnewString(((NI)1024));
	nimln_(564);	len_1 = readlink(nimToCStringConv(procPath_p0), nimToCStringConv(result), ((NI)1024));
	nimln_(565);	{
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_2;
		NimStringV2 T5_;
		if (!(((NI)1024) < len_1)) goto LA3_;
		nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");		nimlf_(566, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");		if (nimAddInt(len_1, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_2)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_2)) < ((NI)0) || ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_2)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_2), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		T5_.len = 0; T5_.p = NIM_NIL;
		T5_ = mnewString(((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_2)));
		nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");		eqsink___flfgrz_u2696((&result), T5_);
		nimlf_(567, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");		len_1 = readlink(nimToCStringConv(procPath_p0), nimToCStringConv(result), len_1);
	}
LA3_: ;
	nimln_(568);	if ((len_1) < ((NI)0) || (len_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(len_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	setLengthStrV2((&result), (len_1));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4491);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getApplHeuristic__cherZbf_u186)(void) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("getApplHeuristic", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(607);	result = paramStr__fgqZpzqyvar_u55(((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(610);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) < result.len);
		if (!(T3_)) goto LA4_;
		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		T3_ = !(((NU8)(result.p->data[((NI)0)]) == (NU8)(47)));
LA4_: ;
		if (!T3_) goto LA5_;
		{
			NimStringV2 p_1;
			NimStringV2 colontmp_;
			NI lastX60gensym37__1;
			NI splitsX60gensym37__1;
			p_1.len = 0; p_1.p = NIM_NIL;
			colontmp_.len = 0; colontmp_.p = NIM_NIL;
			nimlf_(451, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");			nimlf_(612, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");			colontmp_ = getEnv__fgqZraiinef_u15(TM__yu6cxgKBBXbNsTkT9cyMd4g_6, TM__yu6cxgKBBXbNsTkT9cyMd4g_8);
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			nimlf_(389, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");			lastX60gensym37__1 = ((NI)0);
			nimln_(390);			splitsX60gensym37__1 = ((NI)-1);
			{
				nimln_(506);				while (1) {
					NimStringV2 x_1;
					NI firstX60gensym37__1;
					NI TM__yu6cxgKBBXbNsTkT9cyMd4g_10;
					NimStringV2 T20_;
					NI TM__yu6cxgKBBXbNsTkT9cyMd4g_11;
					NI TM__yu6cxgKBBXbNsTkT9cyMd4g_12;
					nimln_(392);					if (!(lastX60gensym37__1 <= colontmp_.len)) goto LA10;
					x_1.len = 0; x_1.p = NIM_NIL;
					nimln_(393);					firstX60gensym37__1 = lastX60gensym37__1;
					{
						nimln_(394);						while (1) {
							NIM_BOOL T14_;
							NI TM__yu6cxgKBBXbNsTkT9cyMd4g_9;
							T14_ = (NIM_BOOL)0;
							T14_ = (lastX60gensym37__1 < colontmp_.len);
							if (!(T14_)) goto LA15_;
							if (lastX60gensym37__1 < 0 || lastX60gensym37__1 >= colontmp_.len){ raiseIndexError2(lastX60gensym37__1,colontmp_.len-1); goto LA11_;
							}
							T14_ = !((((NU8)(colontmp_.p->data[lastX60gensym37__1])) == ((NU8)(58))));
LA15_: ;
							if (!T14_) goto LA13;
							nimln_(395);							if (nimAddInt(lastX60gensym37__1, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_9)) { raiseOverflow(); goto LA11_;
							};
							lastX60gensym37__1 = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_9);
						} LA13: ;
					}
					nimln_(396);					{
						if (!(splitsX60gensym37__1 == ((NI)0))) goto LA18_;
						lastX60gensym37__1 = colontmp_.len;
					}
LA18_: ;
					nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");					nimlf_(612, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");					nimlf_(397, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");					if (nimSubInt(lastX60gensym37__1, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_10)) { raiseOverflow(); goto LA11_;
					};
					nimlf_(612, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");					T20_.len = 0; T20_.p = NIM_NIL;
					T20_ = substr__flfgrz_u8960(colontmp_, firstX60gensym37__1, (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_10));
					nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");					eqsink___flfgrz_u2696((&p_1), T20_);
					nimlf_(613, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");					x_1 = nosjoinPath(p_1, result);
					if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
					nimln_(614);					{
						NIM_BOOL T23_;
						T23_ = (NIM_BOOL)0;
						T23_ = nosfileExists(x_1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
						if (!T23_) goto LA24_;
						nimln_(605);						nimln_(614);						result = x_1;
						nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");						eqwasMoved___flfgrz_u2687((&x_1));
						nimln_(394);						if (x_1.p && !(x_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(x_1.p);
}
						if (colontmp_.p && !(colontmp_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_.p);
}
						if (p_1.p && !(p_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(p_1.p);
}
						goto BeforeRet_;
					}
LA24_: ;
					nimlf_(398, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");					{
						if (!(splitsX60gensym37__1 == ((NI)0))) goto LA28_;
						nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");						if (x_1.p && !(x_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(x_1.p);
}
						nimlf_(398, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");						goto LA9;
					}
LA28_: ;
					nimln_(399);					if (nimSubInt(splitsX60gensym37__1, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_11)) { raiseOverflow(); goto LA11_;
					};
					splitsX60gensym37__1 = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_11);
					nimln_(400);					if (nimAddInt(lastX60gensym37__1, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_12)) { raiseOverflow(); goto LA11_;
					};
					lastX60gensym37__1 = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_12);
					{
						LA11_:;
					}
					{
						nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");						if (x_1.p && !(x_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(x_1.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				} LA10: ;
			} LA9: ;
			{
				LA8_:;
			}
			{
				if (colontmp_.p && !(colontmp_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_.p);
}
				if (p_1.p && !(p_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(p_1.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
	}
LA5_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, eqdestroy___flfgrz_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");
	popFrame();
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isObjDisplayCheck", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/arc.nim");
	nimlf_(266, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/arc.nim");	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	nimfr_("nimBorrowCurrentException", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");
	nimlf_(2301, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");	result = currException__flfgrz_u4136;
	popFrame();
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___fgqZglcrqguernqf_u223(&currException__flfgrz_u4136, (*currException__flfgrz_u4136).up, NIM_FALSE);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetAppFilename)(void) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("getAppFilename", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(690, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");	result = getApplAux__cherZbf_u182(TM__yu6cxgKBBXbNsTkT9cyMd4g_4);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(705);	{
		NimStringV2 T6_;
		NimStringV2 T7_;
		if (!(result.len == ((NI)0))) goto LA3_;
		T6_.len = 0; T6_.p = NIM_NIL;
		nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");		nimlf_(706, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = getApplHeuristic__cherZbf_u186();
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___flfgrz_u281(T7_); goto LA5_;}
		nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");		eqsink___flfgrz_u2696((&result), T7_);
		if (NIM_UNLIKELY(*nimErr_)) {
			LA5_:;
			if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 3158777856)) {
				*nimErr_ = NIM_FALSE;
				eqsink___flfgrz_u2696((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_13);
				popCurrentException();
				LA9_:;
			}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__flfgrz_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_19;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__flfgrz_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__yu6cxgKBBXbNsTkT9cyMd4g_19)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_19);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShellPosix)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("quoteShellPosix", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(177, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		nimln_(178);		result = TM__yu6cxgKBBXbNsTkT9cyMd4g_15;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(179);		T6_ = (NIM_BOOL)0;
		T6_ = allCharsInSet__cherZfgehgvyf_u1568(s_p0, TM__yu6cxgKBBXbNsTkT9cyMd4g_16);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T6_) goto LA7_;
		nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");		eqcopy___flfgrz_u2690((&result), s_p0);
	}
	goto LA1_;
LA7_: ;
	{
		NimStringV2 colontmpD_;
		NimStringV2 T10_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimlf_(182, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");		T10_.len = 0; T10_.p = NIM_NIL;
		colontmpD_ = nsuReplaceStr(s_p0, TM__yu6cxgKBBXbNsTkT9cyMd4g_20, TM__yu6cxgKBBXbNsTkT9cyMd4g_22);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T10_ = rawNewString(colontmpD_.len + 2);
appendString((&T10_), TM__yu6cxgKBBXbNsTkT9cyMd4g_18);
appendString((&T10_), colontmpD_);
appendString((&T10_), TM__yu6cxgKBBXbNsTkT9cyMd4g_23);
		result = T10_;
		nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShell)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("quoteShell", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(193, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/os.nim");	result = nospquoteShellPosix(s_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
