/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/integration_test_build_payload.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@ffgq@fpzqyvar.nim.c.o /home/becker/projects/libnet/nimcache/tests/integration_test_build_payload.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@ffgq@fpzqyvar.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg;
typedef struct tyObject_Defect__voUWI9axWVRIEz4prik9b4nA tyObject_Defect__voUWI9axWVRIEz4prik9b4nA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__rz9by4t7i52ayGwIPpdG9akQ tySequence__rz9by4t7i52ayGwIPpdG9akQ;
typedef struct tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__rz9by4t7i52ayGwIPpdG9akQ {
  NI len; tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__rz9by4t7i52ayGwIPpdG9akQ trace;
	Exception* up;
};
struct tyObject_Defect__voUWI9axWVRIEz4prik9b4nA {
	Exception Sup;
};
struct tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg {
	tyObject_Defect__voUWI9axWVRIEz4prik9b4nA Sup;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content { NI cap; tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___flfgrz_u2687)(NimStringV2* dest_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__flfgrz_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___flfgrzZqbyynef_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___flfgrzZqbyynef_u29)(NI32 xX60gensym3__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NI, paramCount__fgqZpzqyvar_u61)(void);
N_LIB_PRIVATE N_NIMCALL(void, add__fgqZrahzhgvyf_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, paramStr__fgqZpzqyvar_u55)(NI i_p0);
static N_INLINE(void, eqdestroy___flfgrz_u281)(NimStringV2 x_p0);
extern TNimTypeV2 NTIv2__7u631KbObzc6JqpFYL4zNg_;
static const struct {
  NI cap; NIM_CHAR data[43+1];
} TM__MZPGKsURfItHSi3RvnOT8Q_3 = { 43 | NIM_STRLIT_FLAG, "index out of bounds, the container is empty" };
static const NimStringV2 TM__MZPGKsURfItHSi3RvnOT8Q_4 = {43, (NimStrPayload*)&TM__MZPGKsURfItHSi3RvnOT8Q_3};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__MZPGKsURfItHSi3RvnOT8Q_5 = { 6 | NIM_STRLIT_FLAG, "index " };
static const NimStringV2 TM__MZPGKsURfItHSi3RvnOT8Q_6 = {6, (NimStrPayload*)&TM__MZPGKsURfItHSi3RvnOT8Q_5};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__MZPGKsURfItHSi3RvnOT8Q_8 = { 13 | NIM_STRLIT_FLAG, " not in 0 .. " };
static const NimStringV2 TM__MZPGKsURfItHSi3RvnOT8Q_9 = {13, (NimStrPayload*)&TM__MZPGKsURfItHSi3RvnOT8Q_8};
extern int cmdCount;
extern NCSTRING* cmdLine;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4491;
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2723;
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__flfgrz_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__MZPGKsURfItHSi3RvnOT8Q_7;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__flfgrz_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__MZPGKsURfItHSi3RvnOT8Q_7)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__MZPGKsURfItHSi3RvnOT8Q_7);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4491);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2723;
	framePtr__flfgrz_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2723 = (*framePtr__flfgrz_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, paramStr__fgqZpzqyvar_u55)(NI i_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("paramStr", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/cmdline.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(269, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/cmdline.nim");	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (i_p0 < ((NI) (cmdCount)));
		if (!(T3_)) goto LA4_;
		T3_ = (((NI)0) <= i_p0);
LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(270);		result = cstrToNimstr(cmdLine[i_p0]);
	}
	goto LA1_;
LA5_: ;
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg* T9_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		T9_ = NIM_NIL;
		T9_ = (tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg*) nimNewObj(sizeof(tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg), NIM_ALIGNOF(tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg));
		(*T9_).Sup.Sup.Sup.m_type = (&NTIv2__7u631KbObzc6JqpFYL4zNg_);
		(*T9_).Sup.Sup.name = "IndexDefect";
		nimln_(272);		{
			NI TM__MZPGKsURfItHSi3RvnOT8Q_2;
			NimStringV2 blitTmp_1;
			nimlf_(8, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/indexerrors.nim");			nimlf_(272, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/cmdline.nim");			if (nimSubInt(cmdCount, ((NI32)1), &TM__MZPGKsURfItHSi3RvnOT8Q_2)) { raiseOverflow(); goto LA8_;
			};
			if (TM__MZPGKsURfItHSi3RvnOT8Q_2 < (-2147483647 -1) || TM__MZPGKsURfItHSi3RvnOT8Q_2 > 2147483647){ raiseOverflow(); goto LA8_;
			}
			if (!((NI32)(TM__MZPGKsURfItHSi3RvnOT8Q_2) < ((NI32)0))) goto LA12_;
			nimlf_(8, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/indexerrors.nim");			colontmpD_ = TM__MZPGKsURfItHSi3RvnOT8Q_4;
			blitTmp_1 = colontmpD_;
			nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");			eqwasMoved___flfgrz_u2687((&colontmpD_));
			(*T9_).Sup.Sup.message = blitTmp_1;
		}
		goto LA10_;
LA12_: ;
		{
			NimStringV2 colontmpD__3;
			NimStringV2 colontmpD__4;
			NimStringV2 T15_;
			NI TM__MZPGKsURfItHSi3RvnOT8Q_10;
			NimStringV2 blitTmp_2;
			colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
			colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
			nimlf_(9, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/indexerrors.nim");			T15_.len = 0; T15_.p = NIM_NIL;
			colontmpD__3 = dollar___flfgrzZqbyynef_u14(i_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			nimlf_(272, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/cmdline.nim");			if (nimSubInt(cmdCount, ((NI32)1), &TM__MZPGKsURfItHSi3RvnOT8Q_10)) { raiseOverflow(); goto LA8_;
			};
			if (TM__MZPGKsURfItHSi3RvnOT8Q_10 < (-2147483647 -1) || TM__MZPGKsURfItHSi3RvnOT8Q_10 > 2147483647){ raiseOverflow(); goto LA8_;
			}
			nimlf_(9, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/indexerrors.nim");			colontmpD__4 = dollar___flfgrzZqbyynef_u29((NI32)(TM__MZPGKsURfItHSi3RvnOT8Q_10));
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			T15_ = rawNewString(colontmpD__3.len + colontmpD__4.len + 19);
appendString((&T15_), TM__MZPGKsURfItHSi3RvnOT8Q_6);
appendString((&T15_), colontmpD__3);
appendString((&T15_), TM__MZPGKsURfItHSi3RvnOT8Q_9);
appendString((&T15_), colontmpD__4);
			colontmpD__2 = T15_;
			nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");			if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
			nimlf_(9, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/indexerrors.nim");			blitTmp_2 = colontmpD__2;
			nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");			eqwasMoved___flfgrz_u2687((&colontmpD__2));
			(*T9_).Sup.Sup.message = blitTmp_2;
		}
LA10_: ;
		(*T9_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimlf_(272, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/cmdline.nim");		raiseExceptionEx((Exception*)T9_, "IndexDefect", "paramStr", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/cmdline.nim", 272);
goto LA8_;
		{
			LA8_:;
		}
		{
			nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, paramCount__fgqZpzqyvar_u61)(void) {
	NI result;
	NI TM__MZPGKsURfItHSi3RvnOT8Q_11;
	nimfr_("paramCount", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/cmdline.nim");
{	nimlf_(276, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/cmdline.nim");	if (nimSubInt(cmdCount, ((NI32)1), &TM__MZPGKsURfItHSi3RvnOT8Q_11)) { raiseOverflow(); goto BeforeRet_;
	};
	if (TM__MZPGKsURfItHSi3RvnOT8Q_11 < (-2147483647 -1) || TM__MZPGKsURfItHSi3RvnOT8Q_11 > 2147483647){ raiseOverflow(); goto BeforeRet_;
	}
	result = ((NI) ((NI32)(TM__MZPGKsURfItHSi3RvnOT8Q_11)));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, eqdestroy___flfgrz_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, commandLineParams__fgqZpzqyvar_u63)(void) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
	nimfr_("commandLineParams", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/cmdline.nim");
{nimErr_ = nimErrorFlag();
	nimln_(305);	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");		nimlf_(306, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/cmdline.nim");		colontmp_ = paramCount__fgqZpzqyvar_u61();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(96, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");		res_1 = ((NI)1);
		{
			nimln_(97);			while (1) {
				NimStringV2 T4_;
				NI TM__MZPGKsURfItHSi3RvnOT8Q_12;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(306, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/cmdline.nim");				i_1 = ((NI) (res_1));
				nimln_(307);				T4_.len = 0; T4_.p = NIM_NIL;
				T4_ = paramStr__fgqZpzqyvar_u55(i_1);
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___flfgrz_u281(T4_); goto BeforeRet_;}
				add__fgqZrahzhgvyf_u70((&result), T4_);
				nimlf_(102, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__MZPGKsURfItHSi3RvnOT8Q_12)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__MZPGKsURfItHSi3RvnOT8Q_12);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
