import ../../autogenerated/generated_nftnl
import ../../../linux/autogenerated/generated_linux # enum_nft_cmp_ops
import ../../attrs/exprAttrsCoersion
import ../../raii/expresions

## Simple sugar around derived getters/setters

proc sreg*(e: CmpExpr): uint32 =
  getCmpSreg(e)

proc `sreg=`*(e: CmpExpr, v: uint32) =
  setCmpSreg(e, v)

proc op*(e: CmpExpr): enum_nft_cmp_ops =
  enum_nft_cmp_ops(getCmpOp(e))

proc `op=`*(e: CmpExpr, v: enum_nft_cmp_ops) =
  setCmpOp(e, v.uint32)

proc data*(e: CmpExpr): seq[uint8] =
  getCmpData(e)

proc `data=`*(e: CmpExpr, v: seq[uint8]) =
  setCmpData(e, v)
