import ../../autogenerated/generated_nftnl
import ../../../linux/autogenerated/generated_linux # for enum_nft_cmp_ops
import ../../attrs/exprAttrsCoersion
import ../../expr/exprConcept

# u32 fields
proc sreg*(e: ExprConcept): uint32 =
  e.getAttrCmp(NFTNL_EXPR_CMP_SREG.int)

proc `sreg=`*(e: ExprConcept, v: uint32) =
  e.setAttrCmp(NFTNL_EXPR_CMP_SREG.int, v)

# comparison operator — now properly typed!
proc op*(e: ExprConcept): enum_nft_cmp_ops =
  enum_nft_cmp_ops(e.getAttrCmp(NFTNL_EXPR_CMP_OP.int))

proc `op=`*(e: ExprConcept, v: enum_nft_cmp_ops) =
  e.setAttrCmp(NFTNL_EXPR_CMP_OP.int, v.uint32)

# blob (seq[uint8]) field
proc data*(e: ExprConcept): seq[uint8] =
  e.getAttrCmp(NFTNL_EXPR_CMP_DATA.int)

proc `data=`*(e: ExprConcept, v: seq[uint8]) =
  e.setAttrCmp(NFTNL_EXPR_CMP_DATA.int, v)
