/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/integration_test_snprintf.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@fcher@fgvzrf.nim.c.o /home/becker/projects/libnet/nimcache/tests/integration_test_snprintf.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@fcher@fgvzrf.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_TimezonecolonObjectType___4kqQgt3u59aCyxwPkR4NyHA tyObject_TimezonecolonObjectType___4kqQgt3u59aCyxwPkR4NyHA;
typedef struct tyObject_Duration__GaviyXSk1feY9caubDtFrJQ tyObject_Duration__GaviyXSk1feY9caubDtFrJQ;
struct tyObject_Duration__GaviyXSk1feY9caubDtFrJQ {
	NI64 seconds;
	NI nanosecond;
};
typedef NU8 tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ;
typedef NI64 tyArray__2Jc8K5izMpqZDraGtZeX7A[8];
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ, ntAddDuration)(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ a_p0, tyObject_Duration__GaviyXSk1feY9caubDtFrJQ b_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__flfgrzZzrzbel_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ, normalize__cherZgvzrf_u567)(NI64 seconds_p0, NI64 nanoseconds_p1);
static N_INLINE(NI64, convert__cherZgvzrf_u498)(tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ unitFrom_p0, tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ unitTo_p1, NI64 quantity_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimMulInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2);
static N_INLINE(NF, toBiggestFloat__flfgrz_u1684)(NI64 i_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4709)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NF, abs__flfgrz_u5426)(NF x_p0);
static N_INLINE(NIM_BOOL, nimAddInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2);
static N_INLINE(NI, convert__cherZgvzrf_u582)(tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ unitFrom_p0, tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ unitTo_p1, NI quantity_p2);
static N_INLINE(NIM_BOOL, nimSubInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NI, convert__cherZgvzrf_u833)(tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ unitFrom_p0, tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ unitTo_p1, NI quantity_p2);
N_LIB_PRIVATE NIM_CONST tyArray__2Jc8K5izMpqZDraGtZeX7A unitWeights__cherZgvzrf_u111 = {IL64(1),
IL64(1000),
IL64(1000000),
IL64(1000000000),
IL64(60000000000),
IL64(3600000000000),
IL64(86400000000000),
IL64(604800000000000)}
;
N_LIB_PRIVATE NIM_CONST tyObject_Duration__GaviyXSk1feY9caubDtFrJQ DurationZero__cherZgvzrf_u487 = {IL64(0), ((NI)0)}
;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___4kqQgt3u59aCyxwPkR4NyHA* utcInstance__cherZgvzrf_u2031;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___4kqQgt3u59aCyxwPkR4NyHA* localInstance__cherZgvzrf_u2032;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4491;
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2723;
static N_INLINE(void, nimSetMem__flfgrzZzrzbel_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4491);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__flfgrzZzrzbel_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2) {
	NIM_BOOL result;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a_p0 == (IL64(-9223372036854775807) - IL64(1)));
		if (!(T3_)) goto LA4_;
		T3_ = (b_p1 == IL64(-1));
LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_FALSE;
		(*res_p2) = (NI64)(a_p0 / b_p1);
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2723;
	framePtr__flfgrz_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2723 = (*framePtr__flfgrz_u2723).prev;
}
static N_INLINE(NF, toBiggestFloat__flfgrz_u1684)(NI64 i_p0) {
	NF result;
	nimfr_("toBiggestFloat", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");
	nimlf_(1305, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");	result = ((NF) (i_p0));
	popFrame();
	return result;
}
static N_INLINE(NF, abs__flfgrz_u5426)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2) {
	NIM_BOOL result;
	NI64 r_1;
	NF floatProd_1;
	NF T1_;
	NF T2_;
	NF resAsFloat_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI64) ((NU64)((NU64)(((NU64) (a_p0))) * (NU64)(((NU64) (b_p1))))));
	T1_ = (NF)0;
	T1_ = toBiggestFloat__flfgrz_u1684(a_p0);
	T2_ = (NF)0;
	T2_ = toBiggestFloat__flfgrz_u1684(b_p1);
	floatProd_1 = ((NF)(T1_) * (NF)(T2_));
	resAsFloat_1 = toBiggestFloat__flfgrz_u1684(r_1);
	{
		if (!(resAsFloat_1 == floatProd_1)) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA3_;
LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__flfgrz_u5426(((NF)(resAsFloat_1) - (NF)(floatProd_1)));
			T11_ = (NF)0;
			T11_ = abs__flfgrz_u5426(floatProd_1);
			if (!(((NF)(32.0) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res_p2) = r_1;
		}
		goto LA8_;
LA12_: ;
		{
			result = NIM_TRUE;
		}
LA8_: ;
	}
LA3_: ;
	return result;
}
static N_INLINE(NI64, convert__cherZgvzrf_u498)(tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ unitFrom_p0, tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ unitTo_p1, NI64 quantity_p2) {
	NI64 result;
	NI64 colontmpD_;
	NI64 colontmpD__2;
	nimfr_("convert", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");
{	colontmpD_ = (NI64)0;
	colontmpD__2 = (NI64)0;
	nimlf_(439, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");	nimln_(445);	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_2;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_3;
		if (!(unitFrom_p0 < unitTo_p1)) goto LA3_;
		nimln_(446);		if (unitWeights__cherZgvzrf_u111[(unitFrom_p0)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(unitWeights__cherZgvzrf_u111[(unitTo_p1)- 0], unitWeights__cherZgvzrf_u111[(unitFrom_p0)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_2)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_2) == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(quantity_p2, (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_2), &TM__6NbDwwj5FY059b1gz2AsAZQ_3)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD_ = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_3);
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_4;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_5;
		nimln_(448);		if (unitWeights__cherZgvzrf_u111[(unitTo_p1)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(unitWeights__cherZgvzrf_u111[(unitFrom_p0)- 0], unitWeights__cherZgvzrf_u111[(unitTo_p1)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_4)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimMulInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_4), quantity_p2, &TM__6NbDwwj5FY059b1gz2AsAZQ_5)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD__2 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_5);
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2) {
	NIM_BOOL result;
	NI64 r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI64) ((NU64)((NU64)(((NU64) (a_p0))) + (NU64)(((NU64) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (IL64(0) <= (NI64)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (IL64(0) <= (NI64)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NI, convert__cherZgvzrf_u582)(tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ unitFrom_p0, tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ unitTo_p1, NI quantity_p2) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	nimfr_("convert", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimln_(439);	nimln_(445);	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_7;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_8;
		if (!(unitFrom_p0 < unitTo_p1)) goto LA3_;
		nimln_(446);		if (unitWeights__cherZgvzrf_u111[(unitFrom_p0)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(unitWeights__cherZgvzrf_u111[(unitTo_p1)- 0], unitWeights__cherZgvzrf_u111[(unitFrom_p0)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_7)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_7) == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(((NI64) (quantity_p2)), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_7), &TM__6NbDwwj5FY059b1gz2AsAZQ_8)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD_ = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_8)));
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_9;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_10;
		nimln_(448);		if (unitWeights__cherZgvzrf_u111[(unitTo_p1)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(unitWeights__cherZgvzrf_u111[(unitFrom_p0)- 0], unitWeights__cherZgvzrf_u111[(unitTo_p1)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_9)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimMulInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_9), ((NI64) (quantity_p2)), &TM__6NbDwwj5FY059b1gz2AsAZQ_10)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD__2 = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_10)));
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt64)(NI64 a_p0, NI64 b_p1, NI64* res_p2) {
	NIM_BOOL result;
	NI64 r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI64) ((NU64)((NU64)(((NU64) (a_p0))) - (NU64)(((NU64) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (IL64(0) <= (NI64)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (IL64(0) <= (NI64)(r_1 ^ (NI64)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ, normalize__cherZgvzrf_u567)(NI64 seconds_p0, NI64 nanoseconds_p1) {
	tyObject_Duration__GaviyXSk1feY9caubDtFrJQ result;
	NI64 T1_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_6;
	NI64 nanosecond_1;
	NI T2_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_11;
NIM_BOOL* nimErr_;
	nimfr_("normalize", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");
{nimErr_ = nimErrorFlag();
	nimln_(454);	nimZeroMem((void*)(&result), sizeof(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ));
	nimln_(455);	T1_ = (NI64)0;
	T1_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)0), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), nanoseconds_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64(seconds_p0, T1_, &TM__6NbDwwj5FY059b1gz2AsAZQ_6)) { raiseOverflow(); goto BeforeRet_;
	};
	result.seconds = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_6);
	nimln_(456);	T2_ = (NI)0;
	T2_ = convert__cherZgvzrf_u582(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)0), ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (((NI64) (T2_)) == 0){ raiseDivByZero(); goto BeforeRet_;
	}
	if (nimModInt64(nanoseconds_p1, ((NI64) (T2_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_11)) { raiseOverflow(); goto BeforeRet_;
	};
	nanosecond_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_11);
	nimln_(457);	{
		NI T7_;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_12;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_13;
		if (!(nanosecond_1 < IL64(0))) goto LA5_;
		nimln_(458);		T7_ = (NI)0;
		T7_ = convert__cherZgvzrf_u582(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)0), ((NI)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt64(nanosecond_1, ((NI64) (T7_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_12)) { raiseOverflow(); goto BeforeRet_;
		};
		nanosecond_1 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_12);
		nimln_(459);		if (nimSubInt64(result.seconds, IL64(1), &TM__6NbDwwj5FY059b1gz2AsAZQ_13)) { raiseOverflow(); goto BeforeRet_;
		};
		result.seconds = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_13);
	}
LA5_: ;
	nimln_(460);	if ((((NI) (nanosecond_1))) < ((NI)0) || (((NI) (nanosecond_1))) > ((NI)999999999)){ raiseRangeErrorI(((NI) (nanosecond_1)), ((NI)0), ((NI)999999999)); goto BeforeRet_;
	}
	result.nanosecond = (((NI) (nanosecond_1)));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ, ntAddDuration)(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ a_p0, tyObject_Duration__GaviyXSk1feY9caubDtFrJQ b_p1) {
	tyObject_Duration__GaviyXSk1feY9caubDtFrJQ result;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_14;
	NI TM__6NbDwwj5FY059b1gz2AsAZQ_15;
NIM_BOOL* nimErr_;
	nimfr_("+", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ));
	nimln_(817);	nimln_(821);	nimln_(641);	if (nimAddInt64(a_p0.seconds, b_p1.seconds, &TM__6NbDwwj5FY059b1gz2AsAZQ_14)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt(a_p0.nanosecond, b_p1.nanosecond, &TM__6NbDwwj5FY059b1gz2AsAZQ_15)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(821);	result = normalize__cherZgvzrf_u567((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_14), ((NI64) ((NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_15))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, pluseq___cherZgvzrf_u1141)(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ* d1_p0, tyObject_Duration__GaviyXSk1feY9caubDtFrJQ d2_p1) {
	tyObject_Duration__GaviyXSk1feY9caubDtFrJQ T1_;
NIM_BOOL* nimErr_;
	nimfr_("+=", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");
{nimErr_ = nimErrorFlag();
	nimln_(876);	nimZeroMem((void*)(&T1_), sizeof(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ));
	T1_ = ntAddDuration((*d1_p0), d2_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*d1_p0) = T1_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NI, convert__cherZgvzrf_u833)(tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ unitFrom_p0, tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ unitTo_p1, NI quantity_p2) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	nimfr_("convert", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");
{	result = (NI)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimln_(439);	nimln_(445);	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_19;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_20;
		if (!(unitFrom_p0 < unitTo_p1)) goto LA3_;
		nimln_(446);		if (unitWeights__cherZgvzrf_u111[(unitFrom_p0)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(unitWeights__cherZgvzrf_u111[(unitTo_p1)- 0], unitWeights__cherZgvzrf_u111[(unitFrom_p0)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_19)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_19) == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(((NI64) (quantity_p2)), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_19), &TM__6NbDwwj5FY059b1gz2AsAZQ_20)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_20)) < ((NI)0) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_20)) > ((NI)999999999)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_20), ((NI)0), ((NI)999999999)); goto BeforeRet_;
		}
		colontmpD_ = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_20)));
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_21;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_22;
		nimln_(448);		if (unitWeights__cherZgvzrf_u111[(unitTo_p1)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;
		}
		if (nimDivInt64(unitWeights__cherZgvzrf_u111[(unitFrom_p0)- 0], unitWeights__cherZgvzrf_u111[(unitTo_p1)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_21)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimMulInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_21), ((NI64) (quantity_p2)), &TM__6NbDwwj5FY059b1gz2AsAZQ_22)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_22)) < ((NI)0) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_22)) > ((NI)999999999)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_22), ((NI)0), ((NI)999999999)); goto BeforeRet_;
		}
		colontmpD__2 = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_22)));
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI64, inMilliseconds__cherZgvzrf_u799)(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ dur_p0) {
	NI64 result;
	NI64 colontmpD_;
	NI64 colontmpD__2;
	NIM_BOOL correctionX60gensym29__1;
	NIM_BOOL T1_;
NIM_BOOL* nimErr_;
	nimfr_("inMilliseconds", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");
{nimErr_ = nimErrorFlag();
	result = (NI64)0;
	colontmpD_ = (NI64)0;
	colontmpD__2 = (NI64)0;
	nimln_(742);	nimln_(694);	T1_ = (NIM_BOOL)0;
	T1_ = (dur_p0.seconds < IL64(0));
	if (!(T1_)) goto LA2_;
	T1_ = (((NI)0) < dur_p0.nanosecond);
LA2_: ;
	correctionX60gensym29__1 = T1_;
	nimln_(698);	{
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_16;
		NI64 T7_;
		NI T8_;
		NI TM__6NbDwwj5FY059b1gz2AsAZQ_17;
		NI T9_;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_18;
		if (!correctionX60gensym29__1) goto LA5_;
		nimln_(699);		if (nimAddInt64(dur_p0.seconds, IL64(1), &TM__6NbDwwj5FY059b1gz2AsAZQ_16)) { raiseOverflow(); goto BeforeRet_;
		};
		T7_ = (NI64)0;
		T7_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)2), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_16));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(700);		nimln_(701);		T8_ = (NI)0;
		T8_ = convert__cherZgvzrf_u582(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)0), ((NI)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimSubInt(T8_, dur_p0.nanosecond, &TM__6NbDwwj5FY059b1gz2AsAZQ_17)) { raiseOverflow(); goto BeforeRet_;
		};
		nimln_(700);		T9_ = (NI)0;
		T9_ = convert__cherZgvzrf_u582(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)0), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)2), (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_17));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimSubInt64(T7_, ((NI64) (T9_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_18)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD_ = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_18);
		result = colontmpD_;
	}
	goto LA3_;
LA5_: ;
	{
		NI64 T11_;
		NI T12_;
		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_23;
		nimln_(703);		T11_ = (NI64)0;
		T11_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)2), dur_p0.seconds);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(704);		T12_ = (NI)0;
		T12_ = convert__cherZgvzrf_u833(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)0), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)2), dur_p0.nanosecond);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt64(T11_, ((NI64) (T12_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_23)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD__2 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_23);
		result = colontmpD__2;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ntLtDuration)(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ a_p0, tyObject_Duration__GaviyXSk1feY9caubDtFrJQ b_p1) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T3_;
	nimfr_("<", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");
	nimln_(837);	nimln_(846);	T1_ = (NIM_BOOL)0;
	nimln_(644);	T1_ = (a_p0.seconds < b_p1.seconds);
	if (T1_) goto LA2_;
	nimln_(645);	T3_ = (NIM_BOOL)0;
	T3_ = (a_p0.seconds == b_p1.seconds);
	if (!(T3_)) goto LA4_;
	T3_ = (a_p0.nanosecond < b_p1.nanosecond);
LA4_: ;
	T1_ = T3_;
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI64, inNanoseconds__cherZgvzrf_u882)(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ dur_p0) {
	NI64 result;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_24;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_25;
	nimfr_("inNanoseconds", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");
{	nimln_(756);	nimln_(760);	nimln_(692);	if (nimMulInt64(dur_p0.seconds, IL64(1000000000), &TM__6NbDwwj5FY059b1gz2AsAZQ_24)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_24), ((NI64) (dur_p0.nanosecond)), &TM__6NbDwwj5FY059b1gz2AsAZQ_25)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_25);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ, initDuration__cherZgvzrf_u488)(NI64 nanoseconds_p0, NI64 microseconds_p1, NI64 milliseconds_p2, NI64 seconds_p3, NI64 minutes_p4, NI64 hours_p5, NI64 days_p6, NI64 weeks_p7) {
	tyObject_Duration__GaviyXSk1feY9caubDtFrJQ result;
	NI64 seconds_2;
	NI64 T1_;
	NI64 T2_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_26;
	NI64 T3_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_27;
	NI64 T4_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_28;
	NI64 T5_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_29;
	NI64 T6_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_30;
	NI64 T7_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_31;
	NI64 T8_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_32;
	NI nanoseconds_2;
	NI64 T9_;
	NI64 T10_;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_33;
	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_34;
NIM_BOOL* nimErr_;
	nimfr_("initDuration", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Duration__GaviyXSk1feY9caubDtFrJQ));
	nimln_(673);	nimln_(679);	nimln_(678);	nimln_(677);	nimln_(676);	nimln_(675);	nimln_(674);	nimln_(673);	T1_ = (NI64)0;
	T1_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)7), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), weeks_p7);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(674);	T2_ = (NI64)0;
	T2_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)6), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), days_p6);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64(T1_, T2_, &TM__6NbDwwj5FY059b1gz2AsAZQ_26)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(675);	T3_ = (NI64)0;
	T3_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)4), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), minutes_p4);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_26), T3_, &TM__6NbDwwj5FY059b1gz2AsAZQ_27)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(676);	T4_ = (NI64)0;
	T4_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)5), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), hours_p5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_27), T4_, &TM__6NbDwwj5FY059b1gz2AsAZQ_28)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(677);	T5_ = (NI64)0;
	T5_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), seconds_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_28), T5_, &TM__6NbDwwj5FY059b1gz2AsAZQ_29)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(678);	T6_ = (NI64)0;
	T6_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)2), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), milliseconds_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_29), T6_, &TM__6NbDwwj5FY059b1gz2AsAZQ_30)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(679);	T7_ = (NI64)0;
	T7_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)1), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), microseconds_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_30), T7_, &TM__6NbDwwj5FY059b1gz2AsAZQ_31)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(680);	T8_ = (NI64)0;
	T8_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)0), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)3), nanoseconds_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_31), T8_, &TM__6NbDwwj5FY059b1gz2AsAZQ_32)) { raiseOverflow(); goto BeforeRet_;
	};
	seconds_2 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_32);
	nimln_(681);	nimln_(682);	nimln_(681);	T9_ = (NI64)0;
	T9_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)2), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)0), (NI64)((milliseconds_p2) % (IL64(1000))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(682);	T10_ = (NI64)0;
	T10_ = convert__cherZgvzrf_u498(((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)1), ((tyEnum_TimeUnit__WgjmMPe6KFmr4ijhVH45CQ)0), (NI64)((microseconds_p1) % (IL64(1000000))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt64(T9_, T10_, &TM__6NbDwwj5FY059b1gz2AsAZQ_33)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(683);	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_33), (NI64)((nanoseconds_p0) % (IL64(1000000000))), &TM__6NbDwwj5FY059b1gz2AsAZQ_34)) { raiseOverflow(); goto BeforeRet_;
	};
	nanoseconds_2 = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_34)));
	nimln_(685);	result = normalize__cherZgvzrf_u567(seconds_2, ((NI64) (nanoseconds_2)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
