/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/integration_test_snprintf.nim_4a8a08f09d37b73795649038408b5f33/@z..@ffep@fzrffntrOhvyqre.nim.c.o /home/becker/projects/libnet/nimcache/tests/integration_test_snprintf.nim_4a8a08f09d37b73795649038408b5f33/@z..@ffep@fzrffntrOhvyqre.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA;
typedef struct tyObject_struct_nftnl_rule__5wWhyZMl21akJK8BzSyVLQ tyObject_struct_nftnl_rule__5wWhyZMl21akJK8BzSyVLQ;
typedef struct tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ;
typedef struct tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg;
struct tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA {
	tyObject_struct_nftnl_rule__5wWhyZMl21akJK8BzSyVLQ* raw;
};
struct tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ {
	tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg* raw;
};
struct tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg {
	char dummy;
};
N_LIB_PRIVATE N_NIMCALL(void, addExpr__OOZfepZzrffntr66hvyqre_u47)(tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA r_p0, tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ e_p1);
N_CDECL(void, nftnl_rule_add_expr)(tyObject_struct_nftnl_rule__5wWhyZMl21akJK8BzSyVLQ* r_p0, tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg* expr_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfepZasgayZenvvZrkcerfvbaf_u9)(tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ* x_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4709)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4491;
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2723;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4491);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2723;
	framePtr__flfgrz_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2723 = (*framePtr__flfgrz_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, addExpr__OOZfepZzrffntr66hvyqre_u47)(tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA r_p0, tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ e_p1) {
NIM_BOOL* nimErr_;
	nimfr_("addExpr", "/home/becker/projects/libnet/src/messageBuilder.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(32, "/home/becker/projects/libnet/src/messageBuilder.nim");	nftnl_rule_add_expr(r_p0.raw, e_p1.raw);
	nimln_(33);	e_p1.raw = ((tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg*) NIM_NIL);
	nimlf_(17, "/home/becker/projects/libnet/src/nftnl/raii/expresions.nim");	eqdestroy___OOZfepZasgayZenvvZrkcerfvbaf_u9((&e_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, addExpr__OOZfepZzrffntr66hvyqre_u50)(tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA r_p0, tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ e_p1) {
	tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ blitTmp_1;
NIM_BOOL* nimErr_;
	nimfr_("addExpr", "/home/becker/projects/libnet/src/messageBuilder.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(36, "/home/becker/projects/libnet/src/messageBuilder.nim");	blitTmp_1 = e_p1;
	addExpr__OOZfepZzrffntr66hvyqre_u47(r_p0, blitTmp_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
