{.passC: staticExec("pkg-config --cflags libnftnl").}
{.passL: staticExec("pkg-config --libs   libnftnl").}

from os import parentDir, `/`
import futhark

when defined(useFuthark):
  const glibcInclude = staticExec("nix eval --raw nixpkgs#glibc.dev.outPath") & "/include"
  const nftnlInclude = staticExec("pkg-config --variable=includedir libnftnl")

  importc:
    outputPath currentSourcePath.parentDir / "autogenerated" / "generated_nftnl.nim"

    # libc headers required by nftnl
    path glibcInclude

    # nftnl headers
    path nftnlInclude

    "libnftnl/table.h"
    "libnftnl/chain.h"
    "libnftnl/rule.h"
    "libnftnl/set.h"
    "libnftnl/expr.h"
    "libnftnl/object.h"
