import ../autogenerated/generated_nftnl

# --- cmp ---------------------------------------------------------------------

const
  CmpBlobAttrs* = {int(NFTNL_EXPR_CMP_DATA)}
  CmpUint32Attrs* = {int(NFTNL_EXPR_CMP_SREG), int(NFTNL_EXPR_CMP_OP)}

# --- type mapping at CT ------------------------------------------------------

template expectedType*(attr: static int, exprKind: static[string]): untyped =
  when exprKind == "cmp":
    when attr in CmpBlobAttrs:
      seq[uint8]
    elif attr in CmpUint32Attrs:
      uint32
    else:
      {.error: "Unsupported cmp expression attribute: " & $attr.}
  else:
    {.error: "Unsupported expr kind for contract: " & exprKind.}
