import macros
import ../autogenerated/generated_nftnl

const
  # string attributes
  StringAttrs* = {NFTNL_RULE_TABLE, NFTNL_RULE_CHAIN, NFTNL_RULE_USERDATA}

  # uint32 attributes
  Uint32Attrs* = {NFTNL_RULE_FAMILY, NFTNL_RULE_COMPAT_PROTO, NFTNL_RULE_COMPAT_FLAGS}

  # uint64 attributes
  Uint64Attrs* = {NFTNL_RULE_HANDLE}

template expectedType*(attr: static enum_nftnl_rule_attr): untyped =
  when attr in StringAttrs:
    string
  elif attr in Uint32Attrs:
    uint32
  elif attr in Uint64Attrs:
    uint64
  else:
    {.error: "Unsupported rule attribute: " & $attr.}
