# ---------------------------------------------------------------------------
# Expression concept
# ---------------------------------------------------------------------------
# This concept defines the minimal compile-time "shape" that a type must have
# to be treated as an nftnl Expression in our wrapper layer.
#
# Any object that has:
#   - a field named `raw`
#   - whose type is `ptr struct_nftnl_expr`
# will automatically satisfy this concept.
#
# ---------------------------------------------------------------------------

import ../autogenerated/generated_nftnl

type ExprConcept* =
  concept x
      x.raw is ptr struct_nftnl_expr
