/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/core_test_rule.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@fcher@fhavpbqr.nim.c.o /home/becker/projects/libnet/nimcache/tests/core_test_rule.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@fcher@fhavpbqr.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NI32 tyArray__29aKyJI29cO9aTzE8mSc8FIUA[138];
typedef NI32 tyArray__9bhwMxYsABdMIevX9amWmgag[1248];
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(NI32, nuctoUpper)(NI32 c_p0);
N_LIB_PRIVATE N_NIMCALL(NI, binarySearch__cherZhavpbqr_u1119)(NI32 c_p0, NI32* tab_p1, NI tab_p1Len_0, NI len_p2, NI stride_p3);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NF, toFloat__flfgrz_u1681)(NI i_p0);
static N_INLINE(NF, abs__flfgrz_u5426)(NF x_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NIM_BOOL, lteqpercent___flfgrz_u1082)(NI32 x_p0, NI32 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__flfgrz_u2441)(NimStringV2* s_p0);
N_LIB_PRIVATE NIM_CONST tyArray__29aKyJI29cO9aTzE8mSc8FIUA toUpperRanges__cherZhavpbqr_u1112 = {((NI32)97),
((NI32)122),
((NI32)468),
((NI32)224),
((NI32)246),
((NI32)468),
((NI32)248),
((NI32)254),
((NI32)468),
((NI32)575),
((NI32)576),
((NI32)11315),
((NI32)598),
((NI32)599),
((NI32)295),
((NI32)650),
((NI32)651),
((NI32)283),
((NI32)891),
((NI32)893),
((NI32)630),
((NI32)941),
((NI32)943),
((NI32)463),
((NI32)945),
((NI32)961),
((NI32)468),
((NI32)963),
((NI32)971),
((NI32)468),
((NI32)973),
((NI32)974),
((NI32)437),
((NI32)1072),
((NI32)1103),
((NI32)468),
((NI32)1104),
((NI32)1119),
((NI32)420),
((NI32)1377),
((NI32)1414),
((NI32)452),
((NI32)4304),
((NI32)4346),
((NI32)3508),
((NI32)4349),
((NI32)4351),
((NI32)3508),
((NI32)5112),
((NI32)5117),
((NI32)492),
((NI32)7299),
((NI32)7300),
((NI32)-5742),
((NI32)7936),
((NI32)7943),
((NI32)508),
((NI32)7952),
((NI32)7957),
((NI32)508),
((NI32)7968),
((NI32)7975),
((NI32)508),
((NI32)7984),
((NI32)7991),
((NI32)508),
((NI32)8000),
((NI32)8005),
((NI32)508),
((NI32)8032),
((NI32)8039),
((NI32)508),
((NI32)8048),
((NI32)8049),
((NI32)574),
((NI32)8050),
((NI32)8053),
((NI32)586),
((NI32)8054),
((NI32)8055),
((NI32)600),
((NI32)8056),
((NI32)8057),
((NI32)628),
((NI32)8058),
((NI32)8059),
((NI32)612),
((NI32)8060),
((NI32)8061),
((NI32)626),
((NI32)8064),
((NI32)8071),
((NI32)508),
((NI32)8080),
((NI32)8087),
((NI32)508),
((NI32)8096),
((NI32)8103),
((NI32)508),
((NI32)8112),
((NI32)8113),
((NI32)508),
((NI32)8144),
((NI32)8145),
((NI32)508),
((NI32)8160),
((NI32)8161),
((NI32)508),
((NI32)11312),
((NI32)11358),
((NI32)452),
((NI32)11520),
((NI32)11557),
((NI32)-6764),
((NI32)43888),
((NI32)43967),
((NI32)-38364),
((NI32)65345),
((NI32)65370),
((NI32)468),
((NI32)66600),
((NI32)66639),
((NI32)460),
((NI32)66776),
((NI32)66811),
((NI32)460),
((NI32)68800),
((NI32)68850),
((NI32)436),
((NI32)71872),
((NI32)71903),
((NI32)468),
((NI32)93792),
((NI32)93823),
((NI32)468),
((NI32)125218),
((NI32)125251),
((NI32)466)}
;
N_LIB_PRIVATE NIM_CONST tyArray__9bhwMxYsABdMIevX9amWmgag toUpperSinglets__cherZhavpbqr_u1113 = {((NI32)181),
((NI32)1243),
((NI32)255),
((NI32)621),
((NI32)257),
((NI32)499),
((NI32)259),
((NI32)499),
((NI32)261),
((NI32)499),
((NI32)263),
((NI32)499),
((NI32)265),
((NI32)499),
((NI32)267),
((NI32)499),
((NI32)269),
((NI32)499),
((NI32)271),
((NI32)499),
((NI32)273),
((NI32)499),
((NI32)275),
((NI32)499),
((NI32)277),
((NI32)499),
((NI32)279),
((NI32)499),
((NI32)281),
((NI32)499),
((NI32)283),
((NI32)499),
((NI32)285),
((NI32)499),
((NI32)287),
((NI32)499),
((NI32)289),
((NI32)499),
((NI32)291),
((NI32)499),
((NI32)293),
((NI32)499),
((NI32)295),
((NI32)499),
((NI32)297),
((NI32)499),
((NI32)299),
((NI32)499),
((NI32)301),
((NI32)499),
((NI32)303),
((NI32)499),
((NI32)305),
((NI32)268),
((NI32)307),
((NI32)499),
((NI32)309),
((NI32)499),
((NI32)311),
((NI32)499),
((NI32)314),
((NI32)499),
((NI32)316),
((NI32)499),
((NI32)318),
((NI32)499),
((NI32)320),
((NI32)499),
((NI32)322),
((NI32)499),
((NI32)324),
((NI32)499),
((NI32)326),
((NI32)499),
((NI32)328),
((NI32)499),
((NI32)331),
((NI32)499),
((NI32)333),
((NI32)499),
((NI32)335),
((NI32)499),
((NI32)337),
((NI32)499),
((NI32)339),
((NI32)499),
((NI32)341),
((NI32)499),
((NI32)343),
((NI32)499),
((NI32)345),
((NI32)499),
((NI32)347),
((NI32)499),
((NI32)349),
((NI32)499),
((NI32)351),
((NI32)499),
((NI32)353),
((NI32)499),
((NI32)355),
((NI32)499),
((NI32)357),
((NI32)499),
((NI32)359),
((NI32)499),
((NI32)361),
((NI32)499),
((NI32)363),
((NI32)499),
((NI32)365),
((NI32)499),
((NI32)367),
((NI32)499),
((NI32)369),
((NI32)499),
((NI32)371),
((NI32)499),
((NI32)373),
((NI32)499),
((NI32)375),
((NI32)499),
((NI32)378),
((NI32)499),
((NI32)380),
((NI32)499),
((NI32)382),
((NI32)499),
((NI32)383),
((NI32)200),
((NI32)384),
((NI32)695),
((NI32)387),
((NI32)499),
((NI32)389),
((NI32)499),
((NI32)392),
((NI32)499),
((NI32)396),
((NI32)499),
((NI32)402),
((NI32)499),
((NI32)405),
((NI32)597),
((NI32)409),
((NI32)499),
((NI32)410),
((NI32)663),
((NI32)414),
((NI32)630),
((NI32)417),
((NI32)499),
((NI32)419),
((NI32)499),
((NI32)421),
((NI32)499),
((NI32)424),
((NI32)499),
((NI32)429),
((NI32)499),
((NI32)432),
((NI32)499),
((NI32)436),
((NI32)499),
((NI32)438),
((NI32)499),
((NI32)441),
((NI32)499),
((NI32)445),
((NI32)499),
((NI32)447),
((NI32)556),
((NI32)453),
((NI32)499),
((NI32)454),
((NI32)498),
((NI32)456),
((NI32)499),
((NI32)457),
((NI32)498),
((NI32)459),
((NI32)499),
((NI32)460),
((NI32)498),
((NI32)462),
((NI32)499),
((NI32)464),
((NI32)499),
((NI32)466),
((NI32)499),
((NI32)468),
((NI32)499),
((NI32)470),
((NI32)499),
((NI32)472),
((NI32)499),
((NI32)474),
((NI32)499),
((NI32)476),
((NI32)499),
((NI32)477),
((NI32)421),
((NI32)479),
((NI32)499),
((NI32)481),
((NI32)499),
((NI32)483),
((NI32)499),
((NI32)485),
((NI32)499),
((NI32)487),
((NI32)499),
((NI32)489),
((NI32)499),
((NI32)491),
((NI32)499),
((NI32)493),
((NI32)499),
((NI32)495),
((NI32)499),
((NI32)498),
((NI32)499),
((NI32)499),
((NI32)498),
((NI32)501),
((NI32)499),
((NI32)505),
((NI32)499),
((NI32)507),
((NI32)499),
((NI32)509),
((NI32)499),
((NI32)511),
((NI32)499),
((NI32)513),
((NI32)499),
((NI32)515),
((NI32)499),
((NI32)517),
((NI32)499),
((NI32)519),
((NI32)499),
((NI32)521),
((NI32)499),
((NI32)523),
((NI32)499),
((NI32)525),
((NI32)499),
((NI32)527),
((NI32)499),
((NI32)529),
((NI32)499),
((NI32)531),
((NI32)499),
((NI32)533),
((NI32)499),
((NI32)535),
((NI32)499),
((NI32)537),
((NI32)499),
((NI32)539),
((NI32)499),
((NI32)541),
((NI32)499),
((NI32)543),
((NI32)499),
((NI32)547),
((NI32)499),
((NI32)549),
((NI32)499),
((NI32)551),
((NI32)499),
((NI32)553),
((NI32)499),
((NI32)555),
((NI32)499),
((NI32)557),
((NI32)499),
((NI32)559),
((NI32)499),
((NI32)561),
((NI32)499),
((NI32)563),
((NI32)499),
((NI32)572),
((NI32)499),
((NI32)578),
((NI32)499),
((NI32)583),
((NI32)499),
((NI32)585),
((NI32)499),
((NI32)587),
((NI32)499),
((NI32)589),
((NI32)499),
((NI32)591),
((NI32)499),
((NI32)592),
((NI32)11283),
((NI32)593),
((NI32)11280),
((NI32)594),
((NI32)11282),
((NI32)595),
((NI32)290),
((NI32)596),
((NI32)294),
((NI32)601),
((NI32)298),
((NI32)603),
((NI32)297),
((NI32)604),
((NI32)42819),
((NI32)608),
((NI32)295),
((NI32)609),
((NI32)42815),
((NI32)611),
((NI32)293),
((NI32)613),
((NI32)42780),
((NI32)614),
((NI32)42808),
((NI32)616),
((NI32)291),
((NI32)617),
((NI32)289),
((NI32)618),
((NI32)42808),
((NI32)619),
((NI32)11243),
((NI32)620),
((NI32)42805),
((NI32)623),
((NI32)289),
((NI32)625),
((NI32)11249),
((NI32)626),
((NI32)287),
((NI32)629),
((NI32)286),
((NI32)637),
((NI32)11227),
((NI32)640),
((NI32)282),
((NI32)642),
((NI32)42807),
((NI32)643),
((NI32)282),
((NI32)647),
((NI32)42782),
((NI32)648),
((NI32)282),
((NI32)649),
((NI32)431),
((NI32)652),
((NI32)429),
((NI32)658),
((NI32)281),
((NI32)669),
((NI32)42761),
((NI32)670),
((NI32)42758),
((NI32)881),
((NI32)499),
((NI32)883),
((NI32)499),
((NI32)887),
((NI32)499),
((NI32)940),
((NI32)462),
((NI32)962),
((NI32)469),
((NI32)972),
((NI32)436),
((NI32)976),
((NI32)438),
((NI32)977),
((NI32)443),
((NI32)981),
((NI32)453),
((NI32)982),
((NI32)446),
((NI32)983),
((NI32)492),
((NI32)985),
((NI32)499),
((NI32)987),
((NI32)499),
((NI32)989),
((NI32)499),
((NI32)991),
((NI32)499),
((NI32)993),
((NI32)499),
((NI32)995),
((NI32)499),
((NI32)997),
((NI32)499),
((NI32)999),
((NI32)499),
((NI32)1001),
((NI32)499),
((NI32)1003),
((NI32)499),
((NI32)1005),
((NI32)499),
((NI32)1007),
((NI32)499),
((NI32)1008),
((NI32)414),
((NI32)1009),
((NI32)420),
((NI32)1010),
((NI32)507),
((NI32)1011),
((NI32)384),
((NI32)1013),
((NI32)404),
((NI32)1016),
((NI32)499),
((NI32)1019),
((NI32)499),
((NI32)1121),
((NI32)499),
((NI32)1123),
((NI32)499),
((NI32)1125),
((NI32)499),
((NI32)1127),
((NI32)499),
((NI32)1129),
((NI32)499),
((NI32)1131),
((NI32)499),
((NI32)1133),
((NI32)499),
((NI32)1135),
((NI32)499),
((NI32)1137),
((NI32)499),
((NI32)1139),
((NI32)499),
((NI32)1141),
((NI32)499),
((NI32)1143),
((NI32)499),
((NI32)1145),
((NI32)499),
((NI32)1147),
((NI32)499),
((NI32)1149),
((NI32)499),
((NI32)1151),
((NI32)499),
((NI32)1153),
((NI32)499),
((NI32)1163),
((NI32)499),
((NI32)1165),
((NI32)499),
((NI32)1167),
((NI32)499),
((NI32)1169),
((NI32)499),
((NI32)1171),
((NI32)499),
((NI32)1173),
((NI32)499),
((NI32)1175),
((NI32)499),
((NI32)1177),
((NI32)499),
((NI32)1179),
((NI32)499),
((NI32)1181),
((NI32)499),
((NI32)1183),
((NI32)499),
((NI32)1185),
((NI32)499),
((NI32)1187),
((NI32)499),
((NI32)1189),
((NI32)499),
((NI32)1191),
((NI32)499),
((NI32)1193),
((NI32)499),
((NI32)1195),
((NI32)499),
((NI32)1197),
((NI32)499),
((NI32)1199),
((NI32)499),
((NI32)1201),
((NI32)499),
((NI32)1203),
((NI32)499),
((NI32)1205),
((NI32)499),
((NI32)1207),
((NI32)499),
((NI32)1209),
((NI32)499),
((NI32)1211),
((NI32)499),
((NI32)1213),
((NI32)499),
((NI32)1215),
((NI32)499),
((NI32)1218),
((NI32)499),
((NI32)1220),
((NI32)499),
((NI32)1222),
((NI32)499),
((NI32)1224),
((NI32)499),
((NI32)1226),
((NI32)499),
((NI32)1228),
((NI32)499),
((NI32)1230),
((NI32)499),
((NI32)1231),
((NI32)485),
((NI32)1233),
((NI32)499),
((NI32)1235),
((NI32)499),
((NI32)1237),
((NI32)499),
((NI32)1239),
((NI32)499),
((NI32)1241),
((NI32)499),
((NI32)1243),
((NI32)499),
((NI32)1245),
((NI32)499),
((NI32)1247),
((NI32)499),
((NI32)1249),
((NI32)499),
((NI32)1251),
((NI32)499),
((NI32)1253),
((NI32)499),
((NI32)1255),
((NI32)499),
((NI32)1257),
((NI32)499),
((NI32)1259),
((NI32)499),
((NI32)1261),
((NI32)499),
((NI32)1263),
((NI32)499),
((NI32)1265),
((NI32)499),
((NI32)1267),
((NI32)499),
((NI32)1269),
((NI32)499),
((NI32)1271),
((NI32)499),
((NI32)1273),
((NI32)499),
((NI32)1275),
((NI32)499),
((NI32)1277),
((NI32)499),
((NI32)1279),
((NI32)499),
((NI32)1281),
((NI32)499),
((NI32)1283),
((NI32)499),
((NI32)1285),
((NI32)499),
((NI32)1287),
((NI32)499),
((NI32)1289),
((NI32)499),
((NI32)1291),
((NI32)499),
((NI32)1293),
((NI32)499),
((NI32)1295),
((NI32)499),
((NI32)1297),
((NI32)499),
((NI32)1299),
((NI32)499),
((NI32)1301),
((NI32)499),
((NI32)1303),
((NI32)499),
((NI32)1305),
((NI32)499),
((NI32)1307),
((NI32)499),
((NI32)1309),
((NI32)499),
((NI32)1311),
((NI32)499),
((NI32)1313),
((NI32)499),
((NI32)1315),
((NI32)499),
((NI32)1317),
((NI32)499),
((NI32)1319),
((NI32)499),
((NI32)1321),
((NI32)499),
((NI32)1323),
((NI32)499),
((NI32)1325),
((NI32)499),
((NI32)1327),
((NI32)499),
((NI32)7296),
((NI32)-5754),
((NI32)7297),
((NI32)-5753),
((NI32)7298),
((NI32)-5744),
((NI32)7301),
((NI32)-5743),
((NI32)7302),
((NI32)-5736),
((NI32)7303),
((NI32)-5681),
((NI32)7304),
((NI32)35766),
((NI32)7545),
((NI32)35832),
((NI32)7549),
((NI32)4314),
((NI32)7566),
((NI32)35884),
((NI32)7681),
((NI32)499),
((NI32)7683),
((NI32)499),
((NI32)7685),
((NI32)499),
((NI32)7687),
((NI32)499),
((NI32)7689),
((NI32)499),
((NI32)7691),
((NI32)499),
((NI32)7693),
((NI32)499),
((NI32)7695),
((NI32)499),
((NI32)7697),
((NI32)499),
((NI32)7699),
((NI32)499),
((NI32)7701),
((NI32)499),
((NI32)7703),
((NI32)499),
((NI32)7705),
((NI32)499),
((NI32)7707),
((NI32)499),
((NI32)7709),
((NI32)499),
((NI32)7711),
((NI32)499),
((NI32)7713),
((NI32)499),
((NI32)7715),
((NI32)499),
((NI32)7717),
((NI32)499),
((NI32)7719),
((NI32)499),
((NI32)7721),
((NI32)499),
((NI32)7723),
((NI32)499),
((NI32)7725),
((NI32)499),
((NI32)7727),
((NI32)499),
((NI32)7729),
((NI32)499),
((NI32)7731),
((NI32)499),
((NI32)7733),
((NI32)499),
((NI32)7735),
((NI32)499),
((NI32)7737),
((NI32)499),
((NI32)7739),
((NI32)499),
((NI32)7741),
((NI32)499),
((NI32)7743),
((NI32)499),
((NI32)7745),
((NI32)499),
((NI32)7747),
((NI32)499),
((NI32)7749),
((NI32)499),
((NI32)7751),
((NI32)499),
((NI32)7753),
((NI32)499),
((NI32)7755),
((NI32)499),
((NI32)7757),
((NI32)499),
((NI32)7759),
((NI32)499),
((NI32)7761),
((NI32)499),
((NI32)7763),
((NI32)499),
((NI32)7765),
((NI32)499),
((NI32)7767),
((NI32)499),
((NI32)7769),
((NI32)499),
((NI32)7771),
((NI32)499),
((NI32)7773),
((NI32)499),
((NI32)7775),
((NI32)499),
((NI32)7777),
((NI32)499),
((NI32)7779),
((NI32)499),
((NI32)7781),
((NI32)499),
((NI32)7783),
((NI32)499),
((NI32)7785),
((NI32)499),
((NI32)7787),
((NI32)499),
((NI32)7789),
((NI32)499),
((NI32)7791),
((NI32)499),
((NI32)7793),
((NI32)499),
((NI32)7795),
((NI32)499),
((NI32)7797),
((NI32)499),
((NI32)7799),
((NI32)499),
((NI32)7801),
((NI32)499),
((NI32)7803),
((NI32)499),
((NI32)7805),
((NI32)499),
((NI32)7807),
((NI32)499),
((NI32)7809),
((NI32)499),
((NI32)7811),
((NI32)499),
((NI32)7813),
((NI32)499),
((NI32)7815),
((NI32)499),
((NI32)7817),
((NI32)499),
((NI32)7819),
((NI32)499),
((NI32)7821),
((NI32)499),
((NI32)7823),
((NI32)499),
((NI32)7825),
((NI32)499),
((NI32)7827),
((NI32)499),
((NI32)7829),
((NI32)499),
((NI32)7835),
((NI32)441),
((NI32)7841),
((NI32)499),
((NI32)7843),
((NI32)499),
((NI32)7845),
((NI32)499),
((NI32)7847),
((NI32)499),
((NI32)7849),
((NI32)499),
((NI32)7851),
((NI32)499),
((NI32)7853),
((NI32)499),
((NI32)7855),
((NI32)499),
((NI32)7857),
((NI32)499),
((NI32)7859),
((NI32)499),
((NI32)7861),
((NI32)499),
((NI32)7863),
((NI32)499),
((NI32)7865),
((NI32)499),
((NI32)7867),
((NI32)499),
((NI32)7869),
((NI32)499),
((NI32)7871),
((NI32)499),
((NI32)7873),
((NI32)499),
((NI32)7875),
((NI32)499),
((NI32)7877),
((NI32)499),
((NI32)7879),
((NI32)499),
((NI32)7881),
((NI32)499),
((NI32)7883),
((NI32)499),
((NI32)7885),
((NI32)499),
((NI32)7887),
((NI32)499),
((NI32)7889),
((NI32)499),
((NI32)7891),
((NI32)499),
((NI32)7893),
((NI32)499),
((NI32)7895),
((NI32)499),
((NI32)7897),
((NI32)499),
((NI32)7899),
((NI32)499),
((NI32)7901),
((NI32)499),
((NI32)7903),
((NI32)499),
((NI32)7905),
((NI32)499),
((NI32)7907),
((NI32)499),
((NI32)7909),
((NI32)499),
((NI32)7911),
((NI32)499),
((NI32)7913),
((NI32)499),
((NI32)7915),
((NI32)499),
((NI32)7917),
((NI32)499),
((NI32)7919),
((NI32)499),
((NI32)7921),
((NI32)499),
((NI32)7923),
((NI32)499),
((NI32)7925),
((NI32)499),
((NI32)7927),
((NI32)499),
((NI32)7929),
((NI32)499),
((NI32)7931),
((NI32)499),
((NI32)7933),
((NI32)499),
((NI32)7935),
((NI32)499),
((NI32)8017),
((NI32)508),
((NI32)8019),
((NI32)508),
((NI32)8021),
((NI32)508),
((NI32)8023),
((NI32)508),
((NI32)8115),
((NI32)509),
((NI32)8126),
((NI32)-6705),
((NI32)8131),
((NI32)509),
((NI32)8165),
((NI32)507),
((NI32)8179),
((NI32)509),
((NI32)8526),
((NI32)472),
((NI32)8580),
((NI32)499),
((NI32)11361),
((NI32)499),
((NI32)11365),
((NI32)-10295),
((NI32)11366),
((NI32)-10292),
((NI32)11368),
((NI32)499),
((NI32)11370),
((NI32)499),
((NI32)11372),
((NI32)499),
((NI32)11379),
((NI32)499),
((NI32)11382),
((NI32)499),
((NI32)11393),
((NI32)499),
((NI32)11395),
((NI32)499),
((NI32)11397),
((NI32)499),
((NI32)11399),
((NI32)499),
((NI32)11401),
((NI32)499),
((NI32)11403),
((NI32)499),
((NI32)11405),
((NI32)499),
((NI32)11407),
((NI32)499),
((NI32)11409),
((NI32)499),
((NI32)11411),
((NI32)499),
((NI32)11413),
((NI32)499),
((NI32)11415),
((NI32)499),
((NI32)11417),
((NI32)499),
((NI32)11419),
((NI32)499),
((NI32)11421),
((NI32)499),
((NI32)11423),
((NI32)499),
((NI32)11425),
((NI32)499),
((NI32)11427),
((NI32)499),
((NI32)11429),
((NI32)499),
((NI32)11431),
((NI32)499),
((NI32)11433),
((NI32)499),
((NI32)11435),
((NI32)499),
((NI32)11437),
((NI32)499),
((NI32)11439),
((NI32)499),
((NI32)11441),
((NI32)499),
((NI32)11443),
((NI32)499),
((NI32)11445),
((NI32)499),
((NI32)11447),
((NI32)499),
((NI32)11449),
((NI32)499),
((NI32)11451),
((NI32)499),
((NI32)11453),
((NI32)499),
((NI32)11455),
((NI32)499),
((NI32)11457),
((NI32)499),
((NI32)11459),
((NI32)499),
((NI32)11461),
((NI32)499),
((NI32)11463),
((NI32)499),
((NI32)11465),
((NI32)499),
((NI32)11467),
((NI32)499),
((NI32)11469),
((NI32)499),
((NI32)11471),
((NI32)499),
((NI32)11473),
((NI32)499),
((NI32)11475),
((NI32)499),
((NI32)11477),
((NI32)499),
((NI32)11479),
((NI32)499),
((NI32)11481),
((NI32)499),
((NI32)11483),
((NI32)499),
((NI32)11485),
((NI32)499),
((NI32)11487),
((NI32)499),
((NI32)11489),
((NI32)499),
((NI32)11491),
((NI32)499),
((NI32)11500),
((NI32)499),
((NI32)11502),
((NI32)499),
((NI32)11507),
((NI32)499),
((NI32)11559),
((NI32)-6764),
((NI32)11565),
((NI32)-6764),
((NI32)42561),
((NI32)499),
((NI32)42563),
((NI32)499),
((NI32)42565),
((NI32)499),
((NI32)42567),
((NI32)499),
((NI32)42569),
((NI32)499),
((NI32)42571),
((NI32)499),
((NI32)42573),
((NI32)499),
((NI32)42575),
((NI32)499),
((NI32)42577),
((NI32)499),
((NI32)42579),
((NI32)499),
((NI32)42581),
((NI32)499),
((NI32)42583),
((NI32)499),
((NI32)42585),
((NI32)499),
((NI32)42587),
((NI32)499),
((NI32)42589),
((NI32)499),
((NI32)42591),
((NI32)499),
((NI32)42593),
((NI32)499),
((NI32)42595),
((NI32)499),
((NI32)42597),
((NI32)499),
((NI32)42599),
((NI32)499),
((NI32)42601),
((NI32)499),
((NI32)42603),
((NI32)499),
((NI32)42605),
((NI32)499),
((NI32)42625),
((NI32)499),
((NI32)42627),
((NI32)499),
((NI32)42629),
((NI32)499),
((NI32)42631),
((NI32)499),
((NI32)42633),
((NI32)499),
((NI32)42635),
((NI32)499),
((NI32)42637),
((NI32)499),
((NI32)42639),
((NI32)499),
((NI32)42641),
((NI32)499),
((NI32)42643),
((NI32)499),
((NI32)42645),
((NI32)499),
((NI32)42647),
((NI32)499),
((NI32)42649),
((NI32)499),
((NI32)42651),
((NI32)499),
((NI32)42787),
((NI32)499),
((NI32)42789),
((NI32)499),
((NI32)42791),
((NI32)499),
((NI32)42793),
((NI32)499),
((NI32)42795),
((NI32)499),
((NI32)42797),
((NI32)499),
((NI32)42799),
((NI32)499),
((NI32)42803),
((NI32)499),
((NI32)42805),
((NI32)499),
((NI32)42807),
((NI32)499),
((NI32)42809),
((NI32)499),
((NI32)42811),
((NI32)499),
((NI32)42813),
((NI32)499),
((NI32)42815),
((NI32)499),
((NI32)42817),
((NI32)499),
((NI32)42819),
((NI32)499),
((NI32)42821),
((NI32)499),
((NI32)42823),
((NI32)499),
((NI32)42825),
((NI32)499),
((NI32)42827),
((NI32)499),
((NI32)42829),
((NI32)499),
((NI32)42831),
((NI32)499),
((NI32)42833),
((NI32)499),
((NI32)42835),
((NI32)499),
((NI32)42837),
((NI32)499),
((NI32)42839),
((NI32)499),
((NI32)42841),
((NI32)499),
((NI32)42843),
((NI32)499),
((NI32)42845),
((NI32)499),
((NI32)42847),
((NI32)499),
((NI32)42849),
((NI32)499),
((NI32)42851),
((NI32)499),
((NI32)42853),
((NI32)499),
((NI32)42855),
((NI32)499),
((NI32)42857),
((NI32)499),
((NI32)42859),
((NI32)499),
((NI32)42861),
((NI32)499),
((NI32)42863),
((NI32)499),
((NI32)42874),
((NI32)499),
((NI32)42876),
((NI32)499),
((NI32)42879),
((NI32)499),
((NI32)42881),
((NI32)499),
((NI32)42883),
((NI32)499),
((NI32)42885),
((NI32)499),
((NI32)42887),
((NI32)499),
((NI32)42892),
((NI32)499),
((NI32)42897),
((NI32)499),
((NI32)42899),
((NI32)499),
((NI32)42900),
((NI32)548),
((NI32)42903),
((NI32)499),
((NI32)42905),
((NI32)499),
((NI32)42907),
((NI32)499),
((NI32)42909),
((NI32)499),
((NI32)42911),
((NI32)499),
((NI32)42913),
((NI32)499),
((NI32)42915),
((NI32)499),
((NI32)42917),
((NI32)499),
((NI32)42919),
((NI32)499),
((NI32)42921),
((NI32)499),
((NI32)42933),
((NI32)499),
((NI32)42935),
((NI32)499),
((NI32)42937),
((NI32)499),
((NI32)42939),
((NI32)499),
((NI32)42941),
((NI32)499),
((NI32)42943),
((NI32)499),
((NI32)42947),
((NI32)499),
((NI32)43859),
((NI32)-428)}
;
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4491;
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2723;
	framePtr__flfgrz_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2723 = (*framePtr__flfgrz_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, validateUtf8__cherZhavpbqr_u342)(NIM_CHAR* s_p0, NI s_p0Len_0) {
	NI result;
	NI i_1;
	NI L_1;
	nimfr_("validateUtf8", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/unicode.nim");
{	nimlf_(184, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/unicode.nim");	i_1 = ((NI)0);
	nimln_(185);	L_1 = s_p0Len_0;
	{
		nimln_(186);		while (1) {
			if (!(i_1 < L_1)) goto LA2;
			nimln_(187);			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2;
				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU64)(((NU) (((NU8)(s_p0[i_1]))))) <= (NU64)(((NU)127)))) goto LA5_;
				nimln_(188);				if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2);
			}
			goto LA3_;
LA5_: ;
			{
				nimln_(189);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)5))) == ((NU)6))) goto LA8_;
				nimln_(190);				{
					if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
					}
					if (!((NU64)(((NU) (((NU8)(s_p0[i_1]))))) < (NU64)(((NU)194)))) goto LA12_;
					nimln_(176);					nimln_(190);					result = i_1;
					goto BeforeRet_;
				}
LA12_: ;
				nimln_(191);				{
					NIM_BOOL T16_;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_5;
					T16_ = (NIM_BOOL)0;
					if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3)) { raiseOverflow(); goto BeforeRet_;
					};
					T16_ = ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3) < L_1);
					if (!(T16_)) goto LA17_;
					if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4),s_p0Len_0-1); goto BeforeRet_;
					}
					T16_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4)]))))) >> (NU64)(((NI)6))) == ((NU)2));
LA17_: ;
					if (!T16_) goto LA18_;
					if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_5)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_5);
				}
				goto LA14_;
LA18_: ;
				{
					nimln_(192);					nimln_(176);					nimln_(192);					result = i_1;
					goto BeforeRet_;
				}
LA14_: ;
			}
			goto LA3_;
LA8_: ;
			{
				nimln_(193);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)4))) == ((NU)14))) goto LA22_;
				nimln_(194);				{
					NIM_BOOL T26_;
					NIM_BOOL T27_;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_6;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_9;
					T26_ = (NIM_BOOL)0;
					T27_ = (NIM_BOOL)0;
					if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_6)) { raiseOverflow(); goto BeforeRet_;
					};
					T27_ = ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_6) < L_1);
					if (!(T27_)) goto LA28_;
					if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7),s_p0Len_0-1); goto BeforeRet_;
					}
					T27_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7)]))))) >> (NU64)(((NI)6))) == ((NU)2));
LA28_: ;
					T26_ = T27_;
					if (!(T26_)) goto LA29_;
					if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8),s_p0Len_0-1); goto BeforeRet_;
					}
					T26_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8)]))))) >> (NU64)(((NI)6))) == ((NU)2));
LA29_: ;
					if (!T26_) goto LA30_;
					nimln_(195);					if (nimAddInt(i_1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_9)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_9);
				}
				goto LA24_;
LA30_: ;
				{
					nimln_(196);					nimln_(176);					nimln_(196);					result = i_1;
					goto BeforeRet_;
				}
LA24_: ;
			}
			goto LA3_;
LA22_: ;
			{
				nimln_(197);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)3))) == ((NU)30))) goto LA34_;
				nimln_(198);				{
					NIM_BOOL T38_;
					NIM_BOOL T39_;
					NIM_BOOL T40_;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14;
					nimln_(199);					T38_ = (NIM_BOOL)0;
					nimln_(198);					T39_ = (NIM_BOOL)0;
					T40_ = (NIM_BOOL)0;
					if (nimAddInt(i_1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10)) { raiseOverflow(); goto BeforeRet_;
					};
					T40_ = ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10) < L_1);
					if (!(T40_)) goto LA41_;
					if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11),s_p0Len_0-1); goto BeforeRet_;
					}
					T40_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11)]))))) >> (NU64)(((NI)6))) == ((NU)2));
LA41_: ;
					T39_ = T40_;
					if (!(T39_)) goto LA42_;
					nimln_(199);					if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12),s_p0Len_0-1); goto BeforeRet_;
					}
					T39_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12)]))))) >> (NU64)(((NI)6))) == ((NU)2));
LA42_: ;
					T38_ = T39_;
					if (!(T38_)) goto LA43_;
					nimln_(200);					if (nimAddInt(i_1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13),s_p0Len_0-1); goto BeforeRet_;
					}
					T38_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13)]))))) >> (NU64)(((NI)6))) == ((NU)2));
LA43_: ;
					if (!T38_) goto LA44_;
					nimln_(201);					if (nimAddInt(i_1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14);
				}
				goto LA36_;
LA44_: ;
				{
					nimln_(202);					nimln_(176);					nimln_(202);					result = i_1;
					goto BeforeRet_;
				}
LA36_: ;
			}
			goto LA3_;
LA34_: ;
			{
				nimln_(204);				nimln_(176);				nimln_(204);				result = i_1;
				goto BeforeRet_;
			}
LA3_: ;
		} LA2: ;
	}
	nimln_(205);	nimln_(176);	nimln_(205);	result = ((NI)-1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nucruneLen)(NIM_CHAR* s_p0, NI s_p0Len_0) {
	NI result;
	NI i_1;
	nimfr_("runeLen", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/unicode.nim");
{	nimln_(52);	result = ((NI)0);
	nimln_(53);	i_1 = ((NI)0);
	{
		nimln_(54);		while (1) {
			NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22;
			if (!(i_1 < s_p0Len_0)) goto LA2;
			nimln_(55);			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_15;
				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU64)(((NU) (((NU8)(s_p0[i_1]))))) <= (NU64)(((NU)127)))) goto LA5_;
				if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_15)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_15);
			}
			goto LA3_;
LA5_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_16;
				nimln_(56);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)5))) == ((NU)6))) goto LA8_;
				if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_16)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_16);
			}
			goto LA3_;
LA8_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17;
				nimln_(57);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)4))) == ((NU)14))) goto LA11_;
				if (nimAddInt(i_1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17);
			}
			goto LA3_;
LA11_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18;
				nimln_(58);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)3))) == ((NU)30))) goto LA14_;
				if (nimAddInt(i_1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18);
			}
			goto LA3_;
LA14_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_19;
				nimln_(59);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)2))) == ((NU)62))) goto LA17_;
				if (nimAddInt(i_1, ((NI)5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_19)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_19);
			}
			goto LA3_;
LA17_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_20;
				nimln_(60);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)1))) == ((NU)126))) goto LA20_;
				if (nimAddInt(i_1, ((NI)6), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_20)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_20);
			}
			goto LA3_;
LA20_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21;
				nimln_(61);				if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21);
			}
LA3_: ;
			nimln_(62);			if (nimAddInt(result, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22)) { raiseOverflow(); goto BeforeRet_;
			};
			result = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22);
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NF, toFloat__flfgrz_u1681)(NI i_p0) {
	NF result;
	nimfr_("toFloat", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");
	nimlf_(1290, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");	result = ((NF) (i_p0));
	popFrame();
	return result;
}
static N_INLINE(NF, abs__flfgrz_u5426)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	NF floatProd_1;
	NF T1_;
	NF T2_;
	NF resAsFloat_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) * (NU64)(((NU) (b_p1))))));
	T1_ = (NF)0;
	T1_ = toFloat__flfgrz_u1681(a_p0);
	T2_ = (NF)0;
	T2_ = toFloat__flfgrz_u1681(b_p1);
	floatProd_1 = ((NF)(T1_) * (NF)(T2_));
	resAsFloat_1 = toFloat__flfgrz_u1681(r_1);
	{
		if (!(resAsFloat_1 == floatProd_1)) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA3_;
LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__flfgrz_u5426(((NF)(resAsFloat_1) - (NF)(floatProd_1)));
			T11_ = (NF)0;
			T11_ = abs__flfgrz_u5426(floatProd_1);
			if (!(((NF)(32.0) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res_p2) = r_1;
		}
		goto LA8_;
LA12_: ;
		{
			result = NIM_TRUE;
		}
LA8_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, binarySearch__cherZhavpbqr_u1119)(NI32 c_p0, NI32* tab_p1, NI tab_p1Len_0, NI len_p2, NI stride_p3) {
	NI result;
	NI n_1;
	NI t_1;
	nimfr_("binarySearch", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/unicode.nim");
{	nimlf_(468, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/unicode.nim");	n_1 = len_p2;
	nimln_(469);	t_1 = ((NI)0);
	{
		nimln_(470);		while (1) {
			NI m_1;
			NI p_1;
			NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_55;
			NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_56;
			if (!(((NI)1) < n_1)) goto LA2;
			nimln_(471);			m_1 = (NI)((n_1) / (((NI)2)));
			nimln_(472);			if (nimMulInt(m_1, stride_p3, &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_55)) { raiseOverflow(); goto BeforeRet_;
			};
			if (nimAddInt(t_1, (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_55), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_56)) { raiseOverflow(); goto BeforeRet_;
			};
			p_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_56);
			nimln_(473);			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_57;
				if (p_1 < 0 || p_1 >= tab_p1Len_0){ raiseIndexError2(p_1,tab_p1Len_0-1); goto BeforeRet_;
				}
				if (!(tab_p1[p_1] <= c_p0)) goto LA5_;
				nimln_(474);				t_1 = p_1;
				nimln_(475);				if (nimSubInt(n_1, m_1, &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_57)) { raiseOverflow(); goto BeforeRet_;
				};
				n_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_57);
			}
			goto LA3_;
LA5_: ;
			{
				nimln_(477);				n_1 = m_1;
			}
LA3_: ;
		} LA2: ;
	}
	nimln_(478);	{
		NIM_BOOL T10_;
		T10_ = (NIM_BOOL)0;
		T10_ = !((n_1 == ((NI)0)));
		if (!(T10_)) goto LA11_;
		if (t_1 < 0 || t_1 >= tab_p1Len_0){ raiseIndexError2(t_1,tab_p1Len_0-1); goto BeforeRet_;
		}
		T10_ = (tab_p1[t_1] <= c_p0);
LA11_: ;
		if (!T10_) goto LA12_;
		nimln_(479);		nimln_(467);		nimln_(479);		result = t_1;
		goto BeforeRet_;
	}
LA12_: ;
	nimln_(480);	nimln_(467);	nimln_(480);	result = ((NI)-1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4491);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI32, nuctoUpper)(NI32 c_p0) {
	NI32 result;
	NI32 c_2;
	NI p_1;
NIM_BOOL* nimErr_;
	nimfr_("toUpper", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/unicode.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimln_(509);	c_2 = c_p0;
	nimln_(510);	p_1 = binarySearch__cherZhavpbqr_u1119(c_2, toUpperRanges__cherZhavpbqr_u1112, 138, ((NI)46), ((NI)3));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(511);	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_58;
		NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_59;
		NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_60;
		NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_61;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = (((NI)0) <= p_1);
		if (!(T4_)) goto LA5_;
		if ((NU)(p_1) > (NU)(137)){ raiseIndexError2(p_1, 137); goto BeforeRet_;
		}
		T4_ = (toUpperRanges__cherZhavpbqr_u1112[(p_1)- 0] <= c_2);
LA5_: ;
		T3_ = T4_;
		if (!(T3_)) goto LA6_;
		if (nimAddInt(p_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_58)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_58)) > (NU)(137)){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_58), 137); goto BeforeRet_;
		}
		T3_ = (c_2 <= toUpperRanges__cherZhavpbqr_u1112[((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_58))- 0]);
LA6_: ;
		if (!T3_) goto LA7_;
		nimln_(512);		nimln_(500);		nimln_(512);		if (nimAddInt(p_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_59)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_59)) > (NU)(137)){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_59), 137); goto BeforeRet_;
		}
		if (nimAddInt(c_2, toUpperRanges__cherZhavpbqr_u1112[((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_59))- 0], &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_60)) { raiseOverflow(); goto BeforeRet_;
		};
		if (TM__e1RUVS0Bw7xmj9cnDPXLJMQ_60 < (-2147483647 -1) || TM__e1RUVS0Bw7xmj9cnDPXLJMQ_60 > 2147483647){ raiseOverflow(); goto BeforeRet_;
		}
		if (nimSubInt((NI32)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_60), ((NI32)500), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_61)) { raiseOverflow(); goto BeforeRet_;
		};
		if (TM__e1RUVS0Bw7xmj9cnDPXLJMQ_61 < (-2147483647 -1) || TM__e1RUVS0Bw7xmj9cnDPXLJMQ_61 > 2147483647){ raiseOverflow(); goto BeforeRet_;
		}
		result = (NI32)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_61);
		goto BeforeRet_;
	}
LA7_: ;
	nimln_(513);	p_1 = binarySearch__cherZhavpbqr_u1119(c_2, toUpperSinglets__cherZhavpbqr_u1113, 1248, ((NI)624), ((NI)2));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(514);	{
		NIM_BOOL T11_;
		NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_62;
		NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_63;
		NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_64;
		T11_ = (NIM_BOOL)0;
		T11_ = (((NI)0) <= p_1);
		if (!(T11_)) goto LA12_;
		if ((NU)(p_1) > (NU)(1247)){ raiseIndexError2(p_1, 1247); goto BeforeRet_;
		}
		T11_ = (c_2 == toUpperSinglets__cherZhavpbqr_u1113[(p_1)- 0]);
LA12_: ;
		if (!T11_) goto LA13_;
		nimln_(515);		nimln_(500);		nimln_(515);		if (nimAddInt(p_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_62)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_62)) > (NU)(1247)){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_62), 1247); goto BeforeRet_;
		}
		if (nimAddInt(c_2, toUpperSinglets__cherZhavpbqr_u1113[((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_62))- 0], &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_63)) { raiseOverflow(); goto BeforeRet_;
		};
		if (TM__e1RUVS0Bw7xmj9cnDPXLJMQ_63 < (-2147483647 -1) || TM__e1RUVS0Bw7xmj9cnDPXLJMQ_63 > 2147483647){ raiseOverflow(); goto BeforeRet_;
		}
		if (nimSubInt((NI32)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_63), ((NI32)500), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_64)) { raiseOverflow(); goto BeforeRet_;
		};
		if (TM__e1RUVS0Bw7xmj9cnDPXLJMQ_64 < (-2147483647 -1) || TM__e1RUVS0Bw7xmj9cnDPXLJMQ_64 > 2147483647){ raiseOverflow(); goto BeforeRet_;
		}
		result = (NI32)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_64);
		goto BeforeRet_;
	}
LA13_: ;
	nimln_(516);	nimln_(500);	nimln_(516);	result = c_2;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, lteqpercent___flfgrz_u1082)(NI32 x_p0, NI32 y_p1) {
	NIM_BOOL result;
	nimfr_("<=%", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/comparisons.nim");
	result = ((NU32)(((NU32) (x_p0))) <= (NU32)(((NU32) (y_p1))));
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__flfgrz_u2441(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nuctoUpperStr)(NIM_CHAR* s_p0, NI s_p0Len_0) {
	NimStringV2 result;
	NI iX60gensym193__1;
	NI resultIndexX60gensym193__1;
	NI32 runeX60gensym193__1;
NIM_BOOL* nimErr_;
	nimfr_("toUpper", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/unicode.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(666);	if ((s_p0Len_0) < ((NI)0) || (s_p0Len_0) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0Len_0, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0Len_0));
	nimln_(668);	iX60gensym193__1 = ((NI)0);
	nimln_(669);	resultIndexX60gensym193__1 = ((NI)0);
	runeX60gensym193__1 = (NI32)0;
	{
		nimln_(681);		while (1) {
			NI32 iX60gensym215__1;
			nimln_(671);			if (!(iX60gensym193__1 < s_p0Len_0)) goto LA2;
			nimln_(672);			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23;
				nimln_(90);				if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU64)(((NU) (((NU8)(s_p0[iX60gensym193__1]))))) <= (NU64)(((NU)127)))) goto LA5_;
				nimln_(672);				nimln_(91);				if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (((NU) (((NU8)(s_p0[iX60gensym193__1])))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
				}
				runeX60gensym193__1 = ((NI32) (((NU) (((NU8)(s_p0[iX60gensym193__1]))))));
				nimln_(92);				if (nimAddInt(iX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23)) { raiseOverflow(); goto BeforeRet_;
				};
				iX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23);
			}
			goto LA3_;
LA5_: ;
			{
				nimln_(93);				if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[iX60gensym193__1]))))) >> (NU64)(((NI)5))) == ((NU)6))) goto LA8_;
				nimln_(95);				{
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_24;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_25;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_26;
					if (nimSubInt(s_p0Len_0, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_24)) { raiseOverflow(); goto BeforeRet_;
					};
					if (!(iX60gensym193__1 <= (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_24))) goto LA12_;
					nimln_(672);					nimln_(96);					if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(97);					if (nimAddInt(iX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_25)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_25) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_25) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_25),s_p0Len_0-1); goto BeforeRet_;
					}
					if ((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[iX60gensym193__1])))) & ((NU)31))) << (NU64)(((NI)6))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_25)])))) & ((NU)63))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
					}
					runeX60gensym193__1 = ((NI32) ((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[iX60gensym193__1])))) & ((NU)31))) << (NU64)(((NI)6))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_25)])))) & ((NU)63)))));
					nimln_(98);					if (nimAddInt(iX60gensym193__1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_26)) { raiseOverflow(); goto BeforeRet_;
					};
					iX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_26);
				}
				goto LA10_;
LA12_: ;
				{
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_27;
					nimln_(672);					nimln_(100);					runeX60gensym193__1 = ((NI32)65533);
					nimln_(101);					if (nimAddInt(iX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_27)) { raiseOverflow(); goto BeforeRet_;
					};
					iX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_27);
				}
LA10_: ;
			}
			goto LA3_;
LA8_: ;
			{
				nimln_(102);				if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[iX60gensym193__1]))))) >> (NU64)(((NI)4))) == ((NU)14))) goto LA16_;
				nimln_(105);				{
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_28;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_29;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_30;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_31;
					if (nimSubInt(s_p0Len_0, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_28)) { raiseOverflow(); goto BeforeRet_;
					};
					if (!(iX60gensym193__1 <= (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_28))) goto LA20_;
					nimln_(672);					nimln_(106);					nimln_(107);					nimln_(106);					if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(107);					if (nimAddInt(iX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_29)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_29) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_29) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_29),s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(108);					if (nimAddInt(iX60gensym193__1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_30)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_30) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_30) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_30),s_p0Len_0-1); goto BeforeRet_;
					}
					if ((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[iX60gensym193__1])))) & ((NU)15))) << (NU64)(((NI)12))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_29)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_30)])))) & ((NU)63))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
					}
					runeX60gensym193__1 = ((NI32) ((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[iX60gensym193__1])))) & ((NU)15))) << (NU64)(((NI)12))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_29)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_30)])))) & ((NU)63)))));
					nimln_(109);					if (nimAddInt(iX60gensym193__1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_31)) { raiseOverflow(); goto BeforeRet_;
					};
					iX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_31);
				}
				goto LA18_;
LA20_: ;
				{
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_32;
					nimln_(672);					nimln_(111);					runeX60gensym193__1 = ((NI32)65533);
					nimln_(112);					if (nimAddInt(iX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_32)) { raiseOverflow(); goto BeforeRet_;
					};
					iX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_32);
				}
LA18_: ;
			}
			goto LA3_;
LA16_: ;
			{
				nimln_(113);				if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[iX60gensym193__1]))))) >> (NU64)(((NI)3))) == ((NU)30))) goto LA24_;
				nimln_(117);				{
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_33;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_34;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_35;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_37;
					if (nimSubInt(s_p0Len_0, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_33)) { raiseOverflow(); goto BeforeRet_;
					};
					if (!(iX60gensym193__1 <= (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_33))) goto LA28_;
					nimln_(672);					nimln_(118);					nimln_(120);					nimln_(119);					nimln_(118);					if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(119);					if (nimAddInt(iX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_34)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_34) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_34) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_34),s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(120);					if (nimAddInt(iX60gensym193__1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_35)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_35) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_35) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_35),s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(121);					if (nimAddInt(iX60gensym193__1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36),s_p0Len_0-1); goto BeforeRet_;
					}
					if ((NU)((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[iX60gensym193__1])))) & ((NU)7))) << (NU64)(((NI)18))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_34)])))) & ((NU)63))) << (NU64)(((NI)12)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_35)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36)])))) & ((NU)63))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
					}
					runeX60gensym193__1 = ((NI32) ((NU)((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[iX60gensym193__1])))) & ((NU)7))) << (NU64)(((NI)18))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_34)])))) & ((NU)63))) << (NU64)(((NI)12)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_35)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36)])))) & ((NU)63)))));
					nimln_(122);					if (nimAddInt(iX60gensym193__1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_37)) { raiseOverflow(); goto BeforeRet_;
					};
					iX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_37);
				}
				goto LA26_;
LA28_: ;
				{
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_38;
					nimln_(672);					nimln_(124);					runeX60gensym193__1 = ((NI32)65533);
					nimln_(125);					if (nimAddInt(iX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_38)) { raiseOverflow(); goto BeforeRet_;
					};
					iX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_38);
				}
LA26_: ;
			}
			goto LA3_;
LA24_: ;
			{
				nimln_(126);				if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[iX60gensym193__1]))))) >> (NU64)(((NI)2))) == ((NU)62))) goto LA32_;
				nimln_(131);				{
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_39;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_40;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_41;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_44;
					if (nimSubInt(s_p0Len_0, ((NI)5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_39)) { raiseOverflow(); goto BeforeRet_;
					};
					if (!(iX60gensym193__1 <= (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_39))) goto LA36_;
					nimln_(672);					nimln_(132);					nimln_(135);					nimln_(134);					nimln_(133);					nimln_(132);					if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(133);					if (nimAddInt(iX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_40)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_40) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_40) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_40),s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(134);					if (nimAddInt(iX60gensym193__1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_41)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_41) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_41) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_41),s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(135);					if (nimAddInt(iX60gensym193__1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42),s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(136);					if (nimAddInt(iX60gensym193__1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43),s_p0Len_0-1); goto BeforeRet_;
					}
					if ((NU)((NU)((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[iX60gensym193__1])))) & ((NU)3))) << (NU64)(((NI)24))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_40)])))) & ((NU)63))) << (NU64)(((NI)18)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_41)])))) & ((NU)63))) << (NU64)(((NI)12)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43)])))) & ((NU)63))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
					}
					runeX60gensym193__1 = ((NI32) ((NU)((NU)((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[iX60gensym193__1])))) & ((NU)3))) << (NU64)(((NI)24))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_40)])))) & ((NU)63))) << (NU64)(((NI)18)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_41)])))) & ((NU)63))) << (NU64)(((NI)12)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43)])))) & ((NU)63)))));
					nimln_(137);					if (nimAddInt(iX60gensym193__1, ((NI)5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_44)) { raiseOverflow(); goto BeforeRet_;
					};
					iX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_44);
				}
				goto LA34_;
LA36_: ;
				{
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_45;
					nimln_(672);					nimln_(139);					runeX60gensym193__1 = ((NI32)65533);
					nimln_(140);					if (nimAddInt(iX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_45)) { raiseOverflow(); goto BeforeRet_;
					};
					iX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_45);
				}
LA34_: ;
			}
			goto LA3_;
LA32_: ;
			{
				nimln_(141);				if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[iX60gensym193__1]))))) >> (NU64)(((NI)1))) == ((NU)126))) goto LA40_;
				nimln_(147);				{
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_46;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_47;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_48;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_52;
					if (nimSubInt(s_p0Len_0, ((NI)6), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_46)) { raiseOverflow(); goto BeforeRet_;
					};
					if (!(iX60gensym193__1 <= (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_46))) goto LA44_;
					nimln_(672);					nimln_(148);					nimln_(152);					nimln_(151);					nimln_(150);					nimln_(149);					nimln_(148);					if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(149);					if (nimAddInt(iX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_47)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_47) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_47) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_47),s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(150);					if (nimAddInt(iX60gensym193__1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_48)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_48) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_48) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_48),s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(151);					if (nimAddInt(iX60gensym193__1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49),s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(152);					if (nimAddInt(iX60gensym193__1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50),s_p0Len_0-1); goto BeforeRet_;
					}
					nimln_(153);					if (nimAddInt(iX60gensym193__1, ((NI)5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51),s_p0Len_0-1); goto BeforeRet_;
					}
					if ((NU)((NU)((NU)((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[iX60gensym193__1])))) & ((NU)1))) << (NU64)(((NI)30))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_47)])))) & ((NU)63))) << (NU64)(((NI)24)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_48)])))) & ((NU)63))) << (NU64)(((NI)18)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49)])))) & ((NU)63))) << (NU64)(((NI)12)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51)])))) & ((NU)63))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
					}
					runeX60gensym193__1 = ((NI32) ((NU)((NU)((NU)((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[iX60gensym193__1])))) & ((NU)1))) << (NU64)(((NI)30))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_47)])))) & ((NU)63))) << (NU64)(((NI)24)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_48)])))) & ((NU)63))) << (NU64)(((NI)18)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49)])))) & ((NU)63))) << (NU64)(((NI)12)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51)])))) & ((NU)63)))));
					nimln_(154);					if (nimAddInt(iX60gensym193__1, ((NI)6), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_52)) { raiseOverflow(); goto BeforeRet_;
					};
					iX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_52);
				}
				goto LA42_;
LA44_: ;
				{
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_53;
					nimln_(672);					nimln_(156);					runeX60gensym193__1 = ((NI32)65533);
					nimln_(157);					if (nimAddInt(iX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_53)) { raiseOverflow(); goto BeforeRet_;
					};
					iX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_53);
				}
LA42_: ;
			}
			goto LA3_;
LA40_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_54;
				nimln_(672);				nimln_(159);				if (iX60gensym193__1 < 0 || iX60gensym193__1 >= s_p0Len_0){ raiseIndexError2(iX60gensym193__1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (((NU) (((NU8)(s_p0[iX60gensym193__1])))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
				}
				runeX60gensym193__1 = ((NI32) (((NU) (((NU8)(s_p0[iX60gensym193__1]))))));
				nimln_(160);				if (nimAddInt(iX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_54)) { raiseOverflow(); goto BeforeRet_;
				};
				iX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_54);
			}
LA3_: ;
			nimln_(673);			runeX60gensym193__1 = nuctoUpper(runeX60gensym193__1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(221);			iX60gensym215__1 = runeX60gensym193__1;
			nimln_(674);			{
				NIM_BOOL T50_;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_65;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_66;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_67;
				nimln_(222);				T50_ = (NIM_BOOL)0;
				T50_ = lteqpercent___flfgrz_u1082(iX60gensym215__1, ((NI32)127));
				if (!T50_) goto LA51_;
				nimln_(223);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_65)) { raiseOverflow(); goto BeforeRet_;
				};
				if (((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_65)) < ((NI)0) || ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_65)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_65), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				setLengthStrV2((&result), ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_65)));
				nimln_(224);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)0), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_66)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_66) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_66) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_66),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if ((iX60gensym215__1) < ((NI)0) || (iX60gensym215__1) > ((NI)255)){ raiseRangeErrorI(iX60gensym215__1, ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_66)] = ((NIM_CHAR) (((NI) (iX60gensym215__1))));
				nimln_(225);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_67)) { raiseOverflow(); goto BeforeRet_;
				};
				resultIndexX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_67);
			}
			goto LA48_;
LA51_: ;
			{
				NIM_BOOL T54_;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_68;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_69;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_70;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_71;
				nimln_(226);				T54_ = (NIM_BOOL)0;
				T54_ = lteqpercent___flfgrz_u1082(iX60gensym215__1, ((NI32)2047));
				if (!T54_) goto LA55_;
				nimln_(227);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_68)) { raiseOverflow(); goto BeforeRet_;
				};
				if (((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_68)) < ((NI)0) || ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_68)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_68), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				setLengthStrV2((&result), ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_68)));
				nimln_(228);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)0), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_69)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_69) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_69) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_69),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) | ((NI32)192))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) | ((NI32)192))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) | ((NI32)192)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_69)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) | ((NI32)192))))));
				nimln_(229);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_70)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_70) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_70) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_70),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_70)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))))));
				nimln_(230);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_71)) { raiseOverflow(); goto BeforeRet_;
				};
				resultIndexX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_71);
			}
			goto LA48_;
LA55_: ;
			{
				NIM_BOOL T58_;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_72;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_73;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_74;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_75;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_76;
				nimln_(231);				T58_ = (NIM_BOOL)0;
				T58_ = lteqpercent___flfgrz_u1082(iX60gensym215__1, ((NI32)65535));
				if (!T58_) goto LA59_;
				nimln_(232);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_72)) { raiseOverflow(); goto BeforeRet_;
				};
				if (((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_72)) < ((NI)0) || ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_72)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_72), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				setLengthStrV2((&result), ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_72)));
				nimln_(233);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)0), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_73)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_73) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_73) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_73),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) | ((NI32)224))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) | ((NI32)224))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) | ((NI32)224)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_73)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) | ((NI32)224))))));
				nimln_(234);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_74)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_74) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_74) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_74),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_74)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))))));
				nimln_(235);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_75)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_75) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_75) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_75),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_75)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))))));
				nimln_(236);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_76)) { raiseOverflow(); goto BeforeRet_;
				};
				resultIndexX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_76);
			}
			goto LA48_;
LA59_: ;
			{
				NIM_BOOL T62_;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_77;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_78;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_79;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_80;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_81;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_82;
				nimln_(237);				T62_ = (NIM_BOOL)0;
				T62_ = lteqpercent___flfgrz_u1082(iX60gensym215__1, ((NI32)2097151));
				if (!T62_) goto LA63_;
				nimln_(238);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_77)) { raiseOverflow(); goto BeforeRet_;
				};
				if (((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_77)) < ((NI)0) || ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_77)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_77), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				setLengthStrV2((&result), ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_77)));
				nimln_(239);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)0), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_78)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_78) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_78) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_78),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)18))) | ((NI32)240))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)18))) | ((NI32)240))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)18))) | ((NI32)240)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_78)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)18))) | ((NI32)240))))));
				nimln_(240);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_79)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_79) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_79) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_79),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_79)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))))));
				nimln_(241);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_80)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_80) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_80) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_80),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_80)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))))));
				nimln_(242);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_81)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_81) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_81) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_81),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_81)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))))));
				nimln_(243);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_82)) { raiseOverflow(); goto BeforeRet_;
				};
				resultIndexX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_82);
			}
			goto LA48_;
LA63_: ;
			{
				NIM_BOOL T66_;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_83;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_84;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_85;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_86;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_87;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_88;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_89;
				nimln_(244);				T66_ = (NIM_BOOL)0;
				T66_ = lteqpercent___flfgrz_u1082(iX60gensym215__1, ((NI32)67108863));
				if (!T66_) goto LA67_;
				nimln_(245);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_83)) { raiseOverflow(); goto BeforeRet_;
				};
				if (((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_83)) < ((NI)0) || ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_83)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_83), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				setLengthStrV2((&result), ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_83)));
				nimln_(246);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)0), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_84)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_84) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_84) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_84),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)24))) | ((NI32)248))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)24))) | ((NI32)248))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)24))) | ((NI32)248)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_84)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)24))) | ((NI32)248))))));
				nimln_(247);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_85)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_85) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_85) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_85),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_85)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))))));
				nimln_(248);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_86)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_86) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_86) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_86),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_86)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))))));
				nimln_(249);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_87)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_87) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_87) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_87),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_87)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))))));
				nimln_(250);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_88)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_88) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_88) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_88),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_88)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))))));
				nimln_(251);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_89)) { raiseOverflow(); goto BeforeRet_;
				};
				resultIndexX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_89);
			}
			goto LA48_;
LA67_: ;
			{
				NIM_BOOL T70_;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_90;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_91;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_92;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_93;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_94;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_95;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_96;
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_97;
				nimln_(252);				T70_ = (NIM_BOOL)0;
				T70_ = lteqpercent___flfgrz_u1082(iX60gensym215__1, ((NI32)2147483647));
				if (!T70_) goto LA71_;
				nimln_(253);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)6), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_90)) { raiseOverflow(); goto BeforeRet_;
				};
				if (((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_90)) < ((NI)0) || ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_90)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_90), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				setLengthStrV2((&result), ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_90)));
				nimln_(254);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)0), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_91)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_91) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_91) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_91),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)30))) | ((NI32)252))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)30))) | ((NI32)252))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)30))) | ((NI32)252)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_91)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)30))) | ((NI32)252))))));
				nimln_(255);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_92)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_92) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_92) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_92),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)24))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)24))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)24))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_92)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)24))) & ((NI32)63)) | ((NI32)128))))));
				nimln_(256);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_93)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_93) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_93) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_93),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_93)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))))));
				nimln_(257);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_94)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_94) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_94) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_94),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_94)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))))));
				nimln_(258);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_95)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_95) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_95) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_95),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_95)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym215__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))))));
				nimln_(259);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_96)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_96) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_96) >= result.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_96),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_96)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym215__1 & ((NI32)63)) | ((NI32)128))))));
				nimln_(260);				if (nimAddInt(resultIndexX60gensym193__1, ((NI)6), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_97)) { raiseOverflow(); goto BeforeRet_;
				};
				resultIndexX60gensym193__1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_97);
			}
			goto LA48_;
LA71_: ;
			{
			}
LA48_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
