{.passC: staticExec("pkg-config --cflags libnetfilter_conntrack").}
{.passL: staticExec("pkg-config --libs   libnetfilter_conntrack").}

from os import parentDir, `/`
import futhark

when defined(useFuthark):
  const glibcInclude  = staticExec("nix eval --raw nixpkgs#glibc.dev.outPath") & "/include"
  const nfctInclude   = staticExec("pkg-config --variable=includedir libnetfilter_conntrack")
  const nfnetlinkInc  = staticExec("pkg-config --variable=includedir libnfnetlink")

  importc:
    outputPath currentSourcePath.parentDir / "autogenerated" / "generated_conntrack.nim"

    # libc headers
    path glibcInclude

    # libnetfilter_conntrack headers
    path nfctInclude

    # libnfnetlink headers (required transitively)
    path nfnetlinkInc

    "libnetfilter_conntrack/libnetfilter_conntrack.h"
