/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/core_test_payload.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@fflfgrz@frkprcgvbaf.nim.c.o /home/becker/projects/libnet/nimcache/tests/core_test_payload.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@fflfgrz@frkprcgvbaf.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_OverflowDefect__32sQQ9bhkjUt1ZaR9cg9caxBQ tyObject_OverflowDefect__32sQQ9bhkjUt1ZaR9cg9caxBQ;
typedef struct tyObject_RefHeader__v6W0l6WAk9csze6Y7qEe5aQ tyObject_RefHeader__v6W0l6WAk9csze6Y7qEe5aQ;
typedef struct tyObject_ArithmeticDefect__MIu0UhdmECEmLvttakxM2w tyObject_ArithmeticDefect__MIu0UhdmECEmLvttakxM2w;
typedef struct tyObject_Defect__voUWI9axWVRIEz4prik9b4nA tyObject_Defect__voUWI9axWVRIEz4prik9b4nA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__rz9by4t7i52ayGwIPpdG9akQ tySequence__rz9by4t7i52ayGwIPpdG9akQ;
typedef struct tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content;
typedef struct tyObject_GcEnv__p1YlN9aFWG407OPqZoGrSTg tyObject_GcEnv__p1YlN9aFWG407OPqZoGrSTg;
typedef struct tyObject_CellSeq__OJEVnY9cea7WCnffQAf3ZAg tyObject_CellSeq__OJEVnY9cea7WCnffQAf3ZAg;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__LnR439cj6Ol30bS1oJcmIxA tyObject_CellSeq__LnR439cj6Ol30bS1oJcmIxA;
typedef struct tyTuple__3VT4IQLAjd7uSJIGEvpxEg tyTuple__3VT4IQLAjd7uSJIGEvpxEg;
typedef struct tyObject_RangeDefect__DF1NBJIek6Gi3fwMRH4PFQ tyObject_RangeDefect__DF1NBJIek6Gi3fwMRH4PFQ;
typedef struct tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg;
typedef struct tyObject_IOError__rXbvasvcVWhshyzmMnQ9bjw tyObject_IOError__rXbvasvcVWhshyzmMnQ9bjw;
typedef struct tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg;
typedef struct tyObject_AssertionDefect__IucFyIK4V6Bo9bqt6NfK9ayw tyObject_AssertionDefect__IucFyIK4V6Bo9bqt6NfK9ayw;
typedef struct tyObject_DivByZeroDefect__zR4s9ah49aPdrFl9cXZLo9bP9ag tyObject_DivByZeroDefect__zR4s9ah49aPdrFl9cXZLo9bP9ag;
typedef struct tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ;
typedef struct tyObject_ObjectConversionDefect__QjI9ahrsI9csda0R6hZrqHcw tyObject_ObjectConversionDefect__QjI9ahrsI9csda0R6hZrqHcw;
typedef struct tyObject_FieldDefect__Nxe3P83vUg8lTdEI5muuTA tyObject_FieldDefect__Nxe3P83vUg8lTdEI5muuTA;
typedef struct tyObject_OSError__erxHIBa5o9aloCaHjHww2VA tyObject_OSError__erxHIBa5o9aloCaHjHww2VA;
typedef struct tyObject_NilAccessDefect__klHoW8wyqAPyIXzocp9aL7w tyObject_NilAccessDefect__klHoW8wyqAPyIXzocp9aL7w;
typedef struct tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__v6W0l6WAk9csze6Y7qEe5aQ {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__rz9by4t7i52ayGwIPpdG9akQ {
  NI len; tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__rz9by4t7i52ayGwIPpdG9akQ trace;
	Exception* up;
};
struct tyObject_Defect__voUWI9axWVRIEz4prik9b4nA {
	Exception Sup;
};
struct tyObject_ArithmeticDefect__MIu0UhdmECEmLvttakxM2w {
	tyObject_Defect__voUWI9axWVRIEz4prik9b4nA Sup;
};
struct tyObject_OverflowDefect__32sQQ9bhkjUt1ZaR9cg9caxBQ {
	tyObject_ArithmeticDefect__MIu0UhdmECEmLvttakxM2w Sup;
};
struct tyObject_CellSeq__OJEVnY9cea7WCnffQAf3ZAg {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__LnR439cj6Ol30bS1oJcmIxA {
	NI len;
	NI cap;
	tyTuple__3VT4IQLAjd7uSJIGEvpxEg* d;
};
struct tyObject_GcEnv__p1YlN9aFWG407OPqZoGrSTg {
	tyObject_CellSeq__OJEVnY9cea7WCnffQAf3ZAg traceStack;
	tyObject_CellSeq__LnR439cj6Ol30bS1oJcmIxA toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_RangeDefect__DF1NBJIek6Gi3fwMRH4PFQ {
	tyObject_Defect__voUWI9axWVRIEz4prik9b4nA Sup;
};
struct tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg {
	tyObject_Defect__voUWI9axWVRIEz4prik9b4nA Sup;
};
struct tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg {
	Exception Sup;
};
struct tyObject_IOError__rXbvasvcVWhshyzmMnQ9bjw {
	tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg Sup;
};
struct tyObject_AssertionDefect__IucFyIK4V6Bo9bqt6NfK9ayw {
	tyObject_Defect__voUWI9axWVRIEz4prik9b4nA Sup;
};
struct tyObject_DivByZeroDefect__zR4s9ah49aPdrFl9cXZLo9bP9ag {
	tyObject_ArithmeticDefect__MIu0UhdmECEmLvttakxM2w Sup;
};
struct tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ {
	tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg Sup;
};
struct tyObject_ObjectConversionDefect__QjI9ahrsI9csda0R6hZrqHcw {
	tyObject_Defect__voUWI9axWVRIEz4prik9b4nA Sup;
};
struct tyObject_FieldDefect__Nxe3P83vUg8lTdEI5muuTA {
	tyObject_Defect__voUWI9axWVRIEz4prik9b4nA Sup;
};
struct tyObject_OSError__erxHIBa5o9aloCaHjHww2VA {
	tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg Sup;
	NI32 errorCode;
};
struct tyObject_NilAccessDefect__klHoW8wyqAPyIXzocp9aL7w {
	tyObject_Defect__voUWI9axWVRIEz4prik9b4nA Sup;
};
struct tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content { NI cap; tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5248)(tyObject_OverflowDefect__32sQQ9bhkjUt1ZaR9cg9caxBQ* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___flfgrz_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4709)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__flfgrz_u3528)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__v6W0l6WAk9csze6Y7qEe5aQ* s_p1, TNimTypeV2* desc_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fgqZnffregvbaf_u74)(tySequence__rz9by4t7i52ayGwIPpdG9akQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5260)(tyObject_OverflowDefect__32sQQ9bhkjUt1ZaR9cg9caxBQ* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__flfgrz_u3011)(tyObject_CellSeq__OJEVnY9cea7WCnffQAf3ZAg* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__flfgrz_u3019)(tyObject_CellSeq__OJEVnY9cea7WCnffQAf3ZAg* s_p0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u60)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u4775)(tyObject_RangeDefect__DF1NBJIek6Gi3fwMRH4PFQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u4787)(tyObject_RangeDefect__DF1NBJIek6Gi3fwMRH4PFQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u4844)(tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u4856)(tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u64)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u9034)(tyObject_IOError__rXbvasvcVWhshyzmMnQ9bjw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u9046)(tyObject_IOError__rXbvasvcVWhshyzmMnQ9bjw* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u66)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fgqZnffregvbaf_u35)(tyObject_AssertionDefect__IucFyIK4V6Bo9bqt6NfK9ayw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___fgqZnffregvbaf_u47)(tyObject_AssertionDefect__IucFyIK4V6Bo9bqt6NfK9ayw* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u68)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5314)(tyObject_DivByZeroDefect__zR4s9ah49aPdrFl9cXZLo9bP9ag* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5326)(tyObject_DivByZeroDefect__zR4s9ah49aPdrFl9cXZLo9bP9ag* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u70)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u8182)(tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u8194)(tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u72)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5067)(tyObject_ObjectConversionDefect__QjI9ahrsI9csda0R6hZrqHcw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5079)(tyObject_ObjectConversionDefect__QjI9ahrsI9csda0R6hZrqHcw* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u74)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u4934)(tyObject_FieldDefect__Nxe3P83vUg8lTdEI5muuTA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u4946)(tyObject_FieldDefect__Nxe3P83vUg8lTdEI5muuTA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u76)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fgqZbfreebef_u60)(tyObject_OSError__erxHIBa5o9aloCaHjHww2VA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___fgqZbfreebef_u72)(tyObject_OSError__erxHIBa5o9aloCaHjHww2VA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u78)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5171)(tyObject_NilAccessDefect__klHoW8wyqAPyIXzocp9aL7w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5183)(tyObject_NilAccessDefect__klHoW8wyqAPyIXzocp9aL7w* dest_p0, void* env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__32sQQ9bhkjUt1ZaR9cg9caxBQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__DF1NBJIek6Gi3fwMRH4PFQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__7u631KbObzc6JqpFYL4zNg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__rXbvasvcVWhshyzmMnQ9bjw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__IucFyIK4V6Bo9bqt6NfK9ayw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__zR4s9ah49aPdrFl9cXZLo9bP9ag_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__x5fWkS4bHcHaffIXsxxsPQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__QjI9ahrsI9csda0R6hZrqHcw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__Nxe3P83vUg8lTdEI5muuTA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__erxHIBa5o9aloCaHjHww2VA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__klHoW8wyqAPyIXzocp9aL7w_;
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4491;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[5] = {3701606400, 1285336064, 2232820480, 2343850496, 1796227840};
N_LIB_PRIVATE TNimTypeV2 NTIv2__32sQQ9bhkjUt1ZaR9cg9caxBQ_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u56, .size = sizeof(tyObject_OverflowDefect__32sQQ9bhkjUt1ZaR9cg9caxBQ), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__32sQQ9bhkjUt1ZaR9cg9caxBQ), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)eqtrace___flfgrz_u5260, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[4] = {3701606400, 1285336064, 2232820480, 1565328384};
N_LIB_PRIVATE TNimTypeV2 NTIv2__DF1NBJIek6Gi3fwMRH4PFQ_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u60, .size = sizeof(tyObject_RangeDefect__DF1NBJIek6Gi3fwMRH4PFQ), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__DF1NBJIek6Gi3fwMRH4PFQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)eqtrace___flfgrz_u4787, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[4] = {3701606400, 1285336064, 2232820480, 4005024768};
N_LIB_PRIVATE TNimTypeV2 NTIv2__7u631KbObzc6JqpFYL4zNg_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u62, .size = sizeof(tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_6, .traceImpl = (void*)eqtrace___flfgrz_u4856, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_7[4] = {3701606400, 1285336064, 1872959232, 1995401728};
N_LIB_PRIVATE TNimTypeV2 NTIv2__rXbvasvcVWhshyzmMnQ9bjw_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u64, .size = sizeof(tyObject_IOError__rXbvasvcVWhshyzmMnQ9bjw), .align = (NI16) NIM_ALIGNOF(tyObject_IOError__rXbvasvcVWhshyzmMnQ9bjw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_7, .traceImpl = (void*)eqtrace___flfgrz_u9046, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_8[4] = {3701606400, 1285336064, 2232820480, 3875915776};
N_LIB_PRIVATE TNimTypeV2 NTIv2__IucFyIK4V6Bo9bqt6NfK9ayw_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u66, .size = sizeof(tyObject_AssertionDefect__IucFyIK4V6Bo9bqt6NfK9ayw), .align = (NI16) NIM_ALIGNOF(tyObject_AssertionDefect__IucFyIK4V6Bo9bqt6NfK9ayw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_8, .traceImpl = (void*)eqtrace___fgqZnffregvbaf_u47, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_9[5] = {3701606400, 1285336064, 2232820480, 2343850496, 506263040};
N_LIB_PRIVATE TNimTypeV2 NTIv2__zR4s9ah49aPdrFl9cXZLo9bP9ag_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u68, .size = sizeof(tyObject_DivByZeroDefect__zR4s9ah49aPdrFl9cXZLo9bP9ag), .align = (NI16) NIM_ALIGNOF(tyObject_DivByZeroDefect__zR4s9ah49aPdrFl9cXZLo9bP9ag), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_9, .traceImpl = (void*)eqtrace___flfgrz_u5326, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_10[4] = {3701606400, 1285336064, 1872959232, 2547421440};
N_LIB_PRIVATE TNimTypeV2 NTIv2__x5fWkS4bHcHaffIXsxxsPQ_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u70, .size = sizeof(tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ), .align = (NI16) NIM_ALIGNOF(tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_10, .traceImpl = (void*)eqtrace___flfgrz_u8194, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_11[4] = {3701606400, 1285336064, 2232820480, 842892800};
N_LIB_PRIVATE TNimTypeV2 NTIv2__QjI9ahrsI9csda0R6hZrqHcw_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u72, .size = sizeof(tyObject_ObjectConversionDefect__QjI9ahrsI9csda0R6hZrqHcw), .align = (NI16) NIM_ALIGNOF(tyObject_ObjectConversionDefect__QjI9ahrsI9csda0R6hZrqHcw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_11, .traceImpl = (void*)eqtrace___flfgrz_u5079, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_12[4] = {3701606400, 1285336064, 2232820480, 397885184};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Nxe3P83vUg8lTdEI5muuTA_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u74, .size = sizeof(tyObject_FieldDefect__Nxe3P83vUg8lTdEI5muuTA), .align = (NI16) NIM_ALIGNOF(tyObject_FieldDefect__Nxe3P83vUg8lTdEI5muuTA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_12, .traceImpl = (void*)eqtrace___flfgrz_u4946, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_13[4] = {3701606400, 1285336064, 1872959232, 3158777856};
N_LIB_PRIVATE TNimTypeV2 NTIv2__erxHIBa5o9aloCaHjHww2VA_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u76, .size = sizeof(tyObject_OSError__erxHIBa5o9aloCaHjHww2VA), .align = (NI16) NIM_ALIGNOF(tyObject_OSError__erxHIBa5o9aloCaHjHww2VA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_13, .traceImpl = (void*)eqtrace___fgqZbfreebef_u72, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_14[4] = {3701606400, 1285336064, 2232820480, 1374182144};
N_LIB_PRIVATE TNimTypeV2 NTIv2__klHoW8wyqAPyIXzocp9aL7w_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u78, .size = sizeof(tyObject_NilAccessDefect__klHoW8wyqAPyIXzocp9aL7w), .align = (NI16) NIM_ALIGNOF(tyObject_NilAccessDefect__klHoW8wyqAPyIXzocp9aL7w), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_14, .traceImpl = (void*)eqtrace___flfgrz_u5183, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2723;
	framePtr__flfgrz_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2723 = (*framePtr__flfgrz_u2723).prev;
}
static N_INLINE(NI, minuspercent___flfgrz_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/arithmetics.nim");
	nimlf_(364, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4491);
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("nimDecRefIsLastCyclicDyn", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(512, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(513);	{
		tyObject_RefHeader__v6W0l6WAk9csze6Y7qEe5aQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(514);		nimlf_(58, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___flfgrz_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__v6W0l6WAk9csze6Y7qEe5aQ*) (T5_));
		nimlf_(515, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(516);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			NI TM__TzI3paKQY09cLjc9cmCvur3A_2;
			nimln_(519);			if (nimSubInt((*cell_1).rc, ((NI)16), &TM__TzI3paKQY09cLjc9cmCvur3A_2)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell_1).rc = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_2);
		}
LA6_: ;
		nimln_(521);		rememberCycle__flfgrz_u3528(result, cell_1, (*((TNimTypeV2**) (p_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5248)(tyObject_OverflowDefect__32sQQ9bhkjUt1ZaR9cg9caxBQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u56)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u5248(((tyObject_OverflowDefect__32sQQ9bhkjUt1ZaR9cg9caxBQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, add__flfgrz_u3011)(tyObject_CellSeq__OJEVnY9cea7WCnffQAf3ZAg* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	NI TM__TzI3paKQY09cLjc9cmCvur3A_4;
	nimfr_("add", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/cellseqs_v2.nim");
{	nimlf_(28, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__flfgrz_u3019(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	if (nimAddInt((*s_p0).len, ((NI)1), &TM__TzI3paKQY09cLjc9cmCvur3A_4)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_4);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");
	nimlf_(136, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(137);	{
		tyObject_GcEnv__p1YlN9aFWG407OPqZoGrSTg* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(138);		j_1 = ((tyObject_GcEnv__p1YlN9aFWG407OPqZoGrSTg*) (env_p1));
		nimln_(139);		add__flfgrz_u3011((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5260)(tyObject_OverflowDefect__32sQQ9bhkjUt1ZaR9cg9caxBQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u4775)(tyObject_RangeDefect__DF1NBJIek6Gi3fwMRH4PFQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u60)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u4775(((tyObject_RangeDefect__DF1NBJIek6Gi3fwMRH4PFQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u4787)(tyObject_RangeDefect__DF1NBJIek6Gi3fwMRH4PFQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u4844)(tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u62)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u4844(((tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u4856)(tyObject_IndexDefect__7u631KbObzc6JqpFYL4zNg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u9034)(tyObject_IOError__rXbvasvcVWhshyzmMnQ9bjw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u64)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u9034(((tyObject_IOError__rXbvasvcVWhshyzmMnQ9bjw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u9046)(tyObject_IOError__rXbvasvcVWhshyzmMnQ9bjw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fgqZnffregvbaf_u35)(tyObject_AssertionDefect__IucFyIK4V6Bo9bqt6NfK9ayw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u66)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___fgqZnffregvbaf_u35(((tyObject_AssertionDefect__IucFyIK4V6Bo9bqt6NfK9ayw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___fgqZnffregvbaf_u47)(tyObject_AssertionDefect__IucFyIK4V6Bo9bqt6NfK9ayw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5314)(tyObject_DivByZeroDefect__zR4s9ah49aPdrFl9cXZLo9bP9ag* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u68)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u5314(((tyObject_DivByZeroDefect__zR4s9ah49aPdrFl9cXZLo9bP9ag*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5326)(tyObject_DivByZeroDefect__zR4s9ah49aPdrFl9cXZLo9bP9ag* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u8182)(tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u70)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u8182(((tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u8194)(tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5067)(tyObject_ObjectConversionDefect__QjI9ahrsI9csda0R6hZrqHcw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u72)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u5067(((tyObject_ObjectConversionDefect__QjI9ahrsI9csda0R6hZrqHcw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5079)(tyObject_ObjectConversionDefect__QjI9ahrsI9csda0R6hZrqHcw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u4934)(tyObject_FieldDefect__Nxe3P83vUg8lTdEI5muuTA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u74)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u4934(((tyObject_FieldDefect__Nxe3P83vUg8lTdEI5muuTA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u4946)(tyObject_FieldDefect__Nxe3P83vUg8lTdEI5muuTA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fgqZbfreebef_u60)(tyObject_OSError__erxHIBa5o9aloCaHjHww2VA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u76)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___fgqZbfreebef_u60(((tyObject_OSError__erxHIBa5o9aloCaHjHww2VA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___fgqZbfreebef_u72)(tyObject_OSError__erxHIBa5o9aloCaHjHww2VA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5171)(tyObject_NilAccessDefect__klHoW8wyqAPyIXzocp9aL7w* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u78)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u5171(((tyObject_NilAccessDefect__klHoW8wyqAPyIXzocp9aL7w*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5183)(tyObject_NilAccessDefect__klHoW8wyqAPyIXzocp9aL7w* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
