/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/core_test_payload.nim_4a8a08f09d37b73795649038408b5f33/@z..@ffep@fzrffntrOhvyqre.nim.c.o /home/becker/projects/libnet/nimcache/tests/core_test_payload.nim_4a8a08f09d37b73795649038408b5f33/@z..@ffep@fzrffntrOhvyqre.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA;
typedef struct tyObject_struct_nftnl_rule__5wWhyZMl21akJK8BzSyVLQ tyObject_struct_nftnl_rule__5wWhyZMl21akJK8BzSyVLQ;
typedef struct tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ;
typedef struct tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg;
typedef struct tyObject_struct_nlmsghdr__GEldPvzGjI49c1PrkE6Tjhg tyObject_struct_nlmsghdr__GEldPvzGjI49c1PrkE6Tjhg;
typedef struct tyObject_OSError__erxHIBa5o9aloCaHjHww2VA tyObject_OSError__erxHIBa5o9aloCaHjHww2VA;
typedef struct tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__rz9by4t7i52ayGwIPpdG9akQ tySequence__rz9by4t7i52ayGwIPpdG9akQ;
typedef struct tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content;
typedef struct tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw;
struct tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA {
	tyObject_struct_nftnl_rule__5wWhyZMl21akJK8BzSyVLQ* raw;
};
struct tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ {
	tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg* raw;
};
struct tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg {
	char dummy;
};
struct tyObject_struct_nlmsghdr__GEldPvzGjI49c1PrkE6Tjhg {
	char dummy;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__rz9by4t7i52ayGwIPpdG9akQ {
  NI len; tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__rz9by4t7i52ayGwIPpdG9akQ trace;
	Exception* up;
};
struct tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg {
	Exception Sup;
};
struct tyObject_OSError__erxHIBa5o9aloCaHjHww2VA {
	tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg Sup;
	NI32 errorCode;
};
struct tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content { NI cap; tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw data[SEQ_DECL_SIZE]; };
N_CDECL(void, nftnl_rule_add_expr)(tyObject_struct_nftnl_rule__5wWhyZMl21akJK8BzSyVLQ* r_p0, tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg* expr_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfepZasgayZenvvZrkcerfvbaf_u9)(tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ* x_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, addExpr__OOZfepZzrffntr66hvyqre_u47)(tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA r_p0, tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ e_p1);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__flfgrz_u1749)(NI size_p0);
N_CDECL(tyObject_struct_nlmsghdr__GEldPvzGjI49c1PrkE6Tjhg*, nftnl_nlmsg_build_hdr)(NU8* buf_p0, NU16 type_arg_p1, NU16 family_p2, NU16 flags_p3, NU32 seq_p4);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_CDECL(void, nftnl_rule_nlmsg_build_payload)(tyObject_struct_nlmsghdr__GEldPvzGjI49c1PrkE6Tjhg* nlh_p0, tyObject_struct_nftnl_rule__5wWhyZMl21akJK8BzSyVLQ* t_p1);
extern TNimTypeV2 NTIv2__erxHIBa5o9aloCaHjHww2VA_;
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__ulpTzQIRKBCnmicAwbXcQg_2 = { 24 | NIM_STRLIT_FLAG, "Failed to build nlmsghdr" };
static const NimStringV2 TM__ulpTzQIRKBCnmicAwbXcQg_3 = {24, (NimStrPayload*)&TM__ulpTzQIRKBCnmicAwbXcQg_2};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4491;
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2723;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4491);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2723;
	framePtr__flfgrz_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2723 = (*framePtr__flfgrz_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, addExpr__OOZfepZzrffntr66hvyqre_u47)(tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA r_p0, tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ e_p1) {
NIM_BOOL* nimErr_;
	nimfr_("addExpr", "/home/becker/projects/libnet/src/messageBuilder.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(32, "/home/becker/projects/libnet/src/messageBuilder.nim");	nftnl_rule_add_expr(r_p0.raw, e_p1.raw);
	nimln_(33);	e_p1.raw = ((tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg*) NIM_NIL);
	nimlf_(17, "/home/becker/projects/libnet/src/nftnl/raii/expresions.nim");	eqdestroy___OOZfepZasgayZenvvZrkcerfvbaf_u9((&e_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, addExpr__OOZfepZzrffntr66hvyqre_u50)(tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA r_p0, tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ e_p1) {
	tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ blitTmp_1;
NIM_BOOL* nimErr_;
	nimfr_("addExpr", "/home/becker/projects/libnet/src/messageBuilder.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(36, "/home/becker/projects/libnet/src/messageBuilder.nim");	blitTmp_1 = e_p1;
	addExpr__OOZfepZzrffntr66hvyqre_u47(r_p0, blitTmp_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_struct_nlmsghdr__GEldPvzGjI49c1PrkE6Tjhg*, newNlMsg__OOZfepZzrffntr66hvyqre_u8)(int msgType_p0, int family_p1, int flags_p2, NU32 seq_p3) {
	tyObject_struct_nlmsghdr__GEldPvzGjI49c1PrkE6Tjhg* result;
	NU8* buf_1;
	void* T1_;
	nimfr_("newNlMsg", "/home/becker/projects/libnet/src/messageBuilder.nim");
{	result = (tyObject_struct_nlmsghdr__GEldPvzGjI49c1PrkE6Tjhg*)0;
	nimln_(14);	T1_ = (void*)0;
	T1_ = alloc0Impl__flfgrz_u1749(((NI)8192));
	buf_1 = ((NU8*) (T1_));
	nimln_(15);	nimln_(16);	result = nftnl_nlmsg_build_hdr(buf_1, ((NU16) (msgType_p0)), ((NU16) (family_p1)), ((NU16) (flags_p2)), seq_p3);
	nimln_(17);	{
		tyObject_OSError__erxHIBa5o9aloCaHjHww2VA* T6_;
		if (!(result == 0)) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_OSError__erxHIBa5o9aloCaHjHww2VA*) nimNewObj(sizeof(tyObject_OSError__erxHIBa5o9aloCaHjHww2VA), NIM_ALIGNOF(tyObject_OSError__erxHIBa5o9aloCaHjHww2VA));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__erxHIBa5o9aloCaHjHww2VA_);
		(*T6_).Sup.Sup.name = "OSError";
		(*T6_).Sup.Sup.message = TM__ulpTzQIRKBCnmicAwbXcQg_3;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(18);		raiseExceptionEx((Exception*)T6_, "OSError", "newNlMsg", "/home/becker/projects/libnet/src/messageBuilder.nim", 18);
goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, buildRuleMsg__OOZfepZzrffntr66hvyqre_u44)(tyObject_struct_nlmsghdr__GEldPvzGjI49c1PrkE6Tjhg* nlh_p0, tyObject_Rule__pDKlEigGMPA9b9chdzsHk2aA r_p1) {
	nimfr_("buildRuleMsg", "/home/becker/projects/libnet/src/messageBuilder.nim");
	nimln_(27);	nftnl_rule_nlmsg_build_payload(nlh_p0, r_p1.raw);
	popFrame();
}
