/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/core_test_payload.nim_4a8a08f09d37b73795649038408b5f33/@z..@ffep@fasgay@fnggef@frkce@fnyy.nim.c.o /home/becker/projects/libnet/nimcache/tests/core_test_payload.nim_4a8a08f09d37b73795649038408b5f33/@z..@ffep@fasgay@fnggef@frkce@fnyy.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
N_CDECL(void, nftnl_expr_set_u32)(tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg* expr_p0, NU16 type_arg_p1, NU32 data_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_CDECL(int, nftnl_expr_set)(tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg* expr_p0, NU16 type_arg_p1, void* data_p2, NU32 data_len_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2723;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2723;
	framePtr__flfgrz_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2723 = (*framePtr__flfgrz_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, setU32__OOZfepZasgayZnggefZrkceZnyy_u54)(tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg* p_p0, NU16 attr_p1, NU32 v_p2) {
	nimfr_("setU32", "/home/becker/projects/libnet/src/nftnl/attrs/expr/all.nim");
	nimlf_(21, "/home/becker/projects/libnet/src/nftnl/attrs/expr/all.nim");	nftnl_expr_set_u32(p_p0, attr_p1, v_p2);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setBlob__OOZfepZasgayZnggefZrkceZnyy_u62)(tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg* p_p0, NU16 attr_p1, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ v_p2) {
	nimfr_("setBlob", "/home/becker/projects/libnet/src/nftnl/attrs/expr/all.nim");
{	nimln_(27);	{
		NI T3_;
		NI T6_;
		int T7_;
		T3_ = v_p2.len;
		if (!(((NI)0) < T3_)) goto LA4_;
		nimln_(28);		if (((NI)0) < 0 || ((NI)0) >= v_p2.len){ raiseIndexError2(((NI)0),v_p2.len-1); goto BeforeRet_;
		}
		T6_ = v_p2.len;
		T7_ = (int)0;
		T7_ = nftnl_expr_set(p_p0, attr_p1, ((void*) ((&v_p2.p->data[((NI)0)]))), ((NU32) (T6_)));
		(void)(T7_);
	}
	goto LA1_;
LA4_: ;
	{
		int T9_;
		nimln_(30);		T9_ = (int)0;
		T9_ = nftnl_expr_set(p_p0, attr_p1, NIM_NIL, ((NU32)0));
		(void)(T9_);
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
