{.passC: staticExec("pkg-config --cflags libmnl").}
{.passL: staticExec("pkg-config --libs   libmnl").}

from os import parentDir, `/`
import futhark, os

when defined(useFuthark):
  const
    glibcInclude = staticExec("nix eval --raw nixpkgs#glibc.dev.outPath") & "/include"
    mnlInclude = staticExec("pkg-config --variable=includedir libmnl")
    outDir = currentSourcePath.parentDir / "autogenerated"
    outFile = outDir / "generated_mnl.nim"

  static:
    if not dirExists(outDir):
      createDir(outDir)

  importc:
    outputPath outFile.string
    path glibcInclude
    path mnlInclude

    # Core libmnl API
    "libmnl/libmnl.h"
