/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/core_test_expr.nim_4a8a08f09d37b73795649038408b5f33/@z..@ffep@fyvahk@fnhgbtrarengrq@ftrarengrq_yvahk.nim.c.o /home/becker/projects/libnet/nimcache/tests/core_test_expr.nim_4a8a08f09d37b73795649038408b5f33/@z..@ffep@fyvahk@fnhgbtrarengrq@ftrarengrq_yvahk.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NI32 tyEnum_enum_nft_cmp_ops__kn5lbvxsexMHLGeemzot3Q;
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__NdFjkfA0qe6HUt2xe9aisDg_2 = { 10 | NIM_STRLIT_FLAG, "NFT_CMP_EQ" };
static const NimStringV2 TM__NdFjkfA0qe6HUt2xe9aisDg_3 = {10, (NimStrPayload*)&TM__NdFjkfA0qe6HUt2xe9aisDg_2};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__NdFjkfA0qe6HUt2xe9aisDg_4 = { 11 | NIM_STRLIT_FLAG, "NFT_CMP_NEQ" };
static const NimStringV2 TM__NdFjkfA0qe6HUt2xe9aisDg_5 = {11, (NimStrPayload*)&TM__NdFjkfA0qe6HUt2xe9aisDg_4};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__NdFjkfA0qe6HUt2xe9aisDg_6 = { 10 | NIM_STRLIT_FLAG, "NFT_CMP_LT" };
static const NimStringV2 TM__NdFjkfA0qe6HUt2xe9aisDg_7 = {10, (NimStrPayload*)&TM__NdFjkfA0qe6HUt2xe9aisDg_6};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__NdFjkfA0qe6HUt2xe9aisDg_8 = { 11 | NIM_STRLIT_FLAG, "NFT_CMP_LTE" };
static const NimStringV2 TM__NdFjkfA0qe6HUt2xe9aisDg_9 = {11, (NimStrPayload*)&TM__NdFjkfA0qe6HUt2xe9aisDg_8};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__NdFjkfA0qe6HUt2xe9aisDg_10 = { 10 | NIM_STRLIT_FLAG, "NFT_CMP_GT" };
static const NimStringV2 TM__NdFjkfA0qe6HUt2xe9aisDg_11 = {10, (NimStrPayload*)&TM__NdFjkfA0qe6HUt2xe9aisDg_10};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__NdFjkfA0qe6HUt2xe9aisDg_12 = { 11 | NIM_STRLIT_FLAG, "NFT_CMP_GTE" };
static const NimStringV2 TM__NdFjkfA0qe6HUt2xe9aisDg_13 = {11, (NimStrPayload*)&TM__NdFjkfA0qe6HUt2xe9aisDg_12};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__NdFjkfA0qe6HUt2xe9aisDg_14 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__NdFjkfA0qe6HUt2xe9aisDg_15 = {0, (NimStrPayload*)&TM__NdFjkfA0qe6HUt2xe9aisDg_14};
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZfepZyvahkZnhgbtrarengrqZtrarengrq95yvahk_u503)(tyEnum_enum_nft_cmp_ops__kn5lbvxsexMHLGeemzot3Q e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_enum_nft_cmp_ops__kn5lbvxsexMHLGeemzot3Q)0):
	{
		result = TM__NdFjkfA0qe6HUt2xe9aisDg_3;
	}
	break;
	case ((tyEnum_enum_nft_cmp_ops__kn5lbvxsexMHLGeemzot3Q)1):
	{
		result = TM__NdFjkfA0qe6HUt2xe9aisDg_5;
	}
	break;
	case ((tyEnum_enum_nft_cmp_ops__kn5lbvxsexMHLGeemzot3Q)2):
	{
		result = TM__NdFjkfA0qe6HUt2xe9aisDg_7;
	}
	break;
	case ((tyEnum_enum_nft_cmp_ops__kn5lbvxsexMHLGeemzot3Q)3):
	{
		result = TM__NdFjkfA0qe6HUt2xe9aisDg_9;
	}
	break;
	case ((tyEnum_enum_nft_cmp_ops__kn5lbvxsexMHLGeemzot3Q)4):
	{
		result = TM__NdFjkfA0qe6HUt2xe9aisDg_11;
	}
	break;
	case ((tyEnum_enum_nft_cmp_ops__kn5lbvxsexMHLGeemzot3Q)5):
	{
		result = TM__NdFjkfA0qe6HUt2xe9aisDg_13;
	}
	break;
	default:
	{
		result = TM__NdFjkfA0qe6HUt2xe9aisDg_15;
	}
	break;
	}
	return result;
}
