/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/core_test_expr.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@fcher@ffgehgvyf.nim.c.o /home/becker/projects/libnet/nimcache/tests/core_test_expr.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@fcher@ffgehgvyf.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HSlice__D8skNslIDQFiBPOJgPX2UQ tyObject_HSlice__D8skNslIDQFiBPOJgPX2UQ;
typedef struct tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ;
typedef struct tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__rz9by4t7i52ayGwIPpdG9akQ tySequence__rz9by4t7i52ayGwIPpdG9akQ;
typedef struct tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_HSlice__D8skNslIDQFiBPOJgPX2UQ {
	NI a;
	NI b;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef NI tyArray__9cc9aPiDa8VaWjVcFLabEDZQ[256];
typedef NU8 tyEnum_FloatFormatMode__vFVLuA3pnm9aR06Q9cgLgNCg;
typedef NIM_CHAR tyArray__9bPFPkkEEeeNM9bKgiV8Q49cg[6];
typedef NIM_CHAR tyArray__Kn8ZOVsorvcNLB4isUeMzQ[2501];
typedef NIM_CHAR tyArray__9aDX30HEqQRuxelTqCRUacw[3];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__rz9by4t7i52ayGwIPpdG9akQ {
  NI len; tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__rz9by4t7i52ayGwIPpdG9akQ trace;
	Exception* up;
};
struct tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg {
	Exception Sup;
};
struct tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ {
	tyObject_CatchableError__229bjF79ccDLIhNL4rLreedg Sup;
};
typedef NU8 tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__rz9by4t7i52ayGwIPpdG9akQ_Content { NI cap; tyObject_StackTraceEntry__hQMNsMb4YWHiz9b7KyEycbw data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___cherZfgehgvyf_u1176)(NimStringV2* s_p0, tyObject_HSlice__D8skNslIDQFiBPOJgPX2UQ x_p1, NimStringV2 b_p2);
static N_INLINE(tyObject_HSlice__D8skNslIDQFiBPOJgPX2UQ, dotdot___fgqZfgeonfvpf_u48)(NI a_p0, NI b_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4709)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__flfgrz_u2441)(NimStringV2* s_p0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___flfgrz_u2690)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__fgqZnffregvbaf_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
static N_INLINE(NI, minuspercent___flfgrz_u813)(NI x_p0, NI y_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__flfgrz_u8960)(NimStringV2 s_p0, NI first_p1, NI last_p2);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__flfgrz_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__flfgrz_u8973)(NimStringV2 s_p0, NI first_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__flfgrzZzrzbel_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1);
N_LIB_PRIVATE N_NIMCALL(void, fill__cherZfgehgvyf_u1633)(NI* a_p0, NI a_p0Len_0, NI value_p1);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatBiggestFloat)(NF f_p0, tyEnum_FloatFormatMode__vFVLuA3pnm9aR06Q9cgLgNCg format_p1, NI precision_p2, NIM_CHAR decimalSep_p3);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringV2* s_p0, NimStringV2 formatstr_p1, NimStringV2* a_p2, NI a_p2Len_0);
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__cherZfgehgvyf_u2645)(NimStringV2 formatstr_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NF, toFloat__flfgrz_u1681)(NI i_p0);
static N_INLINE(NF, abs__flfgrz_u5426)(NF x_p0);
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__cherZfgehgvyf_u2632)(NimStringV2 x_p0, NimStringV2* inArray_p1, NI inArray_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_CHAR, toLowerAscii__fgqZcevingrZfgevzcy_u1)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIdentNormalize__cherZfgehgvyf_u122)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__flfgrz_u1739)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, substrEq__cherZfgehgvyf_u255)(NimStringV2 s_p0, NI pos_p1, NimStringV2 substr_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___flfgrz_u2696)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__fgqZrahzhgvyf_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___flfgrz_u2687)(NimStringV2* dest_p0);
static const struct {
  NI cap; NIM_CHAR data[172+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_6 = { 172 | NIM_STRLIT_FLAG, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators.nim(272, 11) `len(a) == L` the length of the string changed while iterating over it" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_7 = {172, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_6};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_8 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_9 = {0, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_8};
extern TNimTypeV2 NTIv2__x5fWkS4bHcHaffIXsxxsPQ_;
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_37 = { 23 | NIM_STRLIT_FLAG, "invalid format string: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_38 = {23, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_37};
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_76 = {0, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_8};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_82 = { 7 | NIM_STRLIT_FLAG, "Verbose" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_83 = {7, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_82};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_84 = { 7 | NIM_STRLIT_FLAG, "Compact" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_85 = {7, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_84};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_86 = { 8 | NIM_STRLIT_FLAG, "Failures" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_87 = {8, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_86};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_88 = { 4 | NIM_STRLIT_FLAG, "None" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_89 = {4, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_88};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_90 = { 20 | NIM_STRLIT_FLAG, "Invalid enum value: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_91 = {20, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_90};
N_LIB_PRIVATE NIM_CONST tyArray__9aDX30HEqQRuxelTqCRUacw floatFormatToChar__cherZfgehgvyf_u2258 = {103,
102,
101}
;
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4491;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2723;
	framePtr__flfgrz_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2723 = (*framePtr__flfgrz_u2723).prev;
}
static N_INLINE(tyObject_HSlice__D8skNslIDQFiBPOJgPX2UQ, dotdot___fgqZfgeonfvpf_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__D8skNslIDQFiBPOJgPX2UQ result;
	nimfr_("..", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");
	nimlf_(436, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");	result.a = a_p0;
	result.b = b_p1;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__flfgrz_u2441(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4491);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, alignLeft__cherZfgehgvyf_u1162)(NimStringV2 s_p0, NI count_p1, NIM_CHAR padding_p2) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("alignLeft", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1426, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	{
		if (!(s_p0.len < count_p1)) goto LA3_;
		nimln_(1427);		result = mnewString(count_p1);
		nimln_(1428);		{
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_2;
			tyObject_HSlice__D8skNslIDQFiBPOJgPX2UQ T9_;
			if (!(((NI)0) < s_p0.len)) goto LA7_;
			nimln_(1429);			if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) { raiseOverflow(); goto BeforeRet_;
			};
			T9_ = dotdot___fgqZfgeonfvpf_u48(((NI)0), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2));
			X5BX5Deq___cherZfgehgvyf_u1176((&result), T9_, s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA7_: ;
		{
			NI i_1;
			NI colontmp_;
			NI colontmp__2;
			NI i_2;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			colontmp__2 = (NI)0;
			nimlf_(126, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");			nimlf_(1430, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");			colontmp_ = s_p0.len;
			nimlf_(126, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");			nimlf_(1430, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");			colontmp__2 = count_p1;
			nimlf_(128, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");			i_2 = colontmp_;
			{
				nimln_(129);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_3;
					if (!(i_2 < colontmp__2)) goto LA12;
					nimlf_(1430, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");					i_1 = i_2;
					nimln_(1431);					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					result.p->data[i_1] = padding_p2;
					nimlf_(131, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");					if (nimAddInt(i_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_3)) { raiseOverflow(); goto BeforeRet_;
					};
					i_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_3);
				} LA12: ;
			}
		}
	}
	goto LA1_;
LA3_: ;
	{
		nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");		eqcopy___flfgrz_u2690((&result), s_p0);
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatChar)(NIM_CHAR c_p0, NI count_p1) {
	NimStringV2 result;
	nimfr_("repeat", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{	nimlf_(1350, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	result = mnewString(count_p1);
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_4;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");		nimlf_(1351, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");		if (nimSubInt(count_p1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4);
		nimlf_(96, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_5;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(1351, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				i_1 = ((NI) (res_1));
				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				result.p->data[i_1] = c_p0;
				nimlf_(102, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, allCharsInSet__cherZfgehgvyf_u1568)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw theSet_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("allCharsInSet", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	{
		NIM_CHAR c_1;
		NI i_1;
		NI L_1;
		c_1 = (NIM_CHAR)0;
		nimlf_(267, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(268);		L_1 = s_p0.len;
		{
			nimln_(269);			while (1) {
				if (!(i_1 < L_1)) goto LA3;
				nimlf_(1838, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
				}
				c_1 = s_p0.p->data[i_1];
				nimln_(1839);				{
					if (!!(((theSet_p1[(NU)((((NU8)(c_1))))>>3] &(1U<<((NU)((((NU8)(c_1))))&7U)))!=0))) goto LA6_;
					nimln_(1832);					nimln_(1839);					result = NIM_FALSE;
					goto BeforeRet_;
				}
LA6_: ;
				nimlf_(13, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(272);				{
					if (!!((s_p0.len == L_1))) goto LA10_;
					failedAssertImpl__fgqZnffregvbaf_u234(TM__JGc9b9bh2D3nTdUR7TGyq8aA_7);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA10_: ;
			} LA3: ;
		}
	}
	nimlf_(1840, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	nimln_(1832);	nimln_(1840);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, minuspercent___flfgrz_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/arithmetics.nim");
	nimlf_(364, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI length_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_10;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_11;
	nimfr_("find", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimlf_(1971, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	result = ((NI)-1);
	nimln_(1972);	{
		if (!(last_p3 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p0.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p3;
		last_2 = colontmpD__2;
	}
LA1_: ;
	nimln_(1983);	if (nimSubInt(last_2, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_10)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10), ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)) { raiseOverflow(); goto BeforeRet_;
	};
	length_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11);
	nimln_(1984);	{
		void* found_1;
		if (!(((NI)0) < length_1)) goto LA8_;
		nimln_(1985);		if (start_p2 < 0 || start_p2 >= s_p0.len){ raiseIndexError2(start_p2,s_p0.len-1); goto BeforeRet_;
		}
		found_1 = memchr(((void*) ((&s_p0.p->data[start_p2]))), ((int) (((NU8)(sub_p1)))), ((size_t) (length_1)));
		nimln_(1986);		{
			if (!!((found_1 == 0))) goto LA12_;
			nimln_(1987);			nimln_(1959);			nimln_(1987);			result = minuspercent___flfgrz_u813(((NI) (ptrdiff_t) (found_1)), ((NI) (nimToCStringConv(s_p0))));
			goto BeforeRet_;
		}
LA12_: ;
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__flfgrz_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_13;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__flfgrz_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_13)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_13);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__flfgrzZzrzbel_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__flfgrzZzrzbel_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1) {
	NI m_1;
NIM_BOOL* nimErr_;
	nimfr_("initSkipTable", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(1904);	m_1 = sub_p1.len;
	nimln_(1905);	fill__cherZfgehgvyf_u1633(a_p0, 256, m_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_15;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(126, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");		nimlf_(1907, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");		if (nimSubInt(m_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_15)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_15);
		nimlf_(128, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_16;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_17;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_18;
				if (!(i_2 < colontmp_)) goto LA3;
				nimlf_(1907, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				i_1 = i_2;
				nimln_(1908);				if (i_1 < 0 || i_1 >= sub_p1.len){ raiseIndexError2(i_1,sub_p1.len-1); goto BeforeRet_;
				}
				if (nimSubInt(m_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_16)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_16), i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_17)) { raiseOverflow(); goto BeforeRet_;
				};
				a_p0[(((NU8)(sub_p1.p->data[i_1])))- 0] = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_17);
				nimlf_(131, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_18)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_18);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result) {
NIM_BOOL* nimErr_;
	nimfr_("initSkipTable", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1917, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	nsuInitSkipTable(Result, sub_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI subLast_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_19;
	NI skip_1;
	nimfr_("find", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimln_(1931);	{
		if (!(last_p4 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p1.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p4;
		last_2 = colontmpD__2;
	}
LA1_: ;
	nimln_(1932);	if (nimSubInt(sub_p2.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_19)) { raiseOverflow(); goto BeforeRet_;
	};
	subLast_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_19);
	nimln_(1934);	{
		if (!(subLast_1 == ((NI)-1))) goto LA8_;
		nimln_(1937);		nimln_(1919);		nimln_(1937);		result = start_p3;
		goto BeforeRet_;
	}
LA8_: ;
	nimln_(1941);	result = ((NI)-1);
	nimln_(1942);	skip_1 = start_p3;
	{
		nimln_(1944);		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_20;
			NI i_1;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_23;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_24;
			if (nimSubInt(last_2, skip_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_20)) { raiseOverflow(); goto BeforeRet_;
			};
			if (!(subLast_1 <= (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_20))) goto LA11;
			nimln_(1945);			i_1 = subLast_1;
			{
				nimln_(1946);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_21;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_22;
					if (nimAddInt(skip_1, i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_21)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_21) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_21) >= s_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_21),s_p1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= sub_p2.len){ raiseIndexError2(i_1,sub_p2.len-1); goto BeforeRet_;
					}
					if (!((NU8)(s_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_21)]) == (NU8)(sub_p2.p->data[i_1]))) goto LA13;
					nimln_(1947);					{
						if (!(i_1 == ((NI)0))) goto LA16_;
						nimln_(1948);						nimln_(1919);						nimln_(1948);						result = skip_1;
						goto BeforeRet_;
					}
LA16_: ;
					nimln_(1949);					if (nimSubInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_22)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_22);
				} LA13: ;
			}
			nimln_(1950);			if (nimAddInt(skip_1, subLast_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_23)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_23) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_23) >= s_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_23),s_p1.len-1); goto BeforeRet_;
			}
			if (nimAddInt(skip_1, a_p0[(((NU8)(s_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_23)])))- 0], &TM__JGc9b9bh2D3nTdUR7TGyq8aA_24)) { raiseOverflow(); goto BeforeRet_;
			};
			if (TM__JGc9b9bh2D3nTdUR7TGyq8aA_24 < 0 || TM__JGc9b9bh2D3nTdUR7TGyq8aA_24 > IL64(9223372036854775807)){ raiseOverflow(); goto BeforeRet_;
			}
			skip_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_24);
		} LA11: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuReplaceStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NimStringV2 by_p2) {
	NimStringV2 result;
	NI subLen_1;
NIM_BOOL* nimErr_;
	nimfr_("replace", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(2207);	result = TM__JGc9b9bh2D3nTdUR7TGyq8aA_9;
	nimln_(2208);	subLen_1 = sub_p1.len;
	nimln_(2209);	{
		if (!(subLen_1 == ((NI)0))) goto LA3_;
		nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");		eqcopy___flfgrz_u2690((&result), s_p0);
	}
	goto LA1_;
LA3_: ;
	{
		NimStringV2 colontmpD_;
		NIM_CHAR c_1;
		NI last_1;
		NI i_1;
		nimlf_(2211, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");		if (!(subLen_1 == ((NI)1))) goto LA6_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimln_(2214);		if (((NI)0) < 0 || ((NI)0) >= sub_p1.len){ raiseIndexError2(((NI)0),sub_p1.len-1); goto LA8_;
		}
		c_1 = sub_p1.p->data[((NI)0)];
		nimln_(2215);		last_1 = (s_p0.len-1);
		nimln_(2216);		i_1 = ((NI)0);
		{
			nimln_(2217);			while (1) {
				NimStringV2 colontmpD__2;
				NI j_1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_12;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_14;
				colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
				nimln_(2218);				if ((i_1) < ((NI)0) || (i_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(i_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA11_;
				}
				j_1 = nsuFindChar(s_p0, c_1, (i_1), last_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				nimln_(2219);				{
					if (!(j_1 < ((NI)0))) goto LA14_;
					nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");					if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
					nimlf_(2219, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");					goto LA9;
				}
LA14_: ;
				nimln_(2220);				if (nimSubInt(j_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_12)) { raiseOverflow(); goto LA11_;
				};
				colontmpD__2 = substr__flfgrz_u8960(s_p0, i_1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12));
				prepareAdd((&result), colontmpD__2.len + 0);
appendString((&result), colontmpD__2);
				nimln_(2221);				prepareAdd((&result), by_p2.len + 0);
appendString((&result), by_p2);
				nimln_(2222);				if (nimAddInt(j_1, subLen_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_14)) { raiseOverflow(); goto LA11_;
				};
				i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_14);
				{
					LA11_:;
				}
				{
					nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");					if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			}
		} LA9: ;
		nimlf_(2224, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");		colontmpD_ = substr__flfgrz_u8973(s_p0, i_1);
		prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
		{
			LA8_:;
		}
		{
			nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		NimStringV2 colontmpD__3;
		tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_1;
		NI last_2;
		NI i_2;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		nimZeroMem((void*)a_1, sizeof(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ));
		nimlf_(2226, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");		nsuInitNewSkipTable(sub_p1, a_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
		nimln_(2227);		last_2 = (s_p0.len-1);
		nimln_(2228);		i_2 = ((NI)0);
		{
			nimln_(2229);			while (1) {
				NimStringV2 colontmpD__4;
				NI j_2;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_25;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_26;
				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
				nimln_(2230);				if ((i_2) < ((NI)0) || (i_2) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(i_2, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA24_;
				}
				j_2 = nsuFindStrA(a_1, s_p0, sub_p1, (i_2), last_2);
				if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
				nimln_(2231);				{
					if (!(j_2 < ((NI)0))) goto LA27_;
					nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
					nimlf_(2231, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");					goto LA22;
				}
LA27_: ;
				nimln_(2232);				if (nimSubInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_25)) { raiseOverflow(); goto LA24_;
				};
				colontmpD__4 = substr__flfgrz_u8960(s_p0, i_2, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_25));
				prepareAdd((&result), colontmpD__4.len + 0);
appendString((&result), colontmpD__4);
				nimln_(2233);				prepareAdd((&result), by_p2.len + 0);
appendString((&result), by_p2);
				nimln_(2234);				if (nimAddInt(j_2, subLen_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_26)) { raiseOverflow(); goto LA24_;
				};
				i_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_26);
				{
					LA24_:;
				}
				{
					nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
			}
		} LA22: ;
		nimlf_(2236, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");		colontmpD__3 = substr__flfgrz_u8973(s_p0, i_2);
		prepareAdd((&result), colontmpD__3.len + 0);
appendString((&result), colontmpD__3);
		{
			LA21_:;
		}
		{
			nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatBiggestFloat)(NF f_p0, tyEnum_FloatFormatMode__vFVLuA3pnm9aR06Q9cgLgNCg format_p1, NI precision_p2, NIM_CHAR decimalSep_p3) {
	NimStringV2 result;
	tyArray__9bPFPkkEEeeNM9bKgiV8Q49cg frmtstr_1;
	tyArray__Kn8ZOVsorvcNLB4isUeMzQ buf_1;
	int L_1;
	nimfr_("formatBiggestFloat", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	L_1 = (int)0;
	nimlf_(2551, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	frmtstr_1[(((NI)0))- 0] = 37;
	nimln_(2552);	{
		if (!(((NI)0) <= precision_p2)) goto LA3_;
		nimln_(2553);		frmtstr_1[(((NI)1))- 0] = 35;
		nimln_(2554);		frmtstr_1[(((NI)2))- 0] = 46;
		nimln_(2555);		frmtstr_1[(((NI)3))- 0] = 42;
		nimln_(2556);		frmtstr_1[(((NI)4))- 0] = floatFormatToChar__cherZfgehgvyf_u2258[(format_p1)- 0];
		nimln_(2557);		frmtstr_1[(((NI)5))- 0] = 0;
		nimln_(2558);		L_1 = snprintf(((NCSTRING) (buf_1)), ((size_t)2501), ((NCSTRING) (frmtstr_1)), precision_p2, f_p0);
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(2560);		frmtstr_1[(((NI)1))- 0] = floatFormatToChar__cherZfgehgvyf_u2258[(format_p1)- 0];
		nimln_(2561);		frmtstr_1[(((NI)2))- 0] = 0;
		nimln_(2562);		L_1 = snprintf(((NCSTRING) (buf_1)), ((size_t)2501), ((NCSTRING) (frmtstr_1)), f_p0);
	}
LA1_: ;
	nimln_(2563);	if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString(((NI) (L_1)));
	{
		NI32 i_1;
		NI32 res_1;
		i_1 = (NI32)0;
		nimlf_(137, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");		res_1 = ((NI32)0);
		{
			nimln_(138);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_27;
				if (!(res_1 < L_1)) goto LA8;
				nimlf_(2564, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				i_1 = res_1;
				nimln_(2567);				{
					if ((NU)(i_1) > (NU)(2500)){ raiseIndexError2(i_1, 2500); goto BeforeRet_;
					}
					if (!(((NU8)(buf_1[(i_1)- 0])) == ((NU8)(46)) || ((NU8)(buf_1[(i_1)- 0])) == ((NU8)(44)))) goto LA11_;
					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					result.p->data[i_1] = decimalSep_p3;
				}
				goto LA9_;
LA11_: ;
				{
					nimln_(2568);					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if ((NU)(i_1) > (NU)(2500)){ raiseIndexError2(i_1, 2500); goto BeforeRet_;
					}
					result.p->data[i_1] = buf_1[(i_1)- 0];
				}
LA9_: ;
				nimlf_(140, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_27)) { raiseOverflow(); goto BeforeRet_;
				};
				if (TM__JGc9b9bh2D3nTdUR7TGyq8aA_27 < (-2147483647 -1) || TM__JGc9b9bh2D3nTdUR7TGyq8aA_27 > 2147483647){ raiseOverflow(); goto BeforeRet_;
				}
				res_1 = (NI32)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_27);
			} LA8: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatFloat)(NF f_p0, tyEnum_FloatFormatMode__vFVLuA3pnm9aR06Q9cgLgNCg format_p1, NI precision_p2, NIM_CHAR decimalSep_p3) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("formatFloat", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(2598, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	result = nsuformatBiggestFloat(f_p0, format_p1, precision_p2, decimalSep_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuAlignString)(NimStringV2 s_p0, NI count_p1, NIM_CHAR padding_p2) {
	NimStringV2 result;
	nimfr_("align", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimln_(1400);	{
		NI spaces_1;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_28;
		if (!(s_p0.len < count_p1)) goto LA3_;
		nimln_(1401);		result = mnewString(count_p1);
		nimln_(1402);		if (nimSubInt(count_p1, s_p0.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)) { raiseOverflow(); goto BeforeRet_;
		};
		spaces_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28);
		{
			NI i_1;
			NI colontmp_;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_29;
			NI res_1;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(81, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");			nimlf_(1403, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");			if (nimSubInt(spaces_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_29)) { raiseOverflow(); goto BeforeRet_;
			};
			colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_29);
			nimlf_(96, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");			res_1 = ((NI)0);
			{
				nimln_(97);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_30;
					if (!(res_1 <= colontmp_)) goto LA7;
					nimlf_(1403, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");					i_1 = ((NI) (res_1));
					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					result.p->data[i_1] = padding_p2;
					nimlf_(102, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");					if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_30)) { raiseOverflow(); goto BeforeRet_;
					};
					res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_30);
				} LA7: ;
			}
		}
		{
			NI i_2;
			NI colontmp__2;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_31;
			NI res_2;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			nimln_(81);			nimlf_(1404, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");			if (nimSubInt(count_p1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_31)) { raiseOverflow(); goto BeforeRet_;
			};
			colontmp__2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_31);
			nimlf_(96, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");			res_2 = spaces_1;
			{
				nimln_(97);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_32;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_33;
					if (!(res_2 <= colontmp__2)) goto LA10;
					nimlf_(1404, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");					i_2 = ((NI) (res_2));
					if (i_2 < 0 || i_2 >= result.len){ raiseIndexError2(i_2,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if (nimSubInt(i_2, spaces_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32) >= s_p0.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32),s_p0.len-1); goto BeforeRet_;
					}
					result.p->data[i_2] = s_p0.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)];
					nimlf_(102, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");					if (nimAddInt(res_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_33)) { raiseOverflow(); goto BeforeRet_;
					};
					res_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_33);
				} LA10: ;
			}
		}
	}
	goto LA1_;
LA3_: ;
	{
		nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");		eqcopy___flfgrz_u2690((&result), s_p0);
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__cherZfgehgvyf_u2645)(NimStringV2 formatstr_p0) {
	tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ* T1_;
	NimStringV2 T2_;
	nimfr_("invalidFormatString", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ*) nimNewObj(sizeof(tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ), NIM_ALIGNOF(tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__x5fWkS4bHcHaffIXsxxsPQ_);
	(*T1_).Sup.Sup.name = "ValueError";
	nimlf_(2830, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString(formatstr_p0.len + 23);
appendString((&T2_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_38);
appendString((&T2_), formatstr_p0);
	(*T1_).Sup.Sup.message = T2_;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T1_, "ValueError", "invalidFormatString", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim", 2830);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_41;
{	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	if (nimAddInt((*s_p0).len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_41)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_41);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
	}BeforeRet_: ;
}
static N_INLINE(NF, toFloat__flfgrz_u1681)(NI i_p0) {
	NF result;
	nimfr_("toFloat", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");
	nimlf_(1290, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");	result = ((NF) (i_p0));
	popFrame();
	return result;
}
static N_INLINE(NF, abs__flfgrz_u5426)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	NF floatProd_1;
	NF T1_;
	NF T2_;
	NF resAsFloat_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) * (NU64)(((NU) (b_p1))))));
	T1_ = (NF)0;
	T1_ = toFloat__flfgrz_u1681(a_p0);
	T2_ = (NF)0;
	T2_ = toFloat__flfgrz_u1681(b_p1);
	floatProd_1 = ((NF)(T1_) * (NF)(T2_));
	resAsFloat_1 = toFloat__flfgrz_u1681(r_1);
	{
		if (!(resAsFloat_1 == floatProd_1)) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA3_;
LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__flfgrz_u5426(((NF)(resAsFloat_1) - (NF)(floatProd_1)));
			T11_ = (NF)0;
			T11_ = abs__flfgrz_u5426(floatProd_1);
			if (!(((NF)(32.0) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res_p2) = r_1;
		}
		goto LA8_;
LA12_: ;
		{
			result = NIM_TRUE;
		}
LA8_: ;
	}
LA3_: ;
	return result;
}
static N_INLINE(NIM_CHAR, toLowerAscii__fgqZcevingrZfgevzcy_u1)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	nimfr_("toLowerAscii", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/private/strimpl.nim");
{	result = (NIM_CHAR)0;
	nimlf_(2, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/private/strimpl.nim");	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_59;
		if (!(((NU8)(c_p0)) >= ((NU8)(65)) && ((NU8)(c_p0)) <= ((NU8)(90)))) goto LA3_;
		nimln_(3);		if (nimAddInt(((NU8)(c_p0)), ((NI)32), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_59)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_59)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_59)) > ((NI)255)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_59), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result = ((NIM_CHAR) (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_59))));
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(5);		result = c_p0;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NI result;
	NI aLenX60gensym24__1;
	NI bLenX60gensym24__1;
	NI iX60gensym24__1;
	NI jX60gensym24__1;
NIM_BOOL* nimErr_;
	nimfr_("cmpIgnoreStyle", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	aLenX60gensym24__1 = a_p0.len;
	bLenX60gensym24__1 = b_p1.len;
	iX60gensym24__1 = ((NI)0);
	jX60gensym24__1 = ((NI)0);
	{
		while (1) {
			NIM_CHAR colontmpD_;
			NIM_CHAR colontmpD__2;
			NIM_CHAR colontmpD__3;
			NIM_CHAR colontmpD__4;
			NIM_CHAR aaX60gensym24__1;
			NIM_CHAR bbX60gensym24__1;
			colontmpD_ = (NIM_CHAR)0;
			colontmpD__2 = (NIM_CHAR)0;
			colontmpD__3 = (NIM_CHAR)0;
			colontmpD__4 = (NIM_CHAR)0;
			{
				while (1) {
					NIM_BOOL T5_;
					T5_ = (NIM_BOOL)0;
					T5_ = (iX60gensym24__1 < aLenX60gensym24__1);
					if (!(T5_)) goto LA6_;
					T5_ = ((NU8)(a_p0.p->data[iX60gensym24__1]) == (NU8)(95));
LA6_: ;
					if (!T5_) goto LA4;
					iX60gensym24__1 += ((NI)1);
				} LA4: ;
			}
			{
				while (1) {
					NIM_BOOL T9_;
					T9_ = (NIM_BOOL)0;
					T9_ = (jX60gensym24__1 < bLenX60gensym24__1);
					if (!(T9_)) goto LA10_;
					T9_ = ((NU8)(b_p1.p->data[jX60gensym24__1]) == (NU8)(95));
LA10_: ;
					if (!T9_) goto LA8;
					jX60gensym24__1 += ((NI)1);
				} LA8: ;
			}
			{
				if (!(iX60gensym24__1 < aLenX60gensym24__1)) goto LA13_;
				colontmpD_ = toLowerAscii__fgqZcevingrZfgevzcy_u1(a_p0.p->data[iX60gensym24__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				aaX60gensym24__1 = colontmpD_;
			}
			goto LA11_;
LA13_: ;
			{
				colontmpD__2 = 0;
				aaX60gensym24__1 = colontmpD__2;
			}
LA11_: ;
			{
				if (!(jX60gensym24__1 < bLenX60gensym24__1)) goto LA18_;
				colontmpD__3 = toLowerAscii__fgqZcevingrZfgevzcy_u1(b_p1.p->data[jX60gensym24__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				bbX60gensym24__1 = colontmpD__3;
			}
			goto LA16_;
LA18_: ;
			{
				colontmpD__4 = 0;
				bbX60gensym24__1 = colontmpD__4;
			}
LA16_: ;
			result = (NI)(((NU8)(aaX60gensym24__1)) - ((NU8)(bbX60gensym24__1)));
			{
				if (!!((result == ((NI)0)))) goto LA23_;
				goto BeforeRet_;
			}
LA23_: ;
			{
				if (!(aLenX60gensym24__1 <= iX60gensym24__1)) goto LA27_;
				{
					if (!(bLenX60gensym24__1 <= jX60gensym24__1)) goto LA31_;
					result = ((NI)0);
					goto BeforeRet_;
				}
LA31_: ;
				result = ((NI)-1);
				goto BeforeRet_;
			}
			goto LA25_;
LA27_: ;
			{
				if (!(bLenX60gensym24__1 <= jX60gensym24__1)) goto LA34_;
				result = ((NI)1);
				goto BeforeRet_;
			}
			goto LA25_;
LA34_: ;
LA25_: ;
			iX60gensym24__1 += ((NI)1);
			jX60gensym24__1 += ((NI)1);
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__cherZfgehgvyf_u2632)(NimStringV2 x_p0, NimStringV2* inArray_p1, NI inArray_p1Len_0) {
	NI result;
	NI i_1;
NIM_BOOL* nimErr_;
	nimfr_("findNormalized", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(2822, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	i_1 = ((NI)0);
	{
		nimln_(2823);		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_60;
			if (!(i_1 < (inArray_p1Len_0-1))) goto LA2;
			nimln_(2824);			{
				NI T5_;
				if (i_1 < 0 || i_1 >= inArray_p1Len_0){ raiseIndexError2(i_1,inArray_p1Len_0-1); goto BeforeRet_;
				}
				T5_ = (NI)0;
				T5_ = nsuCmpIgnoreStyle(x_p0, inArray_p1[i_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T5_ == ((NI)0))) goto LA6_;
				nimln_(2821);				nimln_(2824);				result = i_1;
				goto BeforeRet_;
			}
LA6_: ;
			nimln_(2825);			if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_60)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_60);
		} LA2: ;
	}
	nimln_(2827);	nimln_(2821);	nimln_(2827);	result = ((NI)-1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringV2* s_p0, NimStringV2 formatstr_p1, NimStringV2* a_p2, NI a_p2Len_0) {
	NI i_1;
	NI num_1;
NIM_BOOL* nimErr_;
	nimfr_("addf", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(2836);	i_1 = ((NI)0);
	nimln_(2837);	num_1 = ((NI)0);
	{
		nimln_(2838);		while (1) {
			if (!(i_1 < formatstr_p1.len)) goto LA2;
			nimln_(2839);			{
				NIM_BOOL T5_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_35;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_36;
				T5_ = (NIM_BOOL)0;
				if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
				}
				T5_ = ((NU8)(formatstr_p1.p->data[i_1]) == (NU8)(36));
				if (!(T5_)) goto LA6_;
				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_35)) { raiseOverflow(); goto BeforeRet_;
				};
				T5_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_35) < formatstr_p1.len);
LA6_: ;
				if (!T5_) goto LA7_;
				nimln_(2840);				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_36)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_36) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_36) >= formatstr_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_36),formatstr_p1.len-1); goto BeforeRet_;
				}
				switch (((NU8)(formatstr_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_36)]))) {
				case 35:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_39;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_40;
					nimln_(2842);					{
						if (!((a_p2Len_0-1) < num_1)) goto LA12_;
						invalidFormatString__cherZfgehgvyf_u2645(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA12_: ;
					nimln_(2843);					if (num_1 < 0 || num_1 >= a_p2Len_0){ raiseIndexError2(num_1,a_p2Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&(*s_p0)), a_p2[num_1].len + 0);
appendString((&(*s_p0)), a_p2[num_1]);
					nimln_(2844);					if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_39)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_39);
					nimln_(2845);					if (nimAddInt(num_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_40)) { raiseOverflow(); goto BeforeRet_;
					};
					num_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_40);
				}
				break;
				case 36:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_42;
					nimln_(2847);					nimAddCharV1((&(*s_p0)), 36);
					nimln_(2848);					if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_42)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_42);
				}
				break;
				case 49 ... 57:
				case 45:
				{
					NI colontmpD_;
					NI colontmpD__2;
					NI j_1;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_43;
					NIM_BOOL negative_1;
					NI idx_1;
					colontmpD_ = (NI)0;
					colontmpD__2 = (NI)0;
					nimln_(2850);					j_1 = ((NI)0);
					nimln_(2851);					if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_43)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_43);
					nimln_(2852);					if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
					}
					negative_1 = ((NU8)(formatstr_p1.p->data[i_1]) == (NU8)(45));
					nimln_(2853);					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_44;
						if (!negative_1) goto LA18_;
						if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_44)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_44);
					}
LA18_: ;
					{
						nimln_(2854);						while (1) {
							NIM_BOOL T22_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_45;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_46;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_47;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_48;
							T22_ = (NIM_BOOL)0;
							T22_ = (i_1 < formatstr_p1.len);
							if (!(T22_)) goto LA23_;
							if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
							}
							T22_ = (((NU8)(formatstr_p1.p->data[i_1])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[i_1])) <= ((NU8)(57)));
LA23_: ;
							if (!T22_) goto LA21;
							nimln_(2855);							if (nimMulInt(j_1, ((NI)10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_45)) { raiseOverflow(); goto BeforeRet_;
							};
							if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
							}
							if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_45), ((NU8)(formatstr_p1.p->data[i_1])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_46)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_46), ((NI)48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_47)) { raiseOverflow(); goto BeforeRet_;
							};
							j_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_47);
							nimln_(2856);							if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_48)) { raiseOverflow(); goto BeforeRet_;
							};
							i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_48);
						} LA21: ;
					}
					nimln_(2857);					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_49;
						if (!!(negative_1)) goto LA26_;
						if (nimSubInt(j_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_49)) { raiseOverflow(); goto BeforeRet_;
						};
						colontmpD_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_49);
						idx_1 = colontmpD_;
					}
					goto LA24_;
LA26_: ;
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_50;
						if (nimSubInt(a_p2Len_0, j_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_50)) { raiseOverflow(); goto BeforeRet_;
						};
						colontmpD__2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_50);
						idx_1 = colontmpD__2;
					}
LA24_: ;
					nimln_(2858);					{
						NIM_BOOL T31_;
						T31_ = (NIM_BOOL)0;
						T31_ = (idx_1 < ((NI)0));
						if (T31_) goto LA32_;
						T31_ = ((a_p2Len_0-1) < idx_1);
LA32_: ;
						if (!T31_) goto LA33_;
						invalidFormatString__cherZfgehgvyf_u2645(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA33_: ;
					nimln_(2859);					if (idx_1 < 0 || idx_1 >= a_p2Len_0){ raiseIndexError2(idx_1,a_p2Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&(*s_p0)), a_p2[idx_1].len + 0);
appendString((&(*s_p0)), a_p2[idx_1]);
				}
				break;
				case 123:
				{
					NI j_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_51;
					NI k_1;
					NIM_BOOL negative_2;
					NI isNumber_1;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_64;
					nimln_(2861);					if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_51)) { raiseOverflow(); goto BeforeRet_;
					};
					j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_51);
					nimln_(2862);					k_1 = ((NI)0);
					nimln_(2863);					if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
					}
					negative_2 = ((NU8)(formatstr_p1.p->data[j_2]) == (NU8)(45));
					nimln_(2864);					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_52;
						if (!negative_2) goto LA38_;
						if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_52)) { raiseOverflow(); goto BeforeRet_;
						};
						j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_52);
					}
LA38_: ;
					nimln_(2865);					isNumber_1 = ((NI)0);
					{
						nimln_(2866);						while (1) {
							NIM_BOOL T42_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_56;
							T42_ = (NIM_BOOL)0;
							T42_ = (j_2 < formatstr_p1.len);
							if (!(T42_)) goto LA43_;
							if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
							}
							T42_ = !((((NU8)(formatstr_p1.p->data[j_2])) == ((NU8)(0)) || ((NU8)(formatstr_p1.p->data[j_2])) == ((NU8)(125))));
LA43_: ;
							if (!T42_) goto LA41;
							nimln_(2867);							{
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_53;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_54;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_55;
								if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
								}
								if (!(((NU8)(formatstr_p1.p->data[j_2])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[j_2])) <= ((NU8)(57)))) goto LA46_;
								nimln_(2868);								if (nimMulInt(k_1, ((NI)10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_53)) { raiseOverflow(); goto BeforeRet_;
								};
								if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
								}
								if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_53), ((NU8)(formatstr_p1.p->data[j_2])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_54)) { raiseOverflow(); goto BeforeRet_;
								};
								if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_54), ((NI)48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_55)) { raiseOverflow(); goto BeforeRet_;
								};
								k_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_55);
								nimln_(2869);								{
									if (!(isNumber_1 == ((NI)0))) goto LA50_;
									isNumber_1 = ((NI)1);
								}
LA50_: ;
							}
							goto LA44_;
LA46_: ;
							{
								nimln_(2871);								isNumber_1 = ((NI)-1);
							}
LA44_: ;
							nimln_(2872);							if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_56)) { raiseOverflow(); goto BeforeRet_;
							};
							j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_56);
						} LA41: ;
					}
					nimln_(2873);					{
						NI colontmpD__3;
						NI colontmpD__4;
						NI idx_2;
						if (!(isNumber_1 == ((NI)1))) goto LA55_;
						colontmpD__3 = (NI)0;
						colontmpD__4 = (NI)0;
						nimln_(2874);						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_57;
							if (!!(negative_2)) goto LA59_;
							if (nimSubInt(k_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_57)) { raiseOverflow(); goto BeforeRet_;
							};
							colontmpD__3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_57);
							idx_2 = colontmpD__3;
						}
						goto LA57_;
LA59_: ;
						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_58;
							if (nimSubInt(a_p2Len_0, k_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_58)) { raiseOverflow(); goto BeforeRet_;
							};
							colontmpD__4 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_58);
							idx_2 = colontmpD__4;
						}
LA57_: ;
						nimln_(2875);						{
							NIM_BOOL T64_;
							T64_ = (NIM_BOOL)0;
							T64_ = (idx_2 < ((NI)0));
							if (T64_) goto LA65_;
							T64_ = ((a_p2Len_0-1) < idx_2);
LA65_: ;
							if (!T64_) goto LA66_;
							invalidFormatString__cherZfgehgvyf_u2645(formatstr_p1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA66_: ;
						nimln_(2876);						if (idx_2 < 0 || idx_2 >= a_p2Len_0){ raiseIndexError2(idx_2,a_p2Len_0-1); goto BeforeRet_;
						}
						prepareAdd((&(*s_p0)), a_p2[idx_2].len + 0);
appendString((&(*s_p0)), a_p2[idx_2]);
					}
					goto LA53_;
LA55_: ;
					{
						NimStringV2 colontmpD__5;
						NI x_1;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_61;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_62;
						colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
						nimln_(2878);						if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)) { raiseOverflow(); goto LA69_;
						};
						if (nimSubInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_62)) { raiseOverflow(); goto LA69_;
						};
						colontmpD__5 = substr__flfgrz_u8960(formatstr_p1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_62));
						x_1 = findNormalized__cherZfgehgvyf_u2632(colontmpD__5, a_p2, a_p2Len_0);
						if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						nimln_(2879);						{
							NIM_BOOL T72_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_63;
							T72_ = (NIM_BOOL)0;
							T72_ = (((NI)0) <= x_1);
							if (!(T72_)) goto LA73_;
							T72_ = (x_1 < (a_p2Len_0-1));
LA73_: ;
							if (!T72_) goto LA74_;
							if (nimAddInt(x_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_63)) { raiseOverflow(); goto LA69_;
							};
							if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_63) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_63) >= a_p2Len_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_63),a_p2Len_0-1); goto LA69_;
							}
							prepareAdd((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_63)].len + 0);
appendString((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_63)]);
						}
						goto LA70_;
LA74_: ;
						{
							nimln_(2880);							invalidFormatString__cherZfgehgvyf_u2645(formatstr_p1);
							if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						}
LA70_: ;
						{
							LA69_:;
						}
						{
							nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");							if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA53_: ;
					nimlf_(2881, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");					if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_64)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_64);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NimStringV2 colontmpD__6;
					NI j_3;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_65;
					NI x_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_67;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_68;
					colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
					nimln_(2883);					if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_65)) { raiseOverflow(); goto LA80_;
					};
					j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_65);
					{
						nimln_(2884);						while (1) {
							NIM_BOOL T83_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_66;
							T83_ = (NIM_BOOL)0;
							T83_ = (j_3 < formatstr_p1.len);
							if (!(T83_)) goto LA84_;
							if (j_3 < 0 || j_3 >= formatstr_p1.len){ raiseIndexError2(j_3,formatstr_p1.len-1); goto LA80_;
							}
							T83_ = (((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(97)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(122)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(65)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(90)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(57)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(128)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(255)) || ((NU8)(formatstr_p1.p->data[j_3])) == ((NU8)(95)));
LA84_: ;
							if (!T83_) goto LA82;
							if (nimAddInt(j_3, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_66)) { raiseOverflow(); goto LA80_;
							};
							j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_66);
						} LA82: ;
					}
					nimln_(2885);					if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_67)) { raiseOverflow(); goto LA80_;
					};
					if (nimSubInt(j_3, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_68)) { raiseOverflow(); goto LA80_;
					};
					colontmpD__6 = substr__flfgrz_u8960(formatstr_p1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_67), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_68));
					x_2 = findNormalized__cherZfgehgvyf_u2632(colontmpD__6, a_p2, a_p2Len_0);
					if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
					nimln_(2886);					{
						NIM_BOOL T87_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_69;
						T87_ = (NIM_BOOL)0;
						T87_ = (((NI)0) <= x_2);
						if (!(T87_)) goto LA88_;
						T87_ = (x_2 < (a_p2Len_0-1));
LA88_: ;
						if (!T87_) goto LA89_;
						if (nimAddInt(x_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_69)) { raiseOverflow(); goto LA80_;
						};
						if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_69) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_69) >= a_p2Len_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_69),a_p2Len_0-1); goto LA80_;
						}
						prepareAdd((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_69)].len + 0);
appendString((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_69)]);
					}
					goto LA85_;
LA89_: ;
					{
						nimln_(2887);						invalidFormatString__cherZfgehgvyf_u2645(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
					}
LA85_: ;
					nimln_(2888);					i_1 = j_3;
					{
						LA80_:;
					}
					{
						nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");						if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				default:
				{
					nimlf_(2890, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");					invalidFormatString__cherZfgehgvyf_u2645(formatstr_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				}
			}
			goto LA3_;
LA7_: ;
			{
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_70;
				nimln_(2892);				if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
				}
				nimAddCharV1((&(*s_p0)), formatstr_p1.p->data[i_1]);
				nimln_(2893);				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_70)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_70);
			}
LA3_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatOpenArray)(NimStringV2 formatstr_p0, NimStringV2* a_p1, NI a_p1Len_0) {
	NimStringV2 result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_34;
NIM_BOOL* nimErr_;
	nimfr_("%", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(2945);	if (nimAddInt(formatstr_p0.len, (NI)((NU64)(a_p1Len_0) << (NU64)(((NI)4))), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString(((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)));
	nimln_(2946);	nsuAddf((&result), formatstr_p0, a_p1, a_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1) {
	NimStringV2 result;
	nimfr_("join", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimln_(1870);	{
		NI L_1;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_71;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_72;
		if (!(((NI)0) < a_p0Len_0)) goto LA3_;
		nimln_(1871);		if (nimSubInt(a_p0Len_0, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_71)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimMulInt(sep_p1.len, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_71), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_72)) { raiseOverflow(); goto BeforeRet_;
		};
		L_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_72);
		{
			NI i_1;
			NI colontmp_;
			NI res_1;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(81, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");			nimlf_(1872, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");			colontmp_ = (a_p0Len_0-1);
			nimlf_(96, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");			res_1 = ((NI)0);
			{
				nimln_(97);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_73;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_74;
					if (!(res_1 <= colontmp_)) goto LA7;
					nimlf_(1872, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");					i_1 = ((NI) (res_1));
					if (i_1 < 0 || i_1 >= a_p0Len_0){ raiseIndexError2(i_1,a_p0Len_0-1); goto BeforeRet_;
					}
					if (nimAddInt(L_1, a_p0[i_1].len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_73)) { raiseOverflow(); goto BeforeRet_;
					};
					L_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_73);
					nimlf_(102, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");					if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_74)) { raiseOverflow(); goto BeforeRet_;
					};
					res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_74);
				} LA7: ;
			}
		}
		nimlf_(1873, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");		if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		result = rawNewString((L_1));
		nimln_(1874);		if (((NI)0) < 0 || ((NI)0) >= a_p0Len_0){ raiseIndexError2(((NI)0),a_p0Len_0-1); goto BeforeRet_;
		}
		prepareAdd((&result), a_p0[((NI)0)].len + 0);
appendString((&result), a_p0[((NI)0)]);
		{
			NI i_2;
			NI colontmp__2;
			NI res_2;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			nimlf_(81, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");			nimlf_(1875, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");			colontmp__2 = (a_p0Len_0-1);
			nimlf_(96, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");			res_2 = ((NI)1);
			{
				nimln_(97);				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_75;
					if (!(res_2 <= colontmp__2)) goto LA10;
					nimlf_(1875, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");					i_2 = ((NI) (res_2));
					nimln_(1876);					prepareAdd((&result), sep_p1.len + 0);
appendString((&result), sep_p1);
					nimln_(1877);					if (i_2 < 0 || i_2 >= a_p0Len_0){ raiseIndexError2(i_2,a_p0Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&result), a_p0[i_2].len + 0);
appendString((&result), a_p0[i_2]);
					nimlf_(102, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");					if (nimAddInt(res_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_75)) { raiseOverflow(); goto BeforeRet_;
					};
					res_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_75);
				} LA10: ;
			}
		}
	}
	goto LA1_;
LA3_: ;
	{
		nimlf_(1879, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");		result = TM__JGc9b9bh2D3nTdUR7TGyq8aA_76;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIdentNormalize__cherZfgehgvyf_u122)(NimStringV2 s_p0) {
	NimStringV2 result;
	NI j_1;
	nimfr_("nimIdentNormalize", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimln_(298);	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	nimln_(299);	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		nimln_(300);		goto BeforeRet_;
	}
LA3_: ;
	nimln_(301);	if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
	}
	nimPrepareStrMutationV2((&result));
	if (((NI)0) < 0 || ((NI)0) >= s_p0.len){ raiseIndexError2(((NI)0),s_p0.len-1); goto BeforeRet_;
	}
	result.p->data[((NI)0)] = s_p0.p->data[((NI)0)];
	nimln_(302);	j_1 = ((NI)1);
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_77;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");		nimlf_(303, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");		if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_77)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_77);
		nimlf_(96, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");		res_1 = ((NI)1);
		{
			nimln_(97);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_81;
				if (!(res_1 <= colontmp_)) goto LA7;
				nimlf_(303, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				i_1 = ((NI) (res_1));
				nimln_(304);				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_78;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_79;
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					if (!(((NU8)(s_p0.p->data[i_1])) >= ((NU8)(65)) && ((NU8)(s_p0.p->data[i_1])) <= ((NU8)(90)))) goto LA10_;
					nimln_(305);					if (j_1 < 0 || j_1 >= result.len){ raiseIndexError2(j_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					if (nimAddInt(((NU8)(s_p0.p->data[i_1])), ((NI)32), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_78)) { raiseOverflow(); goto BeforeRet_;
					};
					if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_78)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_78)) > ((NI)255)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_78), ((NI)0), ((NI)255)); goto BeforeRet_;
					}
					result.p->data[j_1] = ((NIM_CHAR) (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_78))));
					nimln_(306);					if (nimAddInt(j_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_79)) { raiseOverflow(); goto BeforeRet_;
					};
					j_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_79);
				}
				goto LA8_;
LA10_: ;
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_80;
					nimln_(307);					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					if (!!(((NU8)(s_p0.p->data[i_1]) == (NU8)(95)))) goto LA13_;
					nimln_(308);					if (j_1 < 0 || j_1 >= result.len){ raiseIndexError2(j_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					result.p->data[j_1] = s_p0.p->data[i_1];
					nimln_(309);					if (nimAddInt(j_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_80)) { raiseOverflow(); goto BeforeRet_;
					};
					j_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_80);
				}
				goto LA8_;
LA13_: ;
LA8_: ;
				nimlf_(102, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_81)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_81);
			} LA7: ;
		}
	}
	nimlf_(310, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	{
		if (!!((j_1 == s_p0.len))) goto LA17_;
		if ((j_1) < ((NI)0) || (j_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(j_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), (j_1));
	}
LA17_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__flfgrz_u1739)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/strmantle.nim");
{	nimlf_(35, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(36);	alen_1 = a_p0.len;
	nimln_(37);	blen_1 = b_p1.len;
	nimln_(38);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(39);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(34);			nimln_(39);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(40);		nimln_(34);		nimln_(40);		result = equalMem__flfgrz_u1739(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw, parseEnum__cxtZhavggrfg2_u678)(NimStringV2 s_p0) {
	tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw result;
	NimStringV2 colontmpD_;
	tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw colontmpD__2;
	tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw colontmpD__3;
	tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw colontmpD__4;
	tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw colontmpD__5;
NIM_BOOL* nimErr_;
	nimfr_("parseEnum", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = (tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw)0;
	colontmpD__3 = (tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw)0;
	colontmpD__4 = (tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw)0;
	colontmpD__5 = (tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw)0;
	nimlf_(1306, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	nimln_(1323);	nimlf_(28, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/enumutils.nim");	colontmpD_ = nimIdentNormalize__cherZfgehgvyf_u122(s_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_83)) goto LA2_;
	if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_85)) goto LA3_;
	if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_87)) goto LA4_;
	if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_89)) goto LA5_;
	goto LA6_;
	LA2_: ;
	{
		nimlf_(129, "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");		colontmpD__2 = ((tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw)0);
		result = colontmpD__2;
	}
	goto LA7_;
	LA3_: ;
	{
		nimln_(130);		colontmpD__3 = ((tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw)1);
		result = colontmpD__3;
	}
	goto LA7_;
	LA4_: ;
	{
		nimln_(131);		colontmpD__4 = ((tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw)2);
		result = colontmpD__4;
	}
	goto LA7_;
	LA5_: ;
	{
		nimln_(132);		colontmpD__5 = ((tyEnum_OutputLevel__3s727RVUcFa6eaV25pCDGw)3);
		result = colontmpD__5;
	}
	goto LA7_;
	LA6_: ;
	{
		tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ* T13_;
		NimStringV2 T14_;
		T13_ = NIM_NIL;
		T13_ = (tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ*) nimNewObj(sizeof(tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ), NIM_ALIGNOF(tyObject_ValueError__x5fWkS4bHcHaffIXsxxsPQ));
		(*T13_).Sup.Sup.Sup.m_type = (&NTIv2__x5fWkS4bHcHaffIXsxxsPQ_);
		(*T13_).Sup.Sup.name = "ValueError";
		nimlf_(78, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/enumutils.nim");		T14_.len = 0; T14_.p = NIM_NIL;
		T14_ = rawNewString(s_p0.len + 20);
appendString((&T14_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_91);
appendString((&T14_), s_p0);
		(*T13_).Sup.Sup.message = T14_;
		(*T13_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(77);		raiseExceptionEx((Exception*)T13_, "ValueError", "parseEnum", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/enumutils.nim", 77);
goto LA1_;
	}
LA7_: ;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringV2 s_p0, NimStringV2 prefix_p1) {
	NIM_BOOL result;
	NI prefixLenX60gensym144__1;
	NI sLenX60gensym144__1;
	NI iX60gensym144__1;
	nimfr_("startsWith", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{	nimlf_(1646, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	result = NIM_FALSE;
	nimlf_(56, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/private/strimpl.nim");	prefixLenX60gensym144__1 = prefix_p1.len;
	nimln_(57);	sLenX60gensym144__1 = s_p0.len;
	nimln_(58);	iX60gensym144__1 = ((NI)0);
	{
		nimlf_(1647, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_92;
			nimlf_(60, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/private/strimpl.nim");			{
				if (!(prefixLenX60gensym144__1 <= iX60gensym144__1)) goto LA5_;
				nimlf_(1633, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				nimlf_(60, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/private/strimpl.nim");				result = NIM_TRUE;
				goto BeforeRet_;
			}
LA5_: ;
			nimln_(61);			{
				NIM_BOOL T9_;
				T9_ = (NIM_BOOL)0;
				T9_ = (sLenX60gensym144__1 <= iX60gensym144__1);
				if (T9_) goto LA10_;
				if (iX60gensym144__1 < 0 || iX60gensym144__1 >= s_p0.len){ raiseIndexError2(iX60gensym144__1,s_p0.len-1); goto BeforeRet_;
				}
				if (iX60gensym144__1 < 0 || iX60gensym144__1 >= prefix_p1.len){ raiseIndexError2(iX60gensym144__1,prefix_p1.len-1); goto BeforeRet_;
				}
				T9_ = !(((NU8)(s_p0.p->data[iX60gensym144__1]) == (NU8)(prefix_p1.p->data[iX60gensym144__1])));
LA10_: ;
				if (!T9_) goto LA11_;
				nimlf_(1633, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				nimlf_(61, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/private/strimpl.nim");				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA11_: ;
			nimln_(62);			if (nimAddInt(iX60gensym144__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_92)) { raiseOverflow(); goto BeforeRet_;
			};
			iX60gensym144__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_92);
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, substrEq__cherZfgehgvyf_u255)(NimStringV2 s_p0, NI pos_p1, NimStringV2 substr_p2) {
	NIM_BOOL result;
	NIM_BOOL colontmpD_;
	NIM_BOOL colontmpD__2;
	NI length_1;
	nimfr_("substrEq", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{	colontmpD_ = (NIM_BOOL)0;
	colontmpD__2 = (NIM_BOOL)0;
	nimlf_(370, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	length_1 = substr_p2.len;
	nimln_(371);	{
		NI i_1;
		if (!(((NI)0) < length_1)) goto LA3_;
		nimln_(372);		i_1 = ((NI)0);
		{
			nimln_(373);			while (1) {
				NIM_BOOL T7_;
				NIM_BOOL T8_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_93;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_94;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_95;
				T7_ = (NIM_BOOL)0;
				T8_ = (NIM_BOOL)0;
				T8_ = (i_1 < length_1);
				if (!(T8_)) goto LA9_;
				if (nimAddInt(pos_p1, i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_93)) { raiseOverflow(); goto BeforeRet_;
				};
				T8_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_93) < s_p0.len);
LA9_: ;
				T7_ = T8_;
				if (!(T7_)) goto LA10_;
				if (nimAddInt(pos_p1, i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_94)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_94) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_94) >= s_p0.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_94),s_p0.len-1); goto BeforeRet_;
				}
				if (i_1 < 0 || i_1 >= substr_p2.len){ raiseIndexError2(i_1,substr_p2.len-1); goto BeforeRet_;
				}
				T7_ = ((NU8)(s_p0.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_94)]) == (NU8)(substr_p2.p->data[i_1]));
LA10_: ;
				if (!T7_) goto LA6;
				nimln_(374);				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_95)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_95);
			} LA6: ;
		}
		nimln_(375);		colontmpD_ = (i_1 == length_1);
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(376);		colontmpD__2 = NIM_FALSE;
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitString)(NimStringV2 s_p0, NimStringV2 sep_p1, NI maxsplit_p2) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
	nimfr_("split", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(417);	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 xX60gensym69__1;
		NI colontmpD_;
		NI colontmpD__2;
		NI sepLen_1;
		NI lastX60gensym41__1;
		NI splitsX60gensym41__1;
		xX60gensym69__1.len = 0; xX60gensym69__1.p = NIM_NIL;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		nimln_(535);		{
			if (!(sep_p1.len == ((NI)0))) goto LA5_;
			colontmpD_ = ((NI)1);
			sepLen_1 = colontmpD_;
		}
		goto LA3_;
LA5_: ;
		{
			nimln_(536);			colontmpD__2 = sep_p1.len;
			sepLen_1 = colontmpD__2;
		}
LA3_: ;
		nimln_(389);		lastX60gensym41__1 = ((NI)0);
		nimln_(390);		splitsX60gensym41__1 = maxsplit_p2;
		{
			nimln_(537);			while (1) {
				NI firstX60gensym41__1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_97;
				NimStringV2 T19_;
				NimStringV2 blitTmp_1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_98;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_99;
				nimln_(392);				if (!(lastX60gensym41__1 <= s_p0.len)) goto LA9;
				nimln_(393);				firstX60gensym41__1 = lastX60gensym41__1;
				{
					nimln_(394);					while (1) {
						NIM_BOOL T12_;
						NIM_BOOL T14_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_96;
						T12_ = (NIM_BOOL)0;
						T12_ = (lastX60gensym41__1 < s_p0.len);
						if (!(T12_)) goto LA13_;
						T14_ = (NIM_BOOL)0;
						T14_ = substrEq__cherZfgehgvyf_u255(s_p0, lastX60gensym41__1, sep_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
						T12_ = !(T14_);
LA13_: ;
						if (!T12_) goto LA11;
						nimln_(395);						if (nimAddInt(lastX60gensym41__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_96)) { raiseOverflow(); goto LA2_;
						};
						lastX60gensym41__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_96);
					} LA11: ;
				}
				nimln_(396);				{
					if (!(splitsX60gensym41__1 == ((NI)0))) goto LA17_;
					lastX60gensym41__1 = s_p0.len;
				}
LA17_: ;
				nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");				nimlf_(803, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				nimln_(397);				if (nimSubInt(lastX60gensym41__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_97)) { raiseOverflow(); goto LA2_;
				};
				nimln_(803);				T19_.len = 0; T19_.p = NIM_NIL;
				T19_ = substr__flfgrz_u8960(s_p0, firstX60gensym41__1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_97));
				nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");				eqsink___flfgrz_u2696((&xX60gensym69__1), T19_);
				nimlf_(418, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				blitTmp_1 = xX60gensym69__1;
				nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");				eqwasMoved___flfgrz_u2687((&xX60gensym69__1));
				nimlf_(418, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				add__fgqZrahzhgvyf_u70((&result), blitTmp_1);
				nimln_(398);				{
					if (!(splitsX60gensym41__1 == ((NI)0))) goto LA22_;
					goto LA8;
				}
LA22_: ;
				nimln_(399);				if (nimSubInt(splitsX60gensym41__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_98)) { raiseOverflow(); goto LA2_;
				};
				splitsX60gensym41__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_98);
				nimln_(400);				if (nimAddInt(lastX60gensym41__1, sepLen_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_99)) { raiseOverflow(); goto LA2_;
				};
				lastX60gensym41__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_99);
			} LA9: ;
		} LA8: ;
		{
			LA2_:;
		}
		{
			nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");			if (xX60gensym69__1.p && !(xX60gensym69__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(xX60gensym69__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitChar)(NimStringV2 s_p0, NIM_CHAR sep_p1, NI maxsplit_p2) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
	nimfr_("split", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(417, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 xX60gensym67__1;
		NI lastX60gensym34__1;
		NI splitsX60gensym34__1;
		xX60gensym67__1.len = 0; xX60gensym67__1.p = NIM_NIL;
		nimln_(389);		lastX60gensym34__1 = ((NI)0);
		nimln_(390);		splitsX60gensym34__1 = maxsplit_p2;
		{
			nimln_(449);			while (1) {
				NI firstX60gensym34__1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_101;
				NimStringV2 T13_;
				NimStringV2 blitTmp_1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_102;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_103;
				nimln_(392);				if (!(lastX60gensym34__1 <= s_p0.len)) goto LA4;
				nimln_(393);				firstX60gensym34__1 = lastX60gensym34__1;
				{
					nimln_(394);					while (1) {
						NIM_BOOL T7_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_100;
						T7_ = (NIM_BOOL)0;
						T7_ = (lastX60gensym34__1 < s_p0.len);
						if (!(T7_)) goto LA8_;
						if (lastX60gensym34__1 < 0 || lastX60gensym34__1 >= s_p0.len){ raiseIndexError2(lastX60gensym34__1,s_p0.len-1); goto LA2_;
						}
						T7_ = !(((NU8)(s_p0.p->data[lastX60gensym34__1]) == (NU8)(sep_p1)));
LA8_: ;
						if (!T7_) goto LA6;
						nimln_(395);						if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_100)) { raiseOverflow(); goto LA2_;
						};
						lastX60gensym34__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_100);
					} LA6: ;
				}
				nimln_(396);				{
					if (!(splitsX60gensym34__1 == ((NI)0))) goto LA11_;
					lastX60gensym34__1 = s_p0.len;
				}
LA11_: ;
				nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");				nimlf_(759, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				nimln_(397);				if (nimSubInt(lastX60gensym34__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_101)) { raiseOverflow(); goto LA2_;
				};
				nimln_(759);				T13_.len = 0; T13_.p = NIM_NIL;
				T13_ = substr__flfgrz_u8960(s_p0, firstX60gensym34__1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_101));
				nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");				eqsink___flfgrz_u2696((&xX60gensym67__1), T13_);
				nimlf_(418, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				blitTmp_1 = xX60gensym67__1;
				nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");				eqwasMoved___flfgrz_u2687((&xX60gensym67__1));
				nimlf_(418, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				add__fgqZrahzhgvyf_u70((&result), blitTmp_1);
				nimln_(398);				{
					if (!(splitsX60gensym34__1 == ((NI)0))) goto LA16_;
					goto LA3;
				}
LA16_: ;
				nimln_(399);				if (nimSubInt(splitsX60gensym34__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_102)) { raiseOverflow(); goto LA2_;
				};
				splitsX60gensym34__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_102);
				nimln_(400);				if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_103)) { raiseOverflow(); goto LA2_;
				};
				lastX60gensym34__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_103);
			} LA4: ;
		} LA3: ;
		{
			LA2_:;
		}
		{
			nimlf_(394, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");			if (xX60gensym67__1.p && !(xX60gensym67__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(xX60gensym67__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringV2 s_p0, NimStringV2 suffix_p1) {
	NIM_BOOL result;
	NI suffixLenX60gensym151__1;
	NI sLenX60gensym151__1;
	NI iX60gensym151__1;
	NI jX60gensym151__1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_104;
	nimfr_("endsWith", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");
{	nimlf_(1675, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	result = NIM_FALSE;
	nimlf_(65, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/private/strimpl.nim");	suffixLenX60gensym151__1 = suffix_p1.len;
	nimln_(66);	sLenX60gensym151__1 = s_p0.len;
	nimln_(67);	iX60gensym151__1 = ((NI)0);
	nimln_(68);	if (nimSubInt(sLenX60gensym151__1, suffixLenX60gensym151__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_104)) { raiseOverflow(); goto BeforeRet_;
	};
	jX60gensym151__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_104);
	{
		nimln_(69);		while (1) {
			NIM_BOOL T3_;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_105;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_106;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_108;
			T3_ = (NIM_BOOL)0;
			if (nimAddInt(iX60gensym151__1, jX60gensym151__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_105)) { raiseOverflow(); goto BeforeRet_;
			};
			T3_ = (((NI)0) <= (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_105));
			if (!(T3_)) goto LA4_;
			if (nimAddInt(iX60gensym151__1, jX60gensym151__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_106)) { raiseOverflow(); goto BeforeRet_;
			};
			T3_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_106) < sLenX60gensym151__1);
LA4_: ;
			if (!T3_) goto LA2;
			nimln_(70);			{
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_107;
				if (nimAddInt(iX60gensym151__1, jX60gensym151__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_107)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_107) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_107) >= s_p0.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_107),s_p0.len-1); goto BeforeRet_;
				}
				if (iX60gensym151__1 < 0 || iX60gensym151__1 >= suffix_p1.len){ raiseIndexError2(iX60gensym151__1,suffix_p1.len-1); goto BeforeRet_;
				}
				if (!!(((NU8)(s_p0.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_107)]) == (NU8)(suffix_p1.p->data[iX60gensym151__1])))) goto LA7_;
				nimlf_(1662, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");				nimlf_(70, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/private/strimpl.nim");				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA7_: ;
			nimln_(71);			if (nimAddInt(iX60gensym151__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_108)) { raiseOverflow(); goto BeforeRet_;
			};
			iX60gensym151__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_108);
		} LA2: ;
	}
	nimlf_(1676, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");	{
		nimlf_(72, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/private/strimpl.nim");		if (!(suffixLenX60gensym151__1 <= iX60gensym151__1)) goto LA11_;
		nimlf_(1662, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/pure/strutils.nim");		nimlf_(72, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/private/strimpl.nim");		result = NIM_TRUE;
		goto BeforeRet_;
	}
LA11_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
