{.passC: staticExec("pkg-config --cflags libnftnl").}
{.passL: staticExec("pkg-config --libs   libnftnl").}

# low-level generated bindings
import nftnl/autogenerated/generated_nftnl as gen_nftnl
import nfq/autogenerated/generated_nfq as gen_nfq
export gen_nftnl, gen_nfq

# core wrappers
import nftnl/core/basics
import nftnl/core/iterators
export basics, iterators

# attrs sugar
import nftnl/attrs/tableAttrs
export tableAttrs

# dot props
import nftnl/props/tableProps
export tableProps
