{.passC: staticExec("pkg-config --cflags libnftnl").}
{.passL: staticExec("pkg-config --libs   libnftnl").}

# low-level generated bindings
import nftnl/autogenerated/generated_nftnl as gen_nftnl
import nfq/autogenerated/generated_nfq as gen_nfq
export gen_nftnl, gen_nfq

# high-level wrappers
import nftnl/basics
import nftnl/iterators
import nftnl/attrs

export basics, iterators, attrs
