{.warning[UnusedImport]: off.}

{.passC: staticExec("pkg-config --cflags libnftnl").}
{.passL: staticExec("pkg-config --libs   libnftnl").}

import nftnl/autogenerated/generated_nftnl as gen_nftnl
import linux/autogenerated/generated_linux as gen_linux
export gen_nftnl, gen_linux

import nftnl/raii/[basics, iterators, expresions]
import nftnl/attrs/[table, chain, rule]
import nftnl/attrs/expr/[cmp, payload]
import messageBuilder

export basics, iterators, expresions, table, chain, rule, cmp, payload, messageBuilder
