import ../raii/basics
import ../attrs/exprAttrsCoersion
import ../autogenerated/generated_nftnl
import ../contracts/expr

template defExprProp(kind: static[string], attr: static[int], propName: untyped) =
  proc propName*(e: Expression): expectedType(kind, attr) =
    attrOp(e, kind, attr)

  proc `propName=`*(e: Expression, v: expectedType(kind, attr)) =
    attrOp(e, kind, attr, v)

# cmp
defExprProp("cmp", int(NFTNL_EXPR_CMP_OP), op)
defExprProp("cmp", int(NFTNL_EXPR_CMP_SREG), sreg)
defExprProp("cmp", int(NFTNL_EXPR_CMP_DATA), data)

# payload
defExprProp("payload", int(NFTNL_EXPR_PAYLOAD_BASE), base)
defExprProp("payload", int(NFTNL_EXPR_PAYLOAD_OFFSET), offset)
defExprProp("payload", int(NFTNL_EXPR_PAYLOAD_LEN), len)

# meta
defExprProp("meta", int(NFTNL_EXPR_META_KEY), key)
defExprProp("meta", int(NFTNL_EXPR_META_DREG), dreg)
