import ../raii/basics
import ../attrs/ruleAttrsCoersion
import ../autogenerated/generated_nftnl
import ../contracts/rule

template defRuleProp(attr: static enum_nftnl_rule_attr, propName: untyped) =
  proc propName*(r: Rule): expectedType(attr) =
    r.getAttr(attr)

  proc `propName=`*(r: Rule, v: expectedType(attr)) =
    r.setAttr(attr, v)

# --- String properties ---
defRuleProp(NFTNL_RULE_TABLE, table)
defRuleProp(NFTNL_RULE_CHAIN, chain)
defRuleProp(NFTNL_RULE_USERDATA, userdata)

# --- uint32 properties ---
defRuleProp(NFTNL_RULE_FAMILY, family)
defRuleProp(NFTNL_RULE_COMPAT_PROTO, compatProto)
defRuleProp(NFTNL_RULE_COMPAT_FLAGS, compatFlags)

# --- uint64 properties ---
defRuleProp(NFTNL_RULE_HANDLE, handle)
