import ../core/basics
import ../attrs/tableAttrs
import ../autogenerated/generated_nftnl

# Dot-properties for Table. Thin sugar on top of attrs.

proc name*(t: Table): string =
  t.getAttr(NFTNL_TABLE_NAME)

proc `name=`*(t: Table, v: string) =
  t.setAttr(NFTNL_TABLE_NAME, v)

proc family*(t: Table): uint32 =
  t.getAttr(NFTNL_TABLE_FAMILY)

proc `family=`*(t: Table, v: SomeInteger) =
  # Normalize all ints → uint32
  t.setAttr(NFTNL_TABLE_FAMILY, v.uint32)

proc flags*(t: Table): uint32 =
  t.getAttr(NFTNL_TABLE_FLAGS)

proc `flags=`*(t: Table, v: SomeInteger) =
  # Normalize all ints → uint32
  t.setAttr(NFTNL_TABLE_FLAGS, v.uint32)

proc handle*(t: Table): uint64 =
  t.getAttr(NFTNL_TABLE_HANDLE)

proc `handle=`*(t: Table, v: SomeInteger) =
  # Normalize all ints → uint64
  t.setAttr(NFTNL_TABLE_HANDLE, v.uint64)

proc userdata*(t: Table): string =
  t.getAttr(NFTNL_TABLE_USERDATA)

proc `userdata=`*(t: Table, v: string) =
  t.setAttr(NFTNL_TABLE_USERDATA, v)

proc owner*(t: Table): string =
  t.getAttr(NFTNL_TABLE_OWNER)

proc `owner=`*(t: Table, v: string) =
  t.setAttr(NFTNL_TABLE_OWNER, v)
