import ../raii/basics
import ../attrs/tableAttrsCoersion
import ../autogenerated/generated_nftnl
import ../contracts/table

template defTableProp(attr: static enum_nftnl_table_attr, propName: untyped) =
  proc propName*(t: Table): expectedType(attr) =
    t.getAttr(attr)

  proc `propName=`*(t: Table, v: expectedType(attr)) =
    t.setAttr(attr, v)

# String properties
defTableProp(NFTNL_TABLE_NAME, name)
defTableProp(NFTNL_TABLE_USERDATA, userdata)
defTableProp(NFTNL_TABLE_OWNER, owner)

# uint32 properties
defTableProp(NFTNL_TABLE_FAMILY, family)
defTableProp(NFTNL_TABLE_FLAGS, flags)

# uint64 properties
defTableProp(NFTNL_TABLE_HANDLE, handle)
