/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/test_all.nim_4a8a08f09d37b73795649038408b5f33/@z..@ffep@fasgay@fenvv@frkcerfvbaf.nim.c.o /home/becker/projects/libnet/nimcache/tests/test_all.nim_4a8a08f09d37b73795649038408b5f33/@z..@ffep@fasgay@fenvv@frkcerfvbaf.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ;
typedef struct tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ {
	tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg* raw;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg {
	char dummy;
};
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__flfgrzZzrzbel_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ, create__pber95grfg95rkce_u120)(NimStringV2 kind_p1);
N_CDECL(tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg*, nftnl_expr_alloc)(NU8* name_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_CDECL(void, nftnl_expr_free)(tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg* expr_p0);
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__UjcwMpKWbFvLbWdEpMNnyw_2 = { 3 | NIM_STRLIT_FLAG, "cmp" };
static const NimStringV2 TM__UjcwMpKWbFvLbWdEpMNnyw_3 = {3, (NimStrPayload*)&TM__UjcwMpKWbFvLbWdEpMNnyw_2};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__UjcwMpKWbFvLbWdEpMNnyw_4 = { 7 | NIM_STRLIT_FLAG, "payload" };
static const NimStringV2 TM__UjcwMpKWbFvLbWdEpMNnyw_5 = {7, (NimStrPayload*)&TM__UjcwMpKWbFvLbWdEpMNnyw_4};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4491;
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2723;
static N_INLINE(void, nimSetMem__flfgrzZzrzbel_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4491);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__flfgrzZzrzbel_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2723;
	framePtr__flfgrz_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2723 = (*framePtr__flfgrz_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ, create__pber95grfg95rkce_u120)(NimStringV2 kind_p1) {
	tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ result;
	nimfr_("create", "/home/becker/projects/libnet/src/nftnl/raii/expresions.nim");
	nimlf_(15, "/home/becker/projects/libnet/src/nftnl/raii/expresions.nim");	result.raw = nftnl_expr_alloc(((NU8*) (nimToCStringConv(kind_p1))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ, create__pber95grfg95rkce_u116)(void) {
	tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ result;
NIM_BOOL* nimErr_;
	nimfr_("create", "/home/becker/projects/libnet/src/nftnl/raii/expresions.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ));
	nimln_(48);	result = create__pber95grfg95rkce_u120(TM__UjcwMpKWbFvLbWdEpMNnyw_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfepZasgayZenvvZrkcerfvbaf_u9)(tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ* x_p0) {
	nimfr_("=destroy", "/home/becker/projects/libnet/src/nftnl/raii/expresions.nim");
	nimln_(18);	{
		if (!!(((*x_p0).raw == ((tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg*) NIM_NIL)))) goto LA3_;
		nimln_(19);		nftnl_expr_free((*x_p0).raw);
		nimln_(20);		(*x_p0).raw = ((tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg*) NIM_NIL);
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZfepZasgayZenvvZrkcerfvbaf_u34)(tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ* x_p0) {
	nimfr_("=wasMoved", "/home/becker/projects/libnet/src/nftnl/raii/expresions.nim");
	nimln_(23);	(*x_p0).raw = ((tyObject_struct_nftnl_expr__vGRKjOGw44XqPCHdpX8LGg*) NIM_NIL);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ, create__pber95grfg95cnlybnq_u128)(void) {
	tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ result;
NIM_BOOL* nimErr_;
	nimfr_("create", "/home/becker/projects/libnet/src/nftnl/raii/expresions.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ));
	nimln_(51);	result = create__pber95grfg95rkce_u120(TM__UjcwMpKWbFvLbWdEpMNnyw_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ, toExpression__OOZfepZasgayZenvvZrkcerfvbaf_u91)(tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ e_p0) {
	tyObject_Expression__3IRDJgTuB9b2DXuyXjQ9aSMQ result;
	nimfr_("toExpression", "/home/becker/projects/libnet/src/nftnl/raii/expresions.nim");
	nimln_(64);	result = e_p0;
	popFrame();
	return result;
}
