/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/test_all.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@ffgq@fraiinef.nim.c.o /home/becker/projects/libnet/nimcache/tests/test_all.nim_4a8a08f09d37b73795649038408b5f33/@z..@f..@f..@f..@f..@favk@ffgber@fuwq6mf0x1s87oymcm2ad9lfsc3zppqof-avz-hajenccrq-2.2.4@favz@fyvo@ffgq@fraiinef.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
static N_INLINE(NIM_BOOL, eqeq___flfgrz_u8925)(NCSTRING x_p0, NCSTRING y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NCSTRING, getEnvImpl__fgqZraiinef_u12)(NCSTRING env_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___flfgrz_u2690)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
extern NCSTRING* environ;
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4491;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2723;
	framePtr__flfgrz_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2723 = (*framePtr__flfgrz_u2723).prev;
}
static N_INLINE(NIM_BOOL, eqeq___flfgrz_u8925)(NCSTRING x_p0, NCSTRING y_p1) {
	NIM_BOOL result;
	nimfr_("==", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");
	nimlf_(2729, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");	{
		if (!(((void*) (x_p0)) == ((void*) (y_p1)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(2730);		T6_ = (NIM_BOOL)0;
		T6_ = (((void*) (x_p0)) == NIM_NIL);
		if (T6_) goto LA7_;
		T6_ = (((void*) (y_p1)) == NIM_NIL);
LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
LA8_: ;
	{
		int T11_;
		nimln_(2731);		T11_ = (int)0;
		T11_ = strcmp(x_p0, y_p1);
		result = (T11_ == ((NI32)0));
	}
LA1_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NCSTRING, getEnvImpl__fgqZraiinef_u12)(NCSTRING env_p0) {
	NCSTRING result;
	nimfr_("getEnvImpl", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/envvars.nim");
	result = getenv(env_p0);
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4491);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, existsEnv__fgqZraiinef_u20)(NimStringV2 key_p0) {
	NIM_BOOL result;
	NCSTRING T1_;
	NIM_BOOL T2_;
NIM_BOOL* nimErr_;
	nimfr_("existsEnv", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/envvars.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(117, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/envvars.nim");	T1_ = (NCSTRING)0;
	T1_ = getEnvImpl__fgqZraiinef_u12(nimToCStringConv(key_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (NIM_BOOL)0;
	T2_ = eqeq___flfgrz_u8925(T1_, ((NCSTRING) NIM_NIL));
	result = !(T2_);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__fgqZraiinef_u15)(NimStringV2 key_p0, NimStringV2 default_p1) {
	NimStringV2 result;
	NCSTRING env_1;
NIM_BOOL* nimErr_;
	nimfr_("getEnv", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/envvars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(99);	env_1 = getEnvImpl__fgqZraiinef_u12(nimToCStringConv(key_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(100);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq___flfgrz_u8925(env_1, ((NCSTRING) NIM_NIL));
		if (!T3_) goto LA4_;
		nimlf_(1694, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system.nim");		eqcopy___flfgrz_u2690((&result), default_p1);
	}
	goto LA1_;
LA4_: ;
	{
		nimlf_(103, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/std/envvars.nim");		result = cstrToNimstr(env_1);
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
