/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, arm64, gcc */
/* Command for C compiler:
   gcc -c -w -fmax-errors=3 -pthread -I/nix/store/sxyzg0vgfqrslaxdlbygi9qd8ccc7rf1-libnftnl-1.3.0/include   -I/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib -I/home/becker/projects/libnet/tests -o /home/becker/projects/libnet/nimcache/tests/test_all.nim_4a8a08f09d37b73795649038408b5f33/@zgrfg_nyy.nim.c.o /home/becker/projects/libnet/nimcache/tests/test_all.nim_4a8a08f09d37b73795649038408b5f33/@zgrfg_nyy.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg;
typedef struct tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_TestResult__ymAJhTojpKPCdtwtBDuRDw tyObject_TestResult__ymAJhTojpKPCdtwtBDuRDw;
typedef struct tyObject_Duration__GaviyXSk1feY9caubDtFrJQ tyObject_Duration__GaviyXSk1feY9caubDtFrJQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg {
	RootObj Sup;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
typedef NU8 tyEnum_TestStatus__THjkjgu1Bp8P2bEiBquXDw;
struct tyObject_Duration__GaviyXSk1feY9caubDtFrJQ {
	NI64 seconds;
	NI nanosecond;
};
struct tyObject_TestResult__ymAJhTojpKPCdtwtBDuRDw {
	NimStringV2 suiteName;
	NimStringV2 testName;
	tyEnum_TestStatus__THjkjgu1Bp8P2bEiBquXDw status;
	tyObject_Duration__GaviyXSk1feY9caubDtFrJQ duration;
	NimStringV2 output;
	NimStringV2 errors;
};
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, chckNilDisp)(void* p_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__cxtZhavggrfg2_u1942)(tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg* formatter_p0, NimStringV2 suiteName_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseObjectConversionError)(void);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__cxtZhavggrfg2_u770)(tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ* formatter_p0, NimStringV2 suiteName_p1);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__cxtZhavggrfg2_u105)(tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg* formatter_p0, NimStringV2 suiteName_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__cxtZhavggrfg2_u1968)(tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg* formatter_p0, NimStringV2 testName_p1);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__cxtZhavggrfg2_u822)(tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ* formatter_p0, NimStringV2 testName_p1);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__cxtZhavggrfg2_u109)(tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg* formatter_p0, NimStringV2 testName_p1);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__cxtZhavggrfg2_u1991)(tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__cxtZhavggrfg2_u837)(tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__cxtZhavggrfg2_u113)(tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__cxtZhavggrfg2_u2090)(tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg* formatter_p0, tyObject_TestResult__ymAJhTojpKPCdtwtBDuRDw* testResult_p1);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__cxtZhavggrfg2_u901)(tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ* formatter_p0, tyObject_TestResult__ymAJhTojpKPCdtwtBDuRDw* testResult_p1);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__cxtZhavggrfg2_u118)(tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg* formatter_p0, tyObject_TestResult__ymAJhTojpKPCdtwtBDuRDw* testResult_p1);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__cxtZhavggrfg2_u2097)(tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__cxtZhavggrfg2_u970)(tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__cxtZhavggrfg2_u122)(tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, testRunEnded__cxtZhavggrfg2_u2330)(tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, testRunEnded__cxtZhavggrfg2_u1079)(tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, testRunEnded__cxtZhavggrfg2_u125)(tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, atzdotdotatfdotdotatfdotdotatfdotdotatfdotdotatfavkatffgberatfuwq6mf0x1s87oymcm2ad9lfsc3zppqofminusavzminushajenccrqminus2dot2dot4atfavzatfyvoatfflfgrzdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atzdotdotatfdotdotatfdotdotatfdotdotatfdotdotatfavkatffgberatfuwq6mf0x1s87oymcm2ad9lfsc3zppqofminusavzminushajenccrqminus2dot2dot4atfavzatfyvoatffgqatfrkvgcebpfdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atzdotdotatfdotdotatfdotdotatfdotavzoyratfcxtf2atfhavggrfg2minus0dot2dot4minus746106n4qsrssspr497s1693733s1p1513o5p62patfhavggrfg2dotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atzpber_grfg_punvadotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atzpber_grfg_rkcedotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atzvagrtengvba_grfg_ohvyq_cnlybnqdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atzpber_grfg_cnlybnqdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atzpber_grfg_envvdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atzpber_grfg_ehyrdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atzvagrtengvba_grfg_facevagsdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atzpber_grfg_gnoyrdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4491;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2723;
	framePtr__flfgrz_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2723 = (*framePtr__flfgrz_u2723).prev;
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isObjDisplayCheck", "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/arc.nim");
	nimlf_(266, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/arc.nim");	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4491);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__cxtZhavggrfg2_u108)(tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg* formatter_p0, NimStringV2 suiteName_p1) {
NIM_BOOL* nimErr_;
	nimfr_("suiteStarted", "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(114, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/chcks.nim");	chckNilDisp(formatter_p0);
	nimlf_(296, "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 4099370240)))) goto LA3_;
		if (formatter_p0 && !isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 4099370240)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		suiteStarted__cxtZhavggrfg2_u1942(((tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg*) (formatter_p0)), suiteName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 1784452352)))) goto LA6_;
		if (formatter_p0 && !isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 1784452352)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		suiteStarted__cxtZhavggrfg2_u770(((tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ*) (formatter_p0)), suiteName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 1, 2480918016)))) goto LA9_;
		suiteStarted__cxtZhavggrfg2_u105(formatter_p0, suiteName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testStarted__cxtZhavggrfg2_u112)(tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg* formatter_p0, NimStringV2 testName_p1) {
NIM_BOOL* nimErr_;
	nimfr_("testStarted", "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(114, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/chcks.nim");	chckNilDisp(formatter_p0);
	nimlf_(298, "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 4099370240)))) goto LA3_;
		if (formatter_p0 && !isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 4099370240)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		testStarted__cxtZhavggrfg2_u1968(((tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg*) (formatter_p0)), testName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 1784452352)))) goto LA6_;
		if (formatter_p0 && !isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 1784452352)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		testStarted__cxtZhavggrfg2_u822(((tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ*) (formatter_p0)), testName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 1, 2480918016)))) goto LA9_;
		testStarted__cxtZhavggrfg2_u109(formatter_p0, testName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__cxtZhavggrfg2_u117)(tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2) {
NIM_BOOL* nimErr_;
	nimfr_("failureOccurred", "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(114, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/chcks.nim");	chckNilDisp(formatter_p0);
	nimlf_(300, "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 4099370240)))) goto LA3_;
		if (formatter_p0 && !isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 4099370240)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		failureOccurred__cxtZhavggrfg2_u1991(((tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg*) (formatter_p0)), checkpoints_p1, stackTrace_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 1784452352)))) goto LA6_;
		if (formatter_p0 && !isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 1784452352)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		failureOccurred__cxtZhavggrfg2_u837(((tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ*) (formatter_p0)), checkpoints_p1, stackTrace_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 1, 2480918016)))) goto LA9_;
		failureOccurred__cxtZhavggrfg2_u113(formatter_p0, checkpoints_p1, stackTrace_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testEnded__cxtZhavggrfg2_u121)(tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg* formatter_p0, tyObject_TestResult__ymAJhTojpKPCdtwtBDuRDw* testResult_p1) {
NIM_BOOL* nimErr_;
	nimfr_("testEnded", "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(114, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/chcks.nim");	chckNilDisp(formatter_p0);
	nimlf_(305, "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 4099370240)))) goto LA3_;
		if (formatter_p0 && !isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 4099370240)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		testEnded__cxtZhavggrfg2_u2090(((tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg*) (formatter_p0)), testResult_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 1784452352)))) goto LA6_;
		if (formatter_p0 && !isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 1784452352)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		testEnded__cxtZhavggrfg2_u901(((tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ*) (formatter_p0)), testResult_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 1, 2480918016)))) goto LA9_;
		testEnded__cxtZhavggrfg2_u118(formatter_p0, testResult_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__cxtZhavggrfg2_u124)(tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg* formatter_p0) {
NIM_BOOL* nimErr_;
	nimfr_("suiteEnded", "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(114, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/chcks.nim");	chckNilDisp(formatter_p0);
	nimlf_(307, "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 4099370240)))) goto LA3_;
		if (formatter_p0 && !isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 4099370240)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		suiteEnded__cxtZhavggrfg2_u2097(((tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg*) (formatter_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 1784452352)))) goto LA6_;
		if (formatter_p0 && !isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 1784452352)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		suiteEnded__cxtZhavggrfg2_u970(((tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ*) (formatter_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 1, 2480918016)))) goto LA9_;
		suiteEnded__cxtZhavggrfg2_u122(formatter_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, testRunEnded__cxtZhavggrfg2_u127)(tyObject_OutputFormattercolonObjectType___fpPfzkPttnPMTNAL7GeBwg* formatter_p0) {
NIM_BOOL* nimErr_;
	nimfr_("testRunEnded", "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(114, "/nix/store/hjd6zs0k1f87blzpz2nq9ysfp3mccdbs-nim-unwrapped-2.2.4/nim/lib/system/chcks.nim");	chckNilDisp(formatter_p0);
	nimlf_(314, "/home/becker/.nimble/pkgs2/unittest2-0.2.4-746106a4dfefffce497f1693733f1c1513b5c62c/unittest2.nim");	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 4099370240)))) goto LA3_;
		if (formatter_p0 && !isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 4099370240)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		testRunEnded__cxtZhavggrfg2_u2330(((tyObject_JUnitOutputFormattercolonObjectType___BvRXbXJyvOJyOCtMs5xQsg*) (formatter_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 1784452352)))) goto LA6_;
		if (formatter_p0 && !isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 1784452352)){ raiseObjectConversionError(); goto BeforeRet_;
		}
		testRunEnded__cxtZhavggrfg2_u1079(((tyObject_ConsoleOutputFormattercolonObjectType___UmpclRO8Oigpj2DW9c7lyaQ*) (formatter_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 1, 2480918016)))) goto LA9_;
		testRunEnded__cxtZhavggrfg2_u125(formatter_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE void PreMainInner(void) {
	atzdotdotatfdotdotatfdotdotatfdotdotatfdotdotatfavkatffgberatfuwq6mf0x1s87oymcm2ad9lfsc3zppqofminusavzminushajenccrqminus2dot2dot4atfavzatfyvoatffgqatfrkvgcebpfdotnim_Init000();
	atzdotdotatfdotdotatfdotdotatfdotavzoyratfcxtf2atfhavggrfg2minus0dot2dot4minus746106n4qsrssspr497s1693733s1p1513o5p62patfhavggrfg2dotnim_Init000();
	atzpber_grfg_punvadotnim_Init000();
	atzpber_grfg_rkcedotnim_Init000();
	atzvagrtengvba_grfg_ohvyq_cnlybnqdotnim_Init000();
	atzpber_grfg_cnlybnqdotnim_Init000();
	atzpber_grfg_envvdotnim_Init000();
	atzpber_grfg_ehyrdotnim_Init000();
	atzvagrtengvba_grfg_facevagsdotnim_Init000();
	atzpber_grfg_gnoyrdotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atzdotdotatfdotdotatfdotdotatfdotdotatfdotdotatfavkatffgberatfuwq6mf0x1s87oymcm2ad9lfsc3zppqofminusavzminushajenccrqminus2dot2dot4atfavzatfyvoatfflfgrzdotnim_Init000();
	(*inner)();
#else
	atzdotdotatfdotdotatfdotdotatfdotdotatfdotdotatfavkatffgberatfuwq6mf0x1s87oymcm2ad9lfsc3zppqofminusavzminushajenccrqminus2dot2dot4atfavzatfyvoatfflfgrzdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

